import type { DeliveryStageDefinition } from "./guidedDeliveryTypes";

export const deliveryStages: DeliveryStageDefinition[] = [
  {
    id: "requirements",
    index: 1,
    title: "Requirements & Intent",
    shortTitle: "Requirements",
    purpose: "Define the business problem, scope, stakeholders, constraints and operating context that every later decision must trace back to.",
    outcome: "A reviewed architecture brief that is specific enough for AIW to evaluate feasible architecture options.",
    architectureStage: "designIntent",
    workspace: "design",
    tasks: [
      { id: "intent", title: "Describe the problem and outcome", description: "State the problem, the business result and how success will be measured.", success: "The brief explains why the architecture exists and what it must enable.", checkIds: ["problem", "objectives"] },
      { id: "scope", title: "Define scope and stakeholders", description: "Record in-scope capabilities, exclusions, actors, owners and approvers.", success: "The boundary of the architecture is explicit and reviewable.", checkIds: ["scope", "stakeholders"] },
      { id: "constraints", title: "Capture constraints and existing estate", description: "Add regulatory, data, platform, legacy, delivery and integration constraints.", success: "AIW can distinguish feasible from theoretically attractive options.", checkIds: ["constraints", "feasibility"] },
      { id: "review", title: "Review the structured brief", description: "Resolve ambiguous assumptions and confirm the brief before moving to quality drivers.", success: "No critical context question remains unanswered.", checkIds: ["assumptions"] },
    ],
    outputs: ["Architecture Design Brief", "Scope & Stakeholder Register", "Constraint & Assumption Register"],
  },
  {
    id: "quality",
    index: 2,
    title: "Quality Drivers",
    shortTitle: "Drivers",
    purpose: "Turn the brief into measurable quality scenarios, explicit priorities and acknowledged trade-offs.",
    outcome: "A validated driver pack that can change recommendation ranking and later become fitness tests.",
    workspace: "quality",
    tasks: [
      { id: "prioritize", title: "Prioritise architecture drivers", description: "Weight the qualities that matter and avoid treating every attribute as equally critical.", success: "The top drivers and their relative importance are clear.", checkIds: ["drivers"] },
      { id: "scenarios", title: "Write measurable scenarios", description: "Complete source, stimulus, environment, artifact, response and response measure.", success: "Every scenario can be tested or evidenced.", checkIds: ["scenarios", "classification"] },
      { id: "tradeoffs", title: "Review conflicts and trade-offs", description: "Confirm what the architecture may sacrifice to improve the highest-priority qualities.", success: "The trade-off position is explicit rather than implied.", checkIds: ["tradeoff"] },
      { id: "plan", title: "Confirm the validation plan", description: "Turn uncertain scenarios into tests, evidence requests or implementation obligations.", success: "Each driver has a practical validation route.", checkIds: ["security", "resilience"] },
    ],
    outputs: ["Quality Scenario Pack", "Architecture Drivers Matrix", "Trade-off & Validation Plan"],
  },
  {
    id: "context",
    index: 3,
    title: "System Context & Journeys",
    shortTitle: "Context",
    purpose: "Turn approved intent, stakeholders and solution journeys into a clear system boundary, actor map, external-system context and interaction contract.",
    outcome: "A governed System Context model that preserves requirement and journey lineage before internal decomposition begins.",
    architectureStage: "logicalApplication",
    workspace: "design",
    tasks: [
      { id: "boundary", title: "Define the system of interest", description: "Confirm what AIW is designing, the organisational boundary and what remains external.", success: "The system boundary and scope are explicit and traceable to the approved requirements.", checkIds: ["context-boundary", "context-source"] },
      { id: "participants", title: "Map actors and external systems", description: "Promote approved stakeholders, actors and existing systems into the context model.", success: "Every major journey participant is represented with an accountable role.", checkIds: ["context-actors", "context-externals"] },
      { id: "interactions", title: "Define major interactions", description: "Map the information and outcomes exchanged across the system boundary.", success: "Context relationships explain who interacts, why and what is exchanged.", checkIds: ["context-interactions", "context-journeys"] },
      { id: "assure", title: "Review boundaries and obligations", description: "Identify trust crossings, missing interfaces and journeys that are not represented.", success: "The context model is complete enough to guide logical decomposition.", checkIds: ["context-coverage", "context-questions"] },
    ],
    outputs: ["System Context View", "Actor & External System Register", "Context Interaction Map", "Journey-to-Context Traceability"],
  },
  {
    id: "logical",
    index: 4,
    title: "Logical Application Architecture",
    shortTitle: "Logical App",
    purpose: "Model the technology-neutral domains, responsibilities, services, data ownership and interactions that solve the problem.",
    outcome: "A coherent logical architecture with explicit boundaries, relationships and style decisions.",
    architectureStage: "logicalApplication",
    workspace: "design",
    tasks: [
      { id: "style", title: "Choose the architecture direction", description: "Compare candidate styles and record why the chosen direction fits this context.", success: "The selected style is justified by drivers and feasibility.", checkIds: ["style"] },
      { id: "domains", title: "Model domains and responsibilities", description: "Create actors, business domains, external systems and logical services.", success: "Every logical component has a clear responsibility.", checkIds: ["objects", "existing"] },
      { id: "data", title: "Define data and interaction ownership", description: "Connect components and identify who owns data, commands, events and interfaces.", success: "Coupling and ownership are visible rather than hidden in prose.", checkIds: ["relationships", "ownership", "interfaces"] },
      { id: "patterns", title: "Review patterns and obligations", description: "Accept only patterns whose prerequisites and obligations are understood.", success: "Every accepted pattern creates traceable obligations.", checkIds: ["obligations"] },
    ],
    outputs: ["Logical Application View", "Responsibility & Data Ownership Matrix", "Style / Pattern Decision Record"],
  },
  {
    id: "realization",
    index: 5,
    title: "Application Realization",
    shortTitle: "Realization",
    purpose: "Translate the logical architecture into implementable applications, deployable units, APIs, events and ownership boundaries.",
    outcome: "An implementation-ready application model with lineage, contracts and accountable owners.",
    architectureStage: "applicationRealization",
    workspace: "design",
    tasks: [
      { id: "map", title: "Map logical components to realizations", description: "Create applications, APIs, modules and workers and link each to its logical source.", success: "No realization object is detached from the logical architecture.", checkIds: ["objects", "lineage"] },
      { id: "interfaces", title: "Define contracts and interfaces", description: "Specify inbound/outbound APIs, events, protocols, ownership and failure semantics.", success: "Every interaction has a named contract and responsibility.", checkIds: ["contracts", "workers"] },
      { id: "runtime", title: "Define runtime and ownership", description: "Assign team ownership, deployment responsibility and operational expectations.", success: "Every deployable unit has an owner and runtime intention.", checkIds: ["owners", "runtime"] },
      { id: "validate", title: "Validate coupling and transaction boundaries", description: "Review shared data, distributed transaction and integration risks.", success: "Implementation risks are recorded before technology selection.", checkIds: ["contracts", "workers"] },
    ],
    outputs: ["Application Realization View", "API & Event Contract Register", "Application Ownership Map"],
  },
  {
    id: "logicalTechnology",
    index: 6,
    title: "Logical Technology Architecture",
    shortTitle: "Logical Tech",
    purpose: "Select vendor-neutral platform capabilities that support the application model and its quality drivers.",
    outcome: "A technology capability architecture that is traceable, balanced and operable.",
    architectureStage: "logicalTechnology",
    workspace: "design",
    tasks: [
      { id: "capabilities", title: "Select required platform capabilities", description: "Model runtime, integration, data, security, observability and management capabilities.", success: "The technology model covers every application need.", checkIds: ["objects", "security", "data", "observability"] },
      { id: "trace", title: "Trace capabilities to applications", description: "Link each technology capability to the application or quality need it supports.", success: "No technology choice exists without a consumer or driver.", checkIds: ["trace"] },
      { id: "burden", title: "Review operational burden", description: "Consider skills, support, cost, change readiness and platform constraints.", success: "The design is feasible for the organisation that must operate it.", checkIds: ["obligations"] },
      { id: "decide", title: "Record technology decisions", description: "Document alternatives, trade-offs and any standards exception.", success: "Technology decisions are defensible and reversible where required.", checkIds: ["decision"] },
    ],
    outputs: ["Logical Technology View", "Technology Capability Matrix", "Technology Decision & Exception Register"],
  },
  {
    id: "physicalTechnology",
    index: 7,
    title: "Physical Technology & Deployment",
    shortTitle: "Physical Tech",
    purpose: "Define environments, zones, networks, deployment topology, resilience, capacity and operational placement.",
    outcome: "A deployable and recoverable topology with explicit security and operational evidence requirements.",
    architectureStage: "physicalTechnology",
    workspace: "design",
    tasks: [
      { id: "topology", title: "Model environments and deployment topology", description: "Place regions, zones, clusters, nodes and runtime infrastructure.", success: "The intended deployment shape is visible and complete.", checkIds: ["objects", "region", "zones"] },
      { id: "security", title: "Define networks and trust boundaries", description: "Model zones, ingress, egress, identity, secrets and protected data paths.", success: "Security boundaries are represented in the architecture model.", checkIds: ["network"] },
      { id: "resilience", title: "Design resilience and recovery", description: "Specify redundancy, failover, backup, RTO/RPO and degraded operation.", success: "The topology can demonstrate how it survives expected failures.", checkIds: ["resilience"] },
      { id: "evidence", title: "Attach runtime and capacity evidence", description: "Record inventory, sizing, cost, operational ownership and validation evidence.", success: "Deployment assumptions are testable and owned.", checkIds: ["capacity", "evidence"] },
    ],
    outputs: ["Physical Deployment View", "Resilience & Recovery Design", "Operational Readiness Checklist"],
  },
  {
    id: "review",
    index: 8,
    title: "Review & Assurance",
    shortTitle: "Review",
    purpose: "Run the architecture review, persist findings, resolve or waive blockers and submit an immutable baseline for disposition.",
    outcome: "An approved or explicitly changes-requested architecture baseline with governed evidence.",
    architectureStage: "validationRealization",
    workspace: "design",
    tasks: [
      { id: "run", title: "Run and record the review", description: "Generate findings, ADR proposals, fitness tests and a review scorecard and persist them to the project.", success: "The review is a governed record, not a transient page calculation.", checkIds: ["record", "findings", "decisions"] },
      { id: "triage", title: "Triage and assign findings", description: "Route each material issue to an owner with a fix, evidence request or waiver path.", success: "Every blocker has an accountable disposition route.", checkIds: ["assignment"] },
      { id: "resolve", title: "Resolve or waive blockers", description: "Re-run the review after changes and record authorised exceptions with expiry.", success: "No unresolved hard blocker remains.", checkIds: ["blockers"] },
      { id: "approve", title: "Submit and disposition the baseline", description: "Create an immutable snapshot and obtain independent reviewer approval.", success: "The baseline has a recorded approval decision.", checkIds: ["approval"] },
    ],
    outputs: ["Architecture Review Record", "ADR & Fitness Test Pack", "Approved Baseline & Evidence Ledger"],
  },
  {
    id: "sdd",
    index: 9,
    title: "SDD & Delivery Pack",
    shortTitle: "SDD Pack",
    purpose: "Assemble the approved architecture model, decisions, interfaces, diagrams, evidence and implementation obligations into the final delivery pack.",
    outcome: "A governed, traceable and downloadable solution design package.",
    architectureStage: "validationRealization",
    workspace: "design",
    tasks: [
      { id: "check", title: "Validate delivery completeness", description: "Confirm the approved baseline, artifact manifest and all required SDD sections.", success: "No mandatory section or approval evidence is missing.", checkIds: ["approved", "blockers", "model"] },
      { id: "preview", title: "Review the generated SDD", description: "Inspect diagrams, decisions, interfaces, risks, operations, migration and tests.", success: "The document accurately reflects the governed model.", checkIds: ["interfaces", "operations"] },
      { id: "generate", title: "Generate the final delivery pack", description: "Create the SDD, diagrams, manifests and evidence archive from the approved baseline.", success: "The generated package is reproducible and traceable.", checkIds: ["generated"] },
      { id: "handoff", title: "Record delivery handoff", description: "Record recipients, revision, approvals and implementation obligations.", success: "Delivery teams can act without reconstructing architecture intent.", checkIds: ["generated"] },
    ],
    outputs: ["Final SDD", "Architecture Diagram Set", "Artifact Manifest & Traceability Index", "Implementation Handoff Pack"],
  },
];

function hasText(value: unknown): boolean {
  if (Array.isArray(value)) return value.some(hasText);
  if (typeof value === "string") return value.trim().length > 0;
  if (typeof value === "number") return Number.isFinite(value);
  if (typeof value === "boolean") return true;
  return value != null && typeof value === "object" && Object.values(value as Record<string, unknown>).some(hasText);
}
