import type { ExperienceProfileId, WorkspaceModeId } from './experienceProfiles';

export interface WorkspaceExperienceDefinition {
  id: WorkspaceModeId;
  title: string;
  objective: string;
  ownerRoles: ExperienceProfileId[];
  primaryAction: string;
  inputs: string[];
  outputs: string[];
  completion: string;
  steps: string[];
  differentiators: string[];
  disposition: 'retain' | 'refine' | 'rebuild' | 'consolidate';
}

const definitions: Record<WorkspaceModeId, WorkspaceExperienceDefinition> = {
  cockpit: { id:'cockpit', title:'Role command surface', objective:'Show the work that needs attention now and route directly to an accountable task.', ownerRoles:['solution-architect','enterprise-architect','platform-architect','reviewer','knowledge-curator','administrator'], primaryAction:'Open highest-priority task', inputs:['Role','Project status','Readiness','Findings'], outputs:['Task route','Decision context'], completion:'The user reaches a task surface with a clear outcome.', steps:['Orient','Prioritise','Open task'], differentiators:['Role-specific mission','Readiness-driven routing'], disposition:'rebuild' },
  design: { id:'design', title:'Architecture modelling canvas', objective:'Create and evolve the canonical architecture model through interactive, governed views.', ownerRoles:['solution-architect','platform-architect'], primaryAction:'Continue modelling', inputs:['Requirements','Drivers','Pattern DNA','Existing model'], outputs:['Canonical objects','Relationships','Interfaces','Viewbook'], completion:'The active stage is coherent, traceable and ready for handoff.', steps:['Compose','Inspect','Review','Present'], differentiators:['Canonical graph','Interactive decomposition','Viewbook'], disposition:'retain' },
  activation: { id:'activation', title:'Project activation', objective:'Create a governed project, choose an entry path and establish accountable ownership.', ownerRoles:['solution-architect','enterprise-architect','platform-architect','administrator'], primaryAction:'Activate project', inputs:['Mission','Scope','Team','Constraints'], outputs:['Project','Branch','Role assignments'], completion:'A project and governed branch exist with a selected journey.', steps:['Frame','Assign','Activate'], differentiators:['Guided entry paths','Governed project truth'], disposition:'refine' },
  admin: { id:'admin', title:'AIW control plane', objective:'Operate identity, connectors, workers, evidence, signing, releases and recovery.', ownerRoles:['administrator','knowledge-curator'], primaryAction:'Resolve readiness blocker', inputs:['Platform configuration','Runtime evidence','Policies'], outputs:['Approved configuration','Promotion evidence','Audit trail'], completion:'Mandatory blockers are resolved or explicitly accepted.', steps:['Assess posture','Configure','Verify','Promote'], differentiators:['Durable workers','Evidence ledger','Independent signing','Promotion gates'], disposition:'rebuild' },
  quality: { id:'quality', title:'Quality driver studio', objective:'Turn vague non-functional expectations into measurable scenarios and weighted decisions.', ownerRoles:['solution-architect','enterprise-architect'], primaryAction:'Complete top quality scenario', inputs:['Business objectives','Constraints','Stakeholders'], outputs:['Quality scenarios','Weights','Conflicts'], completion:'Priority drivers are measurable and approved.', steps:['Capture','Measure','Prioritise','Approve'], differentiators:['Sensitivity analysis','Driver-to-pattern reasoning'], disposition:'refine' },
  portfolio: { id:'portfolio', title:'Portfolio intelligence', objective:'Identify cross-project risk, duplication, standards impact, dependency and investment concentration.', ownerRoles:['enterprise-architect'], primaryAction:'Investigate highest portfolio exposure', inputs:['Project models','Standards','Costs','Dependencies'], outputs:['Risk concentration','Reuse candidates','Investment actions'], completion:'Material exposure has an owner and disposition.', steps:['Scan','Concentrate','Compare','Act'], differentiators:['Cross-project graph','Reuse intelligence','Technology concentration'], disposition:'rebuild' },
  governance: { id:'governance', title:'Architecture governance', objective:'Evaluate decisions, exceptions, obligations and approval readiness against evidence.', ownerRoles:['enterprise-architect','reviewer','solution-architect'], primaryAction:'Disposition highest-severity item', inputs:['Findings','ADRs','Policies','Evidence'], outputs:['Approval','Request changes','Waiver','Expiry'], completion:'Every material item has a governed disposition.', steps:['Review','Challenge','Disposition','Record'], differentiators:['Evidence-bound approval','Waiver expiry','Decision consequences'], disposition:'rebuild' },
  comparison: { id:'comparison', title:'Architecture alternatives and merge', objective:'Compare branches, snapshots and architecture options before selecting or merging.', ownerRoles:['enterprise-architect','reviewer','solution-architect'], primaryAction:'Select comparison baseline', inputs:['Branches','Snapshots','Synthesis alternatives'], outputs:['Semantic diff','Merge plan','Decision package'], completion:'A preferred option or reviewed merge plan is recorded.', steps:['Select','Compare','Resolve','Apply'], differentiators:['Semantic branch diff','Conflict plan','Counterfactuals'], disposition:'rebuild' },
  collaboration: { id:'collaboration', title:'Architecture collaboration', objective:'Coordinate discussions, assignments and decisions without losing model context.', ownerRoles:['solution-architect','reviewer','enterprise-architect'], primaryAction:'Resolve open discussion', inputs:['Comments','Model selections','Assignments'], outputs:['Resolved thread','Decision trace'], completion:'Open collaboration items have an owner and outcome.', steps:['Discuss','Assign','Resolve'], differentiators:['Model-linked discussions','Optimistic concurrency'], disposition:'refine' },
  security: { id:'security', title:'Security and trust architecture', objective:'Model trust boundaries, identity flows, sensitive data and control coverage.', ownerRoles:['platform-architect','reviewer','solution-architect'], primaryAction:'Review highest trust-boundary gap', inputs:['Model','Identity posture','Data classifications'], outputs:['Trust view','Controls','Security findings'], completion:'Critical trust crossings are controlled and evidenced.', steps:['Map trust','Assess controls','Close gaps'], differentiators:['Trust-zone view','Identity evidence','Security consequences'], disposition:'rebuild' },
  drift: { id:'drift', title:'Intended versus observed architecture', objective:'Compare the approved model with runtime evidence and produce governed remediation.', ownerRoles:['platform-architect'], primaryAction:'Analyse latest inventory', inputs:['Canonical model','Runtime inventory','Telemetry'], outputs:['Drift report','Waiver','Remediation plan'], completion:'Material drift is remediated, waived or accepted.', steps:['Load evidence','Compare','Disposition','Remediate'], differentiators:['Topology inference','Semantic drift','Reviewable change sets'], disposition:'rebuild' },
  conformance: { id:'conformance', title:'Continuous conformance', objective:'Evaluate architecture fitness controls against repository and runtime evidence.', ownerRoles:['platform-architect','reviewer','enterprise-architect'], primaryAction:'Run conformance assessment', inputs:['Fitness tests','Repository evidence','Runtime evidence'], outputs:['Assessment','Remediation change set','Gate result'], completion:'Required controls have current evidence and disposition.', steps:['Collect','Evaluate','Remediate','Gate'], differentiators:['Generated fitness tests','CI evidence loop','Visual conformance'], disposition:'rebuild' },
  operations: { id:'operations', title:'Operational intelligence', objective:'Connect SLOs, topology, failure signals and remediation to the intended architecture.', ownerRoles:['platform-architect','administrator'], primaryAction:'Review breached SLO', inputs:['SLOs','Telemetry','Runtime topology'], outputs:['Operational drift','Alert policy','Remediation'], completion:'Critical operational risk has an owner and action.', steps:['Observe','Correlate','Decide','Act'], differentiators:['SLO-to-model trace','Failure-path reasoning','Topology evidence'], disposition:'rebuild' },
  knowledge: { id:'knowledge', title:'Knowledge curation studio', objective:'Triage claims, resolve contradictions, normalize records and publish governed knowledge.', ownerRoles:['knowledge-curator'], primaryAction:'Review next claim', inputs:['Source snapshots','Claims','Contradictions'], outputs:['Approved claim','Normalized Pattern DNA','Release candidate'], completion:'Every promoted item has provenance, review and permitted use.', steps:['Triage','Compare evidence','Decide','Promote'], differentiators:['Atomic claim receipts','Contradiction engine','Four-eyes promotion'], disposition:'rebuild' },
  patterns: { id:'patterns', title:'Architecture Composition', objective:'Compare Pattern DNA, preview topology and apply governed changes to a selected scope.', ownerRoles:['solution-architect','enterprise-architect','knowledge-curator'], primaryAction:'Compare recommended patterns', inputs:['Drivers','Forces','Scope','Knowledge release'], outputs:['Pattern decision','Generated topology','Obligations'], completion:'The selected pattern is applied or rejected with rationale.', steps:['Search','Compare','Preview','Apply','Validate'], differentiators:['Pattern DNA','Safe composition','Automatic obligations'], disposition:'refine' },
  synthesis: { id:'synthesis', title:'Architecture Options', objective:'Generate materially different, traceable architecture alternatives and select one deliberately.', ownerRoles:['solution-architect','enterprise-architect'], primaryAction:'Generate architecture alternatives', inputs:['Brief','Drivers','Constraints','Pattern DNA'], outputs:['Alternatives','Simulation','Decision package'], completion:'A selected alternative is applied with rationale and lineage.', steps:['Generate','Simulate','Compare','Select','Apply'], differentiators:['Deterministic eligibility','Counterfactuals','Provider-neutral first'], disposition:'rebuild' },
  runtime: { id:'runtime', title:'Observed architecture', objective:'Inspect runtime inventory, inferred topology, evidence age and model alignment.', ownerRoles:['platform-architect','administrator'], primaryAction:'Run or select collector', inputs:['Collectors','Telemetry','Inventory'], outputs:['Observed topology','Evidence ledger','Drift input'], completion:'A current observed architecture snapshot exists.', steps:['Connect','Collect','Infer','Approve'], differentiators:['Collector health','Topology inference','Evidence provenance'], disposition:'rebuild' },
  pilot: { id:'pilot', title:'Architecture Brain Evaluation Lab', objective:'Compare architecture outcomes, prepare blinded expert review and expose the remaining controlled-pilot evidence.', ownerRoles:['enterprise-architect','knowledge-curator','administrator'], primaryAction:'Run architecture outcome benchmark', inputs:['Canonical architecture models','Pinned intelligence releases','Expert review protocol'], outputs:['Outcome comparison','Blinded review pack','Pilot evidence gaps'], completion:'Reference calibration is reproducible and independently reviewable without claiming an unexecuted pilot.', steps:['Baseline','Compare','Review','Pilot'], differentiators:['Three-mode outcome comparison','Blinded expert review pack','Navigation and UX evidence'], disposition:'rebuild' },
};

export function workspaceExperienceDefinition(id: WorkspaceModeId): WorkspaceExperienceDefinition { return definitions[id]; }
export const workspaceExperienceRegistry = Object.values(definitions);
