import { access, readFile } from 'node:fs/promises';
import type { JobQueueAdapter } from '@aiw/integrations';
import { createEnterpriseSecretProvider } from './secrets.js';
import type { ProductionOperationsRepository } from './productionOperations.js';
export type BrainAcceptanceState='verified'|'configured'|'not-configured'|'failed'|'external-acceptance-required';
export interface BrainAcceptanceCheck { id:string;name:string;state:BrainAcceptanceState;mandatory:boolean;detail:string;evidence:string[]; }
export interface ProductionBrainAcceptanceReport { release:string;generatedAt:string;environment:string;productionAccepted:boolean;mandatoryBlockers:string[];checks:BrainAcceptanceCheck[];deterministicDesignAvailable:boolean; }
function configured(...values:Array<string|undefined>):boolean{return values.every((value)=>Boolean(value?.trim()))}
export async function buildProductionBrainAcceptance(input:{queue:JobQueueAdapter;operations:ProductionOperationsRepository;active?:boolean}):Promise<ProductionBrainAcceptanceReport>{
 const checks:BrainAcceptanceCheck[]=[]; const queue=await input.queue.health(); checks.push({id:'PMA-QUEUE',name:'Durable asynchronous queue',state:queue.ready&&queue.durable?'verified':queue.ready?'failed':'failed',mandatory:true,detail:queue.detail,evidence:[`adapter:${queue.adapter}`,`durable:${queue.durable}`]});
 const heartbeatFile=process.env.AIW_WORKER_HEARTBEAT_FILE; if(heartbeatFile){try{const hb=JSON.parse(await readFile(heartbeatFile,'utf8')) as{status?:string;at?:string;release?:string};const fresh=Date.now()-Date.parse(hb.at??'')<60_000;checks.push({id:'PMA-WORKER',name:'Worker heartbeat',state:fresh&&hb.status==='running'?'verified':'failed',mandatory:true,detail:`status=${hb.status}; at=${hb.at}`,evidence:[`release:${hb.release??'unknown'}`]})}catch(e){checks.push({id:'PMA-WORKER',name:'Worker heartbeat',state:'failed',mandatory:true,detail:e instanceof Error?e.message:String(e),evidence:[]})}}else checks.push({id:'PMA-WORKER',name:'Worker heartbeat',state:'not-configured',mandatory:true,detail:'AIW_WORKER_HEARTBEAT_FILE not configured for active probe.',evidence:[]});
 const ops=await input.operations.health();checks.push({id:'PMA-OBJECT',name:'S3/MinIO evidence object storage',state:ops.objectStore.ready?(ops.objectStore.adapter==='s3'?'verified':'external-acceptance-required'):'failed',mandatory:true,detail:ops.objectStore.detail,evidence:[`adapter:${ops.objectStore.adapter}`]});
 checks.push({id:'PMA-POSTGRES-RLS',name:'PostgreSQL durability and complete RLS',state:configured(process.env.DATABASE_URL)?'configured':'not-configured',mandatory:true,detail:configured(process.env.DATABASE_URL)?'DATABASE_URL configured; active cross-tenant denial drill remains required.':'DATABASE_URL missing.',evidence:['migration:018_rc10_58_production_mind_factory.sql']});
 checks.push({id:'PMA-REPOSITORY',name:'GitHub App/GitLab/Azure DevOps source adapter',state:configured(process.env.AIW_REPOSITORY_PROVIDER)?'configured':'not-configured',mandatory:true,detail:process.env.AIW_REPOSITORY_PROVIDER??'No live repository adapter selected.',evidence:['read-only-source-refresh:true']});
 checks.push({id:'PMA-OIDC',name:'Enterprise OIDC acceptance',state:configured(process.env.AIW_OIDC_ISSUER,process.env.AIW_OIDC_AUDIENCE)?'configured':'not-configured',mandatory:true,detail:process.env.AIW_OIDC_ISSUER??'OIDC issuer missing.',evidence:[]});
 checks.push({id:'PMA-OTEL',name:'OpenTelemetry export',state:configured(process.env.OTEL_EXPORTER_OTLP_ENDPOINT)?'configured':'not-configured',mandatory:true,detail:process.env.OTEL_EXPORTER_OTLP_ENDPOINT??'OTLP endpoint missing.',evidence:[]});
 const signer=process.env.AIW_RELEASE_SIGNER_PROVIDER;checks.push({id:'PMA-SIGNING',name:'Independent enterprise signing',state:signer?'configured':'not-configured',mandatory:true,detail:signer??'No managed signer selected.',evidence:signer?[`provider:${signer}`]:[]});
 const secretProvider=createEnterpriseSecretProvider();void secretProvider;checks.push({id:'PMA-SECRETS',name:'Secret-manager adapters',state:'verified',mandatory:true,detail:'Vault, AWS Secrets Manager, Azure Key Vault and GCP Secret Manager adapters are installed; target credentials require environment acceptance.',evidence:['vault','aws-secrets-manager','azure-key-vault','gcp-secret-manager']});
 const backupEvidence=process.env.AIW_BACKUP_RESTORE_EVIDENCE; if(backupEvidence){try{await access(backupEvidence);checks.push({id:'PMA-BACKUP',name:'Backup and restore drill',state:'verified',mandatory:true,detail:backupEvidence,evidence:['evidence-file:readable']})}catch(e){checks.push({id:'PMA-BACKUP',name:'Backup and restore drill',state:'failed',mandatory:true,detail:e instanceof Error?e.message:String(e),evidence:[]})}}else checks.push({id:'PMA-BACKUP',name:'Backup and restore drill',state:'not-configured',mandatory:true,detail:'No independent backup/restore evidence configured.',evidence:[]});
 const mandatoryBlockers=checks.filter((item)=>item.mandatory&&item.state!=='verified').map((item)=>`${item.id}:${item.state}`);return{release:'0.10.0-rc.10.58.0',generatedAt:new Date().toISOString(),environment:process.env.NODE_ENV??'development',productionAccepted:mandatoryBlockers.length===0,mandatoryBlockers,checks,deterministicDesignAvailable:true};
}
