import type { ArtifactBundle, ArchitectureProject, RepositoryBinding, RepositoryPullRequest } from '@aiw/domain';
import { createPullRequestPreview } from '@aiw/engine';

function base64(value: string): string { return Buffer.from(value, 'utf8').toString('base64'); }
function githubCoordinates(url: string): { owner: string; repo: string } {
  const match = url.match(/github\.com[/:]([^/]+)\/([^/.]+)(?:\.git)?$/); if (!match?.[1] || !match[2]) throw new Error('INVALID_GITHUB_REPOSITORY_URL'); return { owner: match[1], repo: match[2] };
}
function gitlabProject(url: string): string { const match = url.match(/gitlab\.com[/:](.+?)(?:\.git)?$/); if (!match?.[1]) throw new Error('INVALID_GITLAB_REPOSITORY_URL'); return encodeURIComponent(match[1]); }
async function requestJson(url: string, init: RequestInit): Promise<any> { const response = await fetch(url, { ...init, signal: AbortSignal.timeout(20_000) }); const text = await response.text(); const body = text ? JSON.parse(text) : {}; if (!response.ok) throw new Error(`REPOSITORY_PROVIDER_${response.status}:${body.message ?? body.error ?? text}`); return body; }

export async function openRepositoryPullRequest(project: ArchitectureProject, binding: RepositoryBinding, bundle: ArtifactBundle, token: string): Promise<RepositoryPullRequest> {
  if (!token) throw new Error('REPOSITORY_TOKEN_NOT_CONFIGURED');
  const preview = createPullRequestPreview(project, binding, bundle);
  if (binding.provider === 'github') {
    const { owner, repo } = githubCoordinates(binding.repositoryUrl); const api = `https://api.github.com/repos/${owner}/${repo}`;
    const headers = { authorization: `Bearer ${token}`, accept: 'application/vnd.github+json', 'content-type': 'application/json', 'x-github-api-version': '2022-11-28' };
    const ref = await requestJson(`${api}/git/ref/heads/${encodeURIComponent(binding.defaultBranch)}`, { headers });
    const commit = await requestJson(`${api}/git/commits/${ref.object.sha}`, { headers });
    const treeEntries = [];
    for (const file of bundle.files) { const blob = await requestJson(`${api}/git/blobs`, { method: 'POST', headers, body: JSON.stringify({ content: base64(file.content), encoding: 'base64' }) }); treeEntries.push({ path: `${binding.architecturePath.replace(/\/[^/]+$/, '')}/${file.path}`, mode: '100644', type: 'blob', sha: blob.sha }); }
    const tree = await requestJson(`${api}/git/trees`, { method: 'POST', headers, body: JSON.stringify({ base_tree: commit.tree.sha, tree: treeEntries }) });
    const newCommit = await requestJson(`${api}/git/commits`, { method: 'POST', headers, body: JSON.stringify({ message: preview.title, tree: tree.sha, parents: [ref.object.sha] }) });
    await requestJson(`${api}/git/refs`, { method: 'POST', headers, body: JSON.stringify({ ref: `refs/heads/${preview.sourceBranch}`, sha: newCommit.sha }) });
    const pr = await requestJson(`${api}/pulls`, { method: 'POST', headers, body: JSON.stringify({ title: preview.title, head: preview.sourceBranch, base: preview.targetBranch, body: 'Generated by AIW after explicit human approval. Review all architecture and remediation artifacts before merge.' }) });
    return { ...preview, status: 'opened', url: pr.html_url };
  }
  if (binding.provider === 'gitlab') {
    const projectId = gitlabProject(binding.repositoryUrl); const api = `https://gitlab.com/api/v4/projects/${projectId}`; const headers = { 'private-token': token, 'content-type': 'application/json' };
    await requestJson(`${api}/repository/branches`, { method: 'POST', headers, body: JSON.stringify({ branch: preview.sourceBranch, ref: preview.targetBranch }) });
    await requestJson(`${api}/repository/commits`, { method: 'POST', headers, body: JSON.stringify({ branch: preview.sourceBranch, commit_message: preview.title, actions: bundle.files.map((file) => ({ action: 'create', file_path: `${binding.architecturePath.replace(/\/[^/]+$/, '')}/${file.path}`, content: file.content })) }) });
    const mr = await requestJson(`${api}/merge_requests`, { method: 'POST', headers, body: JSON.stringify({ source_branch: preview.sourceBranch, target_branch: preview.targetBranch, title: preview.title, description: 'Generated by AIW after explicit human approval.' }) });
    return { ...preview, status: 'opened', url: mr.web_url };
  }
  throw new Error('REPOSITORY_PROVIDER_WRITE_NOT_SUPPORTED');
}
