import {readStoredProject} from './project-storage.js';
import {withFinalReview} from './public/review-domain.js';
import {journeyIndex} from './public/journey-context.js';
import {digest} from './public/brain-integrity.js';
import {neighbourhood} from './public/object-graph.js';
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}}),text=(v,n=4000)=>typeof v==='string'?v.trim().slice(0,n):'';
export function activityStatement(env,identity,project,event,stamp){const {owner,actor}=identity,id=crypto.randomUUID(),at=event.at||new Date().toISOString(),doc={id,at,actor,...event};const tail=stamp?' WHERE EXISTS(SELECT 1 FROM projects WHERE owner_id=? AND id=? AND index_stamp=?)':'';return env.DB.prepare('INSERT INTO project_activity(owner_id,project_id,id,actor_id,document,created_at) SELECT ?,?,?,?,?,?'+tail).bind(owner,project,id,actor,JSON.stringify(doc),at,...(stamp?[owner,project,stamp]:[]));}
export async function handleObjects(request,env,identity,project){
 const {owner,actor,role}=identity,url=new URL(request.url),at=new Date().toISOString();
 if(!['GET','POST'].includes(request.method))return json({error:'Unsupported object action.'},405);
 if(request.method==='POST'&&request.headers.get('Origin')!==url.origin)return json({error:'Use this action within your project.'},403);
 const row=await env.DB.prepare('SELECT document,revision FROM projects WHERE owner_id=? AND id=?').bind(owner,project).first();if(!row)return json({error:'Project unavailable.'},404);
 try{
  if(url.pathname==='/api/activity'){
   if(request.method==='POST'){const raw=await request.json();if(raw.action!=='read'||!/^\d{4}-\d{2}-\d{2}T/.test(raw.through||'')||raw.through>at)throw Error('Choose the last displayed activity date.');await env.DB.prepare('INSERT INTO activity_reads(owner_id,project_id,actor_id,seen_at) VALUES(?,?,?,?) ON CONFLICT(owner_id,project_id,actor_id) DO UPDATE SET seen_at=MAX(seen_at,excluded.seen_at)').bind(owner,project,actor,raw.through).run();return json({saved:true});}
   const [before,beforeId]=(url.searchParams.get('before')||'9999|~').split('|'),rows=await env.DB.prepare('SELECT id,document FROM project_activity WHERE owner_id=? AND project_id=? AND (created_at<? OR (created_at=? AND id<?)) ORDER BY created_at DESC,id DESC LIMIT 61').bind(owner,project,before,before,beforeId||'').all(),read=await env.DB.prepare('SELECT seen_at FROM activity_reads WHERE owner_id=? AND project_id=? AND actor_id=?').bind(owner,project,actor).first();const events=rows.results.slice(0,60).map(r=>({...JSON.parse(r.document),id:r.id}));return json({actor,events:events.map(e=>({...e,unread:e.actor!==actor&&e.at>(read?.seen_at||'')})),next:rows.results.length>60?events.at(-1).at+'|'+events.at(-1).id:null,through:events[0]?.at||null});
  }
  const p=withFinalReview((await readStoredProject(env,owner,row.document)).document),index=journeyIndex(p),objectId=url.searchParams.get('object');
  if(url.pathname==='/api/graph'){if(request.method!=='GET')return json({error:'Graph slices are read-only.'},405);return json({revision:row.revision,...neighbourhood(p,objectId,{depth:url.searchParams.get('depth')||1,limit:url.searchParams.get('limit')||40})});}
  const node=index.nodes.get(objectId);if(!node)return json({error:'Choose an existing object in this project.'},404);const basis=digest([node.record,index.edges.filter(e=>e.from===objectId||e.to===objectId)]);
  const rows=await env.DB.prepare('SELECT document,revision FROM object_discussions WHERE owner_id=? AND project_id=? AND object_id=? ORDER BY updated_at DESC LIMIT 100').bind(owner,project,objectId).all(),threads=rows.results.map(r=>({...JSON.parse(r.document),revision:r.revision}));
  if(request.method==='GET')return json({actor,role,object:{id:objectId,title:node.title,chapter:node.chapter,basis},threads:threads.map(t=>({...t,current:t.basis===basis})),members:[{actor_id:owner,role:'owner'},...(await env.DB.prepare('SELECT actor_id,role FROM project_access WHERE owner_id=? AND project_id=?').bind(owner,project).all()).results]});
  if(role==='viewer')return json({error:'Viewer access permits reading discussions.'},403);if(p.workspace?.status==='archived')throw Error('Restore the project before opening or changing discussions.');const body=await request.text();if(body.length>16000)throw Error('Keep discussion updates below 16 KB.');const raw=JSON.parse(body);if(!text(raw.text))throw Error('Record the observation or response.');let thread;
  if(raw.action==='create'){
   if(threads.length>=100)throw Error('Resolve or reuse an existing thread for this object.');if(!text(raw.title,180)||raw.basis!==basis)throw Error('Name the discussion and review the current object.');if(raw.assignee&&raw.assignee!==owner){const a=await env.DB.prepare('SELECT role FROM project_access WHERE owner_id=? AND project_id=? AND actor_id=?').bind(owner,project,raw.assignee).first();if(!a||a.role==='viewer')throw Error('Assign an existing project contributor.');}
   thread={id:crypto.randomUUID(),objectId,title:text(raw.title,180),author:actor,assignee:raw.assignee||null,basis,state:'open',at,events:[{at,actor,action:'opened',text:text(raw.text)}]};await env.DB.batch([env.DB.prepare('INSERT INTO object_discussions(owner_id,project_id,id,object_id,document,revision,updated_at) VALUES(?,?,?,?,?,1,?)').bind(owner,project,thread.id,objectId,JSON.stringify(thread),at),activityStatement(env,identity,project,{at,kind:'discussion',objectId,title:thread.title,threadId:thread.id})]);
  }else{
   thread=threads.find(t=>t.id===raw.id);if(!thread)throw Error('Choose a saved discussion.');if(raw.revision!==thread.revision)return json({error:'This thread changed. Reload before responding.',conflict:true},409);if(thread.events.length>=200)throw Error('Start a follow-up thread with a reference to this discussion.');if(!['comment','resolve','reopen'].includes(raw.action))throw Error('Choose a discussion action.');if(raw.action!=='comment'){if(!['owner','editor'].includes(role)&&thread.author!==actor&&thread.assignee!==actor)return json({error:'Only the owner, an editor or the responsible contributor can change the thread state.'},403);if(raw.action==='resolve'&&(raw.basis!==basis||raw.reviewed!==true))throw Error('Review the current object before resolving this discussion.');thread.state=raw.action==='resolve'?'resolved':'open';thread.basis=basis;}
   thread.events.push({at,actor,action:raw.action,text:text(raw.text)});const revision=thread.revision;delete thread.revision;const updated=at+'#'+crypto.randomUUID();const changed=await env.DB.batch([env.DB.prepare('UPDATE object_discussions SET document=?,revision=revision+1,updated_at=? WHERE owner_id=? AND project_id=? AND id=? AND revision=?').bind(JSON.stringify(thread),updated,owner,project,thread.id,revision),env.DB.prepare('INSERT INTO project_activity(owner_id,project_id,id,actor_id,document,created_at) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM object_discussions WHERE owner_id=? AND project_id=? AND id=? AND updated_at=?)').bind(owner,project,crypto.randomUUID(),actor,JSON.stringify({at,actor,kind:'discussion',objectId,threadId:thread.id,title:thread.title+' · '+raw.action}),at,owner,project,thread.id,updated)]);if(!changed[0].meta.changes)return json({error:'The discussion changed during this save.',conflict:true},409);
  }return json({saved:true,id:thread.id});
 }catch(e){return json({error:e.message},400);}
}
