import {readStoredProject,saveStoredProject} from './project-storage.js';
import {withFinalReview,inheritedFindings} from './public/review-domain.js';
import {journeyIndex} from './public/journey-context.js';
import {workingBasis} from './public/workbench-domain.js';
import {applyEvidenceCommand} from './public/evidence-domain.js';
import {previewFeedback,applyFeedbackCommand} from './public/delivery-feedback.js';
import {previewSpecification,applyStandardsCommand} from './public/standards-domain.js';
import {connectionProfiles,fetchConnector} from './connection-adapters.js';
import {activityStatement} from './object-service.js';
import {digest} from './public/brain-integrity.js';
const json=(v,status=200)=>new Response(JSON.stringify(v),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}}),text=(v,n=4000)=>typeof v==='string'?v.trim().slice(0,n):'',prefix=(owner,project)=>'operations/'+encodeURIComponent(owner)+'/'+project+'/';
export function operationStatement(env,owner,project,kind,data,at=new Date().toISOString()){return env.DB.prepare('INSERT INTO operation_events(owner_id,project_id,id,kind,document,created_at) VALUES(?,?,?,?,?,?)').bind(owner,project,crypto.randomUUID(),kind,JSON.stringify(data),at);}
const jobs=async(env,owner,project)=>{const rows=await env.DB.prepare('SELECT * FROM project_jobs WHERE owner_id=? AND project_id=? ORDER BY created_at DESC LIMIT 100').bind(owner,project).all();return rows.results.map(r=>({...JSON.parse(r.document),id:r.id,kind:r.kind,status:r.status,revision:r.revision,leaseUntil:r.lease_until,createdAt:r.created_at,updatedAt:r.updated_at}));};
const jobById=async(env,owner,project,id)=>{if(!id)return null;const r=await env.DB.prepare('SELECT * FROM project_jobs WHERE owner_id=? AND project_id=? AND id=?').bind(owner,project,id).first();return r?{...JSON.parse(r.document),id:r.id,kind:r.kind,status:r.status,revision:r.revision,leaseUntil:r.lease_until,createdAt:r.created_at,updatedAt:r.updated_at}:null;};
const connections=async(env,owner,project)=>{const rows=await env.DB.prepare('SELECT document,revision FROM project_connections WHERE owner_id=? AND project_id=? ORDER BY updated_at DESC LIMIT 40').bind(owner,project).all();return rows.results.map(r=>({...JSON.parse(r.document),revision:r.revision}));};
export async function runProjectJob(env,identity,project,id,{fetcher=fetch}={}){
 const {owner,actor}=identity,job=await jobById(env,owner,project,id);if(!job||job.status==='completed'||job.status==='cancelled')return;const at=new Date().toISOString(),lease=new Date(Date.now()+60000).toISOString();if(job.status==='running'&&job.leaseUntil>at)return;
 const leased=await env.DB.prepare("UPDATE project_jobs SET status='running',revision=revision+1,lease_until=?,updated_at=? WHERE owner_id=? AND project_id=? AND id=? AND revision=? AND (status IN ('queued','failed') OR (status='running' AND lease_until<?))").bind(lease,at,owner,project,id,job.revision,at).run();if(!leased.meta.changes)return;
 const started=Date.now(),key=prefix(owner,project)+id+'/'+crypto.randomUUID()+'.json';try{
  const row=await env.DB.prepare('SELECT document,revision FROM projects WHERE owner_id=? AND id=?').bind(owner,project).first();if(!row)throw Error('Project unavailable.');const p=withFinalReview((await readStoredProject(env,owner,row.document)).document);let output;
  if(job.kind==='validate')output={kind:'validation',basis:workingBasis(p),projectRevision:row.revision,findings:inheritedFindings(p),at};
  else{const connection=(await connections(env,owner,project)).find(c=>c.id===job.connectionId),profile=connectionProfiles(env,owner).find(p=>p.id===connection?.profileId);if(!connection?.enabled||!profile||connection.revision!==job.connectionRevision||digest(profile)!==job.profileStamp)throw Error('The connection changed or is unavailable. Prepare a new job.');output=await fetchConnector(env,profile,{cursor:job.cursor,etag:job.etag,fetcher});output.connectionId=connection.id;output.origin='connection:'+connection.id;output.title=connection.title;output.projectBasis=workingBasis(p);output.connectionRevision=connection.revision;}
  await env.FILES.put(key,JSON.stringify(output));const doc={...job,outputKey:key,outputHash:digest(output),attempts:(job.attempts||0)+1,result:{kind:output.kind,records:output.records?.length||0,next:output.next,etag:output.etag,unchanged:output.unchanged===true},actor,elapsedMs:Date.now()-started};delete doc.status;delete doc.revision;
  const result=await env.DB.prepare("UPDATE project_jobs SET document=?,status='completed',revision=revision+1,lease_until=NULL,updated_at=? WHERE owner_id=? AND project_id=? AND id=? AND status='running' AND lease_until=?").bind(JSON.stringify(doc),new Date().toISOString(),owner,project,id,lease).run();if(!result.meta.changes)await env.FILES.delete(key);else await operationStatement(env,owner,project,'job',{id,kind:job.kind,status:'completed',elapsedMs:doc.elapsedMs,actor}).run();
 }catch(e){await env.FILES.delete(key);const doc={...job,error:text(e.message,700),attempts:(job.attempts||0)+1,actor};delete doc.status;delete doc.revision;await env.DB.prepare("UPDATE project_jobs SET document=?,status='failed',revision=revision+1,lease_until=NULL,updated_at=? WHERE owner_id=? AND project_id=? AND id=? AND status='running' AND lease_until=?").bind(JSON.stringify(doc),new Date().toISOString(),owner,project,id,lease).run();await operationStatement(env,owner,project,'job',{id,kind:job.kind,status:'failed',elapsedMs:Date.now()-started,actor,error:doc.error}).run();}
}
async function resultFor(env,owner,project,job){if(job.status!=='completed'||!job.outputKey?.startsWith(prefix(owner,project)))throw Error('Complete this job before reviewing its result.');const file=await env.FILES.get(job.outputKey);if(!file)throw Error('The job result is unavailable.');const result=JSON.parse(await file.text());if(digest(result)!==job.outputHash)throw Error('The saved result failed its integrity check.');return result;}
function feedFor(p,result,raw){const selected=new Set(raw.selected||[]);if(!selected.size||selected.size>200)throw Error('Select 1–200 observations for this review.');const ids=new Set(p.artefacts.filter(a=>a.type==='requirement').map(a=>a.id));const records=result.records.filter(r=>selected.has(r.externalId)).map(r=>{const requirements=[...new Set(raw.mapping?.[r.externalId]||r.requirements||[])];if(!requirements.length||requirements.some(id=>!ids.has(id)))throw Error('Map '+r.externalId+' to existing requirement IDs.');return {...r,requirements};});if(records.length!==selected.size)throw Error('A selected observation is absent from the saved result.');return {schema:'aiw.delivery.v1',origin:result.origin,records};}
export async function handleOperations(request,env,identity,project,ctx){
 const {owner,actor,role}=identity,url=new URL(request.url),action=url.searchParams.get('action')||'list',at=new Date().toISOString();if(!['GET','POST'].includes(request.method))return json({error:'Unsupported operation.'},405);if(request.method==='POST'&&request.headers.get('Origin')!==url.origin)return json({error:'Use these actions from your private project.'},403);
 const row=await env.DB.prepare('SELECT document,revision FROM projects WHERE owner_id=? AND id=?').bind(owner,project).first();if(!row)return json({error:'Project unavailable.'},404);
 try{
  const stored=await readStoredProject(env,owner,row.document),p=withFinalReview(stored.document);let raw={};if(request.method==='POST'){if(!['owner','editor'].includes(role))return json({error:'Only project editors can manage jobs and sync.'},403);const body=await request.text();if(body.length>60000)throw Error('Keep operation settings below 60 KB.');raw=JSON.parse(body);if(p.workspace?.status==='archived')throw Error('Restore this project before preparing work.');}
  if(url.pathname==='/api/operations'){
   if(request.method==='GET'){const events=(await env.DB.prepare('SELECT kind,document,created_at FROM operation_events WHERE owner_id=? AND project_id=? ORDER BY created_at DESC LIMIT 100').bind(owner,project).all()).results;const ai=(await env.DB.prepare('SELECT status,COUNT(*) AS count,SUM(used_tokens) AS used_tokens,SUM(CASE WHEN used_tokens IS NULL THEN reserved_tokens ELSE 0 END) AS reserved_tokens FROM intelligence_runs WHERE owner_id=? AND project_id=? AND created_at>? GROUP BY status').bind(owner,project,new Date(Date.now()-86400000).toISOString()).all()).results;const retrieval=(await env.DB.prepare('SELECT status,COUNT(*) AS count,SUM(used_tokens) AS used_tokens,SUM(CASE WHEN used_tokens IS NULL THEN reserved_tokens ELSE 0 END) AS reserved_tokens FROM brain_retrieval_runs WHERE owner_id=? AND project_id=? AND created_at>? GROUP BY status').bind(owner,project,new Date(Date.now()-86400000).toISOString()).all()).results;return json({actor,role,projectRevision:row.revision,policy:p.workspace?.aiPolicy||{enabled:true,hourlyRequests:10,dailyTokens:1000000},aiLast24h:ai,retrievalLast24h:retrieval,events:events.map(e=>({kind:e.kind,at:e.created_at,...JSON.parse(e.document)})),jobs:(await jobs(env,owner,project)).map(({outputKey,profileStamp,...j})=>j)});}
   if(role!=='owner')return json({error:'Only the project owner sets disclosure and budgets.'},403);if(raw.action!=='policy'||raw.revision!==row.revision)return json({error:'Review the latest project settings.',conflict:true},409);if(typeof raw.enabled!=='boolean'||!Number.isInteger(raw.hourlyRequests)||raw.hourlyRequests<0||raw.hourlyRequests>10||!Number.isInteger(raw.dailyTokens)||raw.dailyTokens<0||raw.dailyTokens>2000000)throw Error('Use 0–10 requests per hour and 0–2,000,000 reserved tokens per day.');if(!Array.isArray(raw.excludedObjectIds)||raw.excludedObjectIds.length>200||raw.excludedObjectIds.some(id=>typeof id!=='string'||!journeyIndex(p).nodes.has(id)))throw Error('Exclude at most 200 existing project object IDs.');p.workspace??={};p.workspace.aiPolicy={enabled:raw.enabled,hourlyRequests:raw.hourlyRequests,dailyTokens:raw.dailyTokens,redactContacts:raw.redactContacts===true,excludedObjectIds:[...new Set(raw.excludedObjectIds||[])].slice(0,200),reason:text(raw.reason),actor,at};if(!p.workspace.aiPolicy.reason)throw Error('Record the disclosure policy and budget rationale.');const saved=await saveStoredProject(env,owner,project,p,row.revision,at,stored.keys);if(!saved.meta.changes)return json({error:'The project changed.',conflict:true},409);return json({saved:true,revision:row.revision+1});
  }
  if(url.pathname==='/api/connections'){
   const all=await connections(env,owner,project),profiles=connectionProfiles(env,owner);if(request.method==='GET')return json({connections:all,profiles:profiles.map(p=>({id:p.id,title:p.title,kind:p.kind,configured:!p.tokenEnv||!!env[p.tokenEnv]})),role});if(role!=='owner')return json({error:'Only the project owner configures a source connection.'},403);const old=raw.id?all.find(c=>c.id===raw.id):null;if(raw.id&&!old)throw Error('Choose an existing connection.');if(old&&raw.revision!==old.revision)return json({error:'The connection changed.',conflict:true},409);const profile=profiles.find(p=>p.id===raw.profileId);if(!profile||!text(raw.title,180))throw Error('Choose an authorized server profile and name this connection.');const c={id:old?.id||crypto.randomUUID(),profileId:profile.id,kind:profile.kind,title:text(raw.title,180),enabled:raw.enabled===true,actor,at};if(old){const result=await env.DB.prepare('UPDATE project_connections SET document=?,revision=revision+1,updated_at=? WHERE owner_id=? AND project_id=? AND id=? AND revision=?').bind(JSON.stringify(c),at,owner,project,c.id,old.revision).run();if(!result.meta.changes)return json({error:'Connection changed during save.',conflict:true},409);}else{if(all.length>=40)throw Error('At most forty project connections are supported.');await env.DB.prepare('INSERT INTO project_connections(owner_id,project_id,id,document,revision,updated_at) VALUES(?,?,?,?,1,?)').bind(owner,project,c.id,JSON.stringify(c),at).run();}return json({saved:true,id:c.id});
  }
  const all=await jobs(env,owner,project),id=url.searchParams.get('id')||raw.id,job=await jobById(env,owner,project,id);
  if(request.method==='GET'){if(!id)return json({jobs:all.map(({outputKey,profileStamp,...j})=>j)});if(!job)throw Error('Choose a project job.');return json({job,...(action==='result'?{result:await resultFor(env,owner,project,job)}:{})});}
  if(action==='create'){
   if(!['sync','validate'].includes(raw.kind))throw Error('Choose a validation or source-sync job.');const connection=raw.kind==='sync'?(await connections(env,owner,project)).find(c=>c.id===raw.connectionId&&c.enabled):null,profile=connection?connectionProfiles(env,owner).find(p=>p.id===connection.profileId):null;if(raw.kind==='sync'&&!profile)throw Error('Enable an authorized connection first.');if(!/^[a-f0-9-]{36}$/.test(raw.requestId||''))throw Error('Start a new job request.');const doc={id:raw.requestId,kind:raw.kind,connectionId:connection?.id,connectionRevision:connection?.revision,profileStamp:profile?digest(profile):null,cursor:text(raw.cursor,2000),etag:text(raw.etag,500),basis:workingBasis(p),actor,attempts:0};const hash=digest(doc),existing=await jobById(env,owner,project,doc.id);if(existing){if(existing.inputHash!==hash)throw Error('This request ID already belongs to different work.');return json({id:existing.id,status:existing.status});}doc.inputHash=hash;
   const count=await env.DB.prepare('SELECT COUNT(*) AS count FROM project_jobs WHERE owner_id=? AND project_id=? AND created_at>?').bind(owner,project,new Date(Date.now()-3600000).toISOString()).first();if(count.count>=30)return json({error:'Thirty jobs have been prepared this hour. Resume existing jobs before adding more.'},429);await env.DB.prepare("INSERT INTO project_jobs(owner_id,project_id,id,kind,status,input_hash,document,revision,created_at,updated_at) VALUES(?,?,?,?,'queued',?,?,1,?,?)").bind(owner,project,doc.id,doc.kind,hash,JSON.stringify(doc),at,at).run();return json({id:doc.id,status:'queued'},201);
  }
  if(!job)throw Error('Choose a saved job.');if(action==='run'){if(job.attempts>=3&&job.status==='failed')throw Error('Three attempts failed. Correct the connection and prepare a new job.');const task=runProjectJob(env,identity,project,job.id,{fetcher:env.CONNECTION_FETCH||fetch});if(ctx?.waitUntil){ctx.waitUntil(task);return json({id:job.id,status:'running'},202);}await task;return json({job:await jobById(env,owner,project,job.id)});}
  if(action==='cancel'){await env.DB.prepare("UPDATE project_jobs SET status='cancelled',revision=revision+1,lease_until=NULL,updated_at=? WHERE owner_id=? AND project_id=? AND id=? AND status IN ('queued','running','failed')").bind(at,owner,project,id).run();return json({saved:true});}
  if(!['preview','apply'].includes(action))throw Error('Unknown job action.');const result=await resultFor(env,owner,project,job);if(result.unchanged)return json({unchanged:true});if(result.kind==='validation')return json(result);const connection=(await connections(env,owner,project)).find(c=>c.id===job.connectionId);if(!connection?.enabled||connection.revision!==job.connectionRevision)throw Error('This source connection changed. Prepare a new read.');const liveProfile=connectionProfiles(env,owner).find(profile=>profile.id===connection.profileId);if(!liveProfile||digest(liveProfile)!==job.profileStamp)throw Error('The server source profile changed. Prepare a new read.');let command,q;if(result.kind==='specification'){q=previewSpecification(p,{spec:result.spec,identity:result.origin,from:raw.from,to:raw.to});command={type:'standards.import',payload:{spec:result.spec,identity:result.origin,from:raw.from,to:raw.to,stamp:q.stamp,reviewed:true}};}else{const feed=feedFor(p,result,raw);q=previewFeedback(p,feed);command={type:'feedback.import',payload:{feed,stamp:q.stamp,reviewed:true,resolutions:raw.resolutions}};}
  const stamp=digest([job.outputHash,q.stamp,row.revision]);if(action==='preview')return json({preview:q,stamp,revision:row.revision});if(raw.reviewed!==true||raw.stamp!==stamp||raw.revision!==row.revision)return json({error:'Review the current incoming change preview.',conflict:true},409);
  if(q.counts&&q.counts.new===0&&q.counts.update===0)return json({unchanged:true,revision:row.revision});
  let doc=applyEvidenceCommand(p,{type:'evidence.source',payload:{title:result.title+' · '+result.at,location:'Retrieved source connection '+connection.id+' · SHA-256 '+result.hash,version:result.hash,date:result.at.slice(0,10),excerpt:result.body.slice(0,8000),status:'Unconfirmed'}},at).document;const source=doc.coauthoring.sources.at(-1);source.originalJob={id:job.id,hash:result.hash};if(command.type==='feedback.import'){command.payload.sourceId=source.id;doc=applyFeedbackCommand(doc,command,at,actor).document;}else doc=applyStandardsCommand(doc,command,at,actor).document;
  const saved=await saveStoredProject(env,owner,project,doc,row.revision,at,stored.keys,stamp=>[activityStatement(env,identity,project,{kind:'source-sync',title:'Reviewed source update · '+connection.title,jobId:job.id},stamp)]);if(!saved.meta.changes)return json({error:'The model changed while applying this source update.',conflict:true},409);return json({saved:true,revision:row.revision+1});
 }catch(e){return json({error:e.message},400);}
}
