import {readStoredProject,saveStoredProject} from './project-storage.js';
import {withFinalReview} from './public/review-domain.js';
import {applyEvidenceCommand} from './public/evidence-domain.js';
import {applyWorkbenchCommand} from './public/workbench-domain.js';
import {sha256} from './public/workbook-reader.js';
const json=(v,status=200)=>new Response(JSON.stringify(v),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}}),clean=(v,n=4000)=>typeof v==='string'?v.trim().slice(0,n):'';
const kinds=new Set(['technology','control','runbook','requirement-template','scenario-template','decision-template','document-template','standard','pattern','reference-architecture']);
async function organization(env,actor,id){const row=await env.DB.prepare('SELECT * FROM organizations WHERE id=?').bind(id).first();if(!row)return null;const member=await env.DB.prepare('SELECT role FROM organization_members WHERE organization_id=? AND actor_id=?').bind(id,actor).first();return member?{...row,...JSON.parse(row.document),ownerId:row.owner_id,role:member.role}:null;}
const canEdit=o=>['administrator','editor'].includes(o.role);
async function signature(env,org,body){const stored=await env.FILES.get('organizations/'+org+'/signing-key');if(!stored)throw Error('The organization signing key is unavailable.');const key=await crypto.subtle.importKey('raw',await stored.arrayBuffer(),{name:'HMAC',hash:'SHA-256'},false,['sign']);return [...new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(body)))].map(n=>n.toString(16).padStart(2,'0')).join('');}
export async function verifyOrganizationRelease(env,release){const {signature:received,...payload}=release;return typeof received==='string'&&received===await signature(env,release.organizationId,JSON.stringify(payload));}
export async function handleOrganizations(request,env,actor,projectId){
 const url=new URL(request.url),action=url.searchParams.get('action')||'list',id=url.searchParams.get('organization'),at=new Date().toISOString();
 if(!['GET','POST'].includes(request.method))return json({error:'Unsupported workspace action.'},405);
 if(request.method==='POST'&&request.headers.get('Origin')!==url.origin)return json({error:'Use organization actions from your private workspace.'},403);
 try{
 let raw={};if(request.method==='POST'){const body=await request.text();if(body.length>120000)throw Error('Keep this library change below 120 KB.');raw=JSON.parse(body);}
 if(action==='list'&&request.method==='GET'){const rows=await env.DB.prepare('SELECT o.id,o.document,o.revision,m.role FROM organizations o JOIN organization_members m ON o.id=m.organization_id WHERE m.actor_id=? ORDER BY o.updated_at DESC').bind(actor).all();return json({organizations:rows.results.map(r=>({...JSON.parse(r.document),id:r.id,revision:r.revision,role:r.role}))});}
 if(action==='create'&&request.method==='POST'){
  if(!clean(raw.title,100))throw Error('Name the organization workspace.');if(!env.FILES)throw Error('Private organization storage is unavailable.');const org=crypto.randomUUID(),document={title:clean(raw.title,100),purpose:clean(raw.purpose),owner:actor,at};const key='organizations/'+org+'/signing-key';await env.FILES.put(key,crypto.getRandomValues(new Uint8Array(32)));
  try{await env.DB.batch([env.DB.prepare('INSERT INTO organizations(id,owner_id,document,revision,updated_at) VALUES(?,?,?,1,?)').bind(org,actor,JSON.stringify(document),at),env.DB.prepare('INSERT INTO organization_members(organization_id,actor_id,role,created_at) VALUES(?,?,?,?)').bind(org,actor,'administrator',at)]);}catch(e){await env.FILES.delete(key);throw e;}
  return json({id:org,...document,role:'administrator',revision:1},201);
 }
 const org=await organization(env,actor,id);if(!org)return json({error:'This organization workspace is unavailable.'},404);
 if(action==='members'){
  if(request.method==='GET'){const rows=await env.DB.prepare('SELECT actor_id,role,created_at FROM organization_members WHERE organization_id=?').bind(id).all();return json({members:rows.results,role:org.role,owner:org.ownerId});}
  if(org.role!=='administrator')return json({error:'Only organization administrators manage membership.'},403);if(!/^[A-Za-z0-9_@.\-]{1,180}$/.test(raw.actorId||'')||raw.actorId===org.ownerId)throw Error('Choose a different existing authenticated account.');if(!['administrator','editor','reviewer','reader','remove'].includes(raw.role))throw Error('Choose an organization role.');
  if(raw.role==='remove')await env.DB.prepare('DELETE FROM organization_members WHERE organization_id=? AND actor_id=?').bind(id,raw.actorId).run();else await env.DB.prepare('INSERT INTO organization_members(organization_id,actor_id,role,created_at) VALUES(?,?,?,?) ON CONFLICT(organization_id,actor_id) DO UPDATE SET role=excluded.role').bind(id,raw.actorId,raw.role,at).run();return json({saved:true,note:'Membership recorded; Site access remains separately owner-controlled. No message or invitation was sent.'});
 }
 if(action==='library'){
  const rows=await env.DB.prepare('SELECT * FROM organization_library WHERE organization_id=? ORDER BY updated_at DESC').bind(id).all();const entries=rows.results.map(r=>({...JSON.parse(r.document),revision:r.revision}));
  if(request.method==='GET')return json({organization:{id,title:org.title,role:org.role},entries});
  if(!canEdit(org))return json({error:'Only organization editors can prepare library changes.'},403);const prior=raw.id?entries.find(e=>e.id===raw.id):null;if(raw.id&&!prior)throw Error('Choose an existing library entry.');if(prior&&raw.revision!==prior.revision)return json({error:'This library entry changed. Reload before editing.',conflict:true},409);
  if(!kinds.has(raw.kind)||!clean(raw.title,160)||!clean(raw.content,30000))throw Error('Choose a library type and provide its title and content.');if(!clean(raw.source?.location)||!clean(raw.source?.passage,12000)||!clean(raw.source?.revision,180))throw Error('Preserve the source location, exact passage and revision.');
  if(raw.reviewDue&&!/^\d{4}-\d{2}-\d{2}$/.test(raw.reviewDue))throw Error('Use an ISO review date.');
  const source={location:clean(raw.source.location),passage:clean(raw.source.passage,12000),revision:clean(raw.source.revision,180),licence:clean(raw.source.licence,600)},hash=await sha256(new TextEncoder().encode(JSON.stringify(source)));
  const entry={id:prior?.id||crypto.randomUUID(),kind:raw.kind,title:clean(raw.title,160),content:clean(raw.content,30000),conditions:clean(raw.conditions),limitations:clean(raw.limitations),lifecycle:clean(raw.lifecycle),reviewDue:clean(raw.reviewDue,30),source:{...source,hash},status:'draft',author:prior?.author||actor,lastEditor:actor,at,history:prior?[...(prior.history||[]),{at:prior.at,revision:prior.revision,status:prior.status,content:prior.content,source:prior.source,review:prior.review}]:[]};
  if(prior){const result=await env.DB.prepare('UPDATE organization_library SET document=?,revision=revision+1,updated_at=? WHERE organization_id=? AND id=? AND revision=?').bind(JSON.stringify(entry),at,id,entry.id,raw.revision).run();if(!result.meta.changes)return json({error:'A concurrent library change needs review.',conflict:true},409);}else await env.DB.prepare('INSERT INTO organization_library(organization_id,id,document,revision,updated_at) VALUES(?,?,?,1,?)').bind(id,entry.id,JSON.stringify(entry),at).run();return json({saved:true,id:entry.id});
 }
 if(action==='review'&&request.method==='POST'){
  if(!['administrator','reviewer'].includes(org.role))return json({error:'This action requires an organization reviewer.'},403);const row=await env.DB.prepare('SELECT * FROM organization_library WHERE organization_id=? AND id=?').bind(id,raw.id).first();if(!row)throw Error('Choose a library entry.');if(raw.revision!==row.revision)return json({error:'Review the current entry revision.',conflict:true},409);const entry=JSON.parse(row.document);
  if(actor===entry.author||actor===entry.lastEditor)return json({error:'A different authenticated reviewer must assess this entry.'},403);if(!['approved','changes requested','withdrawn'].includes(raw.outcome)||raw.reviewed!==true||!clean(raw.rationale)||!clean(raw.evidence))throw Error('Record the review outcome, rationale and review evidence.');if(raw.outcome==='approved'&&(!entry.conditions||!entry.limitations))throw Error('State applicability conditions and limitations before approving.');entry.status=raw.outcome;entry.review={at,actor,outcome:raw.outcome,rationale:clean(raw.rationale),evidence:clean(raw.evidence),sourceHash:entry.source.hash,contentHash:await sha256(new TextEncoder().encode(entry.content))};entry.history.push({at,actor,event:'Review',...entry.review});
  const result=await env.DB.prepare('UPDATE organization_library SET document=?,revision=revision+1,updated_at=? WHERE organization_id=? AND id=? AND revision=?').bind(JSON.stringify(entry),at,id,raw.id,raw.revision).run();if(!result.meta.changes)return json({error:'The entry changed during review.',conflict:true},409);return json({saved:true});
 }
 if(action==='releases'){
  if(request.method==='GET'){const rows=await env.DB.prepare('SELECT document FROM organization_releases WHERE organization_id=? ORDER BY created_at DESC').bind(id).all();return json({releases:rows.results.map(r=>JSON.parse(r.document))});}
  if(org.role!=='administrator')return json({error:'Only organization administrators publish library releases.'},403);if(!clean(raw.title,160)||!Array.isArray(raw.entryIds)||!raw.entryIds.length||raw.entryIds.length>100||raw.reviewed!==true)throw Error('Name and review a release of 1–100 approved entries.');const entries=[];
  for(const entryId of [...new Set(raw.entryIds)]){const row=await env.DB.prepare('SELECT document,revision FROM organization_library WHERE organization_id=? AND id=?').bind(id,entryId).first();if(!row)throw Error('A selected library entry is unavailable.');const e={...JSON.parse(row.document),revision:row.revision};if(e.status!=='approved'||e.review?.actor===e.author||e.review?.actor===e.lastEditor||e.review?.sourceHash!==e.source.hash||e.review?.contentHash!==await sha256(new TextEncoder().encode(e.content)))throw Error('Every release entry needs independent review of its exact source and content.');if(e.reviewDue&&e.reviewDue<at.slice(0,10))throw Error('An entry is overdue for review.');entries.push(e);}
  const release={id:crypto.randomUUID(),organizationId:id,title:clean(raw.title,160),entries,createdBy:actor,at,engine:'organization-library-1',authority:'Reviewed organization guidance with retained conditions; no automatic project adoption.'};release.signature=await signature(env,id,JSON.stringify(release));await env.DB.prepare('INSERT INTO organization_releases(organization_id,id,document,created_at) VALUES(?,?,?,?)').bind(id,release.id,JSON.stringify(release),at).run();return json({release},201);
 }
 if(action==='install'&&request.method==='POST'){
  if(!canEdit(org))return json({error:'Only organization editors can install library guidance into their projects.'},403);const row=await env.DB.prepare('SELECT document,revision FROM projects WHERE owner_id=? AND id=?').bind(actor,projectId).first();if(!row)return json({error:'Choose a project you own.'},404);if(raw.revision!==row.revision)return json({error:'Reload this project before installing a release.',conflict:true},409);const rel=await env.DB.prepare('SELECT document FROM organization_releases WHERE organization_id=? AND id=?').bind(id,raw.releaseId).first();if(!rel)throw Error('Choose an existing release.');const release=JSON.parse(rel.document);if(!await verifyOrganizationRelease(env,release))throw Error('The release signature could not be verified.');if(raw.reviewed!==true)throw Error('Review this release and its effect on your project.');
  const stored=await readStoredProject(env,actor,row.document);let p=withFinalReview(stored.document);if(p.workspace?.status==='archived')throw Error('Restore this project before changing its guidance.');if(p.workspace.organizationPins?.some(pin=>pin.releaseId===release.id))return json({saved:true,unchanged:true});
  for(const entry of release.entries){const latest=await env.DB.prepare('SELECT document FROM organization_library WHERE organization_id=? AND id=?').bind(id,entry.id).first();if(!latest||JSON.parse(latest.document).status==='withdrawn')throw Error('An entry in this release has been withdrawn.');const old=p.workbench?.catalogue?.find(e=>e.organization?.id===id&&e.organization.entryId===entry.id);p=applyEvidenceCommand(p,{type:'evidence.source',payload:{title:entry.title,excerpt:entry.source.passage,location:entry.source.location,version:entry.source.revision,status:'Unconfirmed'}},at).document;const sourceId=p.coauthoring.sources.at(-1).id;const kind=entry.kind;
   p=applyWorkbenchCommand(p,{type:'workspace.catalogue',payload:{id:old?.id,kind,title:entry.title,content:entry.content,owner:org.title,status:'approved',sourceId,reviewed:true,reviewNote:'Installed signed organization release '+release.title+'; reviewer '+entry.review.actor+'. Conditions: '+entry.conditions+'. Limitations: '+entry.limitations}},at,actor).document;
   const target=old?p.workbench.catalogue.find(e=>e.id===old.id):p.workbench.catalogue.at(-1);target.organization={id,title:org.title,entryId:entry.id,entryKind:entry.kind,releaseId:release.id,signature:release.signature,contentHash:entry.review.contentHash,sourceHash:entry.source.hash,conditions:entry.conditions,limitations:entry.limitations,reviewDue:entry.reviewDue,assurance:{eligible:true,status:'Verified signed release',signature:release.signature}};
  }
  p.workspace.organizationId=id;p.workspace.organizationPins=[...(p.workspace.organizationPins||[]),{organizationId:id,releaseId:release.id,title:release.title,signature:release.signature,at,actor}];const result=await saveStoredProject(env,actor,projectId,p,row.revision,at,stored.keys);if(!result.meta.changes)return json({error:'The project changed during installation.',conflict:true},409);return json({saved:true,revision:row.revision+1});
 }
 return json({error:'Organization action not found.'},404);
 }catch(e){return json({error:e.message},400);}
}

export async function refreshOrganizationAssurance(env,actor,p){
 const entries=p.workbench?.catalogue?.filter(e=>e.organization)||[];if(!entries.length)return p;const releases=new Map(),members=new Map();
 for(const e of entries){const org=e.organization;let eligible=false,status='Organization release verification unavailable';try{
  if(!members.has(org.id))members.set(org.id,await organization(env,actor,org.id));if(!members.get(org.id))throw Error('Organization membership no longer permits new use of this guidance');
  const key=org.id+':'+org.releaseId;if(!releases.has(key)){const row=await env.DB.prepare('SELECT document FROM organization_releases WHERE organization_id=? AND id=?').bind(org.id,org.releaseId).first();const release=row?JSON.parse(row.document):null;if(!release||!await verifyOrganizationRelease(env,release))throw Error('Release signature unavailable or invalid');releases.set(key,release);}const release=releases.get(key),entry=release.entries.find(v=>v.id===org.entryId);if(!entry||release.signature!==org.signature)throw Error('Entry is not part of the pinned signed release');
  const source=p.coauthoring.sources.find(s=>s.id===e.sourceId)?.versions.at(-1);if(!source||source.excerpt!==entry.source.passage||e.content!==entry.content)throw Error('Local guidance differs from its signed release');const latest=await env.DB.prepare('SELECT document FROM organization_library WHERE organization_id=? AND id=?').bind(org.id,org.entryId).first();if(!latest||JSON.parse(latest.document).status==='withdrawn')throw Error('Organization guidance was withdrawn');if(entry.reviewDue&&entry.reviewDue<new Date().toISOString().slice(0,10))throw Error('Organization guidance is overdue for review');eligible=true;status='Verified signed release';
 }catch(err){status=err.message;}org.assurance={eligible,status,signature:org.signature};}
 return p;
}
