import {validateNativePackage,PACKAGE_SCHEMA} from './public/model-exchange.js';
import {readStoredProject,saveStoredProject} from './project-storage.js';
import {withFinalReview,chapterSummaries} from './public/review-domain.js';
import {createProject} from './public/projects-domain.js';
import {journeyIndex} from './public/journey-context.js';
import {sha256} from './public/workbook-reader.js';
import {digest} from './public/brain-integrity.js';
const json=(v,status=200)=>new Response(JSON.stringify(v),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}}),MAX=12*1024*1024;
const encoded=bytes=>{let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.slice(i,i+8192));return btoa(binary);};
function decoded(s){if(typeof s!=='string'||s.length>MAX*1.4)throw Error('Invalid recovery file encoding.');return Uint8Array.from(atob(s),c=>c.charCodeAt(0));}
async function unpackRecovery(pack){
 if(pack?.schema!=='aiw.recovery.gzip.v1')return pack;
 if(!Number.isInteger(pack.expandedBytes)||pack.expandedBytes<1||pack.expandedBytes>64*1024*1024)throw Error('The recovery package expands beyond the 64 MB project limit.');
 const bytes=decoded(pack.body);if(await sha256(bytes)!==pack.checksum)throw Error('The recovery package checksum does not match.');
 const reader=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip')).getReader(),parts=[];let size=0;try{for(;;){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>pack.expandedBytes||size>64*1024*1024){await reader.cancel();throw Error('The recovery package expands beyond its declared size.');}parts.push(value);}}finally{reader.releaseLock();}if(size!==pack.expandedBytes)throw Error('The recovery package size does not match.');return JSON.parse(await new Blob(parts).text());
}
async function packRecovery(pack){const bytes=new TextEncoder().encode(JSON.stringify(pack));if(bytes.length>64*1024*1024)throw Error('The expanded recovery package exceeds 64 MB. Use a database and files backup.');if(bytes.length<512*1024)return pack;const compressed=new Uint8Array(await new Response(new Blob([bytes]).stream().pipeThrough(new CompressionStream('gzip'))).arrayBuffer()),result={schema:'aiw.recovery.gzip.v1',expandedBytes:bytes.length,checksum:await sha256(compressed),body:encoded(compressed)};if(JSON.stringify(result).length>MAX*.95)throw Error('This compressed recovery package exceeds 12 MB. Use a database and files backup.');return result;}
async function body(request){const reader=request.body?.getReader();if(!reader)throw Error('Choose a project export or recovery package.');let size=0,out='',decode=new TextDecoder();for(;;){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>MAX){await reader.cancel();throw Error('This recovery request exceeds 12 MB. Use the local project database backup for larger projects.');}out+=decode.decode(value,{stream:true});}return JSON.parse(out+decode.decode());}
export async function buildRecovery(env,identity,project){
 const row=await env.DB.prepare('SELECT document,revision FROM projects WHERE owner_id=? AND id=?').bind(identity.owner,project).first();if(!row)throw Error('Project unavailable.');const p=withFinalReview((await readStoredProject(env,identity.owner,row.document)).document),files=[],seen=new Set();let total=0;
 async function retain(key,metadata){if(seen.has(key))return;seen.add(key);const item=await env.FILES.get(key);if(!item)throw Error('A referenced original is missing; recovery is incomplete.');const bytes=new Uint8Array(await item.arrayBuffer());total+=bytes.length;if(total>7*1024*1024)throw Error('Original files exceed this portable recovery limit. Use a local database and files backup for the complete project.');files.push({...metadata,key,hash:await sha256(bytes),bytes:bytes.length,body:encoded(bytes)});}
 const uploads=(await env.DB.prepare('SELECT * FROM workbook_uploads WHERE owner_id=? AND project_id=?').bind(identity.owner,project).all()).results;
 for(const u of uploads)await retain(u.storage_key,{kind:'workbook',metadata:{id:u.id,filename:u.filename,sha256:u.sha256,bytes:u.bytes,created_at:u.created_at}});
 const attachments=(await env.DB.prepare('SELECT * FROM project_attachments WHERE owner_id=? AND project_id=?').bind(identity.owner,project).all()).results;
 for(const a of attachments)await retain(a.storage_key,{kind:'attachment',metadata:{id:a.id,filename:a.filename,sha256:a.sha256,bytes:a.bytes,source_id:a.source_id,created_at:a.created_at,actor_id:a.actor_id}});
 for(const d of p.intake?.datasets||[])for(const v of d.versions||[]){const key=p.workspace?.recovery?.keys?.[v.snapshotKey]||v.snapshotKey;if(key)await retain(key,{kind:'snapshot',originalKey:v.snapshotKey});}
 for(const f of p.workspace?.recovery?.files||[])if(!seen.has(f.key))await retain(f.key,{kind:f.kind,metadata:f.metadata,originalKey:f.originalKey});
 const audit={};for(const table of ['project_reviews','object_discussions','project_activity'])audit[table]=(await env.DB.prepare('SELECT document FROM '+table+' WHERE owner_id=? AND project_id=?').bind(identity.owner,project).all()).results.map(r=>JSON.parse(r.document));
 const packageBody={schema:'aiw.recovery.v1',at:new Date().toISOString(),project:p,revision:row.revision,files,audit,authority:'Portable source history. Imported identities are historical assertions; access grants, server secrets and live approvals are not transferred.'};const bytes=JSON.stringify(packageBody);return packRecovery({...packageBody,checksum:await sha256(new TextEncoder().encode(bytes))});
}
export async function previewRecovery(raw){const encodedPack=raw.package||raw,pack=await unpackRecovery(encodedPack),p=pack.project||pack.document||pack;if(!p||typeof p.name!=='string'||!Array.isArray(p.artefacts)||!Array.isArray(p.relationships))throw Error('Choose a complete AIW project JSON export.');for(const key of ['quality','decisions','logical','realisation','technology','technologyRealisation','interfaces','security','runtime','finalReview'])if(!p[key]||p[key].storageKey)throw Error('The export must include the complete '+key+' chapter.');if(p.caseExtensions||p.requirementsStorage||p.coauthoring?.storageKey||p.workbench?.storageKey||p.knowledge?.storageKey||p.changes?.storageKey)throw Error('Use the hydrated project export, not internal storage metadata.');const {checksum,...payload}=pack;if(pack.schema==='aiw.recovery.v1'&&checksum!==await sha256(new TextEncoder().encode(JSON.stringify(payload))))throw Error('The recovery package checksum does not match.');if((pack.files||[]).length>200)throw Error('This package exceeds the portable file count.');
 let bytes=0;for(const f of pack.files||[]){const data=decoded(f.body);bytes+=data.length;if(bytes>7*1024*1024||data.length!==f.bytes||await sha256(data)!==f.hash||!['workbook','snapshot','attachment'].includes(f.kind))throw Error('A recovery file failed integrity or size checks.');}
 const native=pack.schema===PACKAGE_SCHEMA?await validateNativePackage(pack):null;const hydrated=withFinalReview(p),index=journeyIndex(hydrated);if(index.nodes.size>100000)throw Error('Use the managed migration path above 100,000 objects.');if(hydrated.finalReview.baselines.some(b=>!b.source||b.storageKey))throw Error('Every baseline must contain its original frozen snapshot.');return {name:p.name,objects:native?.objects||index.nodes.size,relationships:native?.relationships||index.edges.length,chapters:chapterSummaries(hydrated),files:(pack.files||[]).length,sourceBytes:bytes,baselines:p.finalReview.baselines.length,hash:await sha256(new TextEncoder().encode(JSON.stringify(encodedPack))),limits:pack.schema==='aiw.recovery.v1'?['Restored as a new private project. Imported review history is retained as historical evidence.','Organisation releases require verified membership and reviewed adoption.']:['Project JSON does not include original uploaded files or authenticated collaboration history. Attach originals separately or use a recovery package.']};}
export async function handleRecovery(request,env,identity,project){const {owner,actor,role}=identity,url=new URL(request.url),action=url.searchParams.get('action')||'export';if(request.method!=='GET'&&request.headers.get('Origin')!==url.origin)return json({error:'Use recovery from the private workspace.'},403);try{
 if(action==='export'&&request.method==='GET'){const pack=await buildRecovery(env,identity,project);return new Response(JSON.stringify(pack),{headers:{'Content-Type':'application/json','Content-Disposition':'attachment; filename="AIW_Recovery.json"','Cache-Control':'no-store'}});}
 if(action==='audit'&&request.method==='GET'){const row=await env.DB.prepare('SELECT document FROM projects WHERE owner_id=? AND id=?').bind(owner,project).first();if(!row)return json({error:'Project unavailable.'},404);const p=JSON.parse(row.document),key=p.workspace?.recovery?.auditKey;if(!key)return json({audit:null});if(!key.startsWith('recovery/'+encodeURIComponent(owner)+'/'+project+'/'))throw Error('Invalid historical audit reference.');return json(JSON.parse(await (await env.FILES.get(key)).text()));}
 if(!['preview','restore'].includes(action)||request.method!=='POST')return json({error:'Unknown recovery action.'},405);const raw=await body(request),preview=await previewRecovery(raw.package);if(action==='preview')return json(preview);if(raw.reviewed!==true||raw.hash!==preview.hash||typeof raw.name!=='string'||!raw.name.trim()||raw.name.length>100)throw Error('Name the restored project and review its complete source package.');
 const pack=await unpackRecovery(raw.package),p=structuredClone(pack.project||pack.document||pack),id='project-'+crypto.randomUUID(),at=new Date().toISOString(),prefix='recovery/'+encodeURIComponent(actor)+'/'+id+'/',created=[];let modelView=null;if(pack.schema===PACKAGE_SCHEMA&&pack.exploration){p.workbench??={version:1,alternatives:[],analyses:[],catalogue:[],views:[],assignments:[]};modelView='imported-view-'+preview.hash.slice(0,16);p.workbench.views??=[];p.workbench.views=p.workbench.views.filter(v=>v.id!==modelView);p.workbench.views.push({id:modelView,title:'Imported perspective',chapter:4,tab:'model',objectId:pack.exploration.selectedId||'',exploration:pack.exploration,at,actor});}const originalId=p.id;p.id=id;p.name=raw.name.trim();for(const v of p.workbench?.views||[]){if(v.exploration&&!v.exploration.baselineId){for(const key of ['scopeId','selectedId'])if(v.exploration[key]==='system:'+originalId)v.exploration[key]='system:'+id;}if(!v.exploration?.baselineId&&v.objectId==='system:'+originalId)v.objectId='system:'+id;}p.workspace={...p.workspace,status:'active',template:'imported',...(modelView?{initialModelViewId:modelView}:{}),organizationPins:[],restoredAt:at,restoredBy:actor,recovery:{originProjectId:(pack.project||pack.document||pack).id,packageHash:preview.hash,keys:{},files:[],auditKey:prefix+'audit.json'}};delete p.workspace.organizationId;if(p.knowledge){p.knowledge.pins=[];if(p.knowledge.repositorySync)for(const receipt of p.knowledge.repositorySync.releases||[])receipt.assurance={eligible:false,status:'Imported historical proof; obtain a receipt for this project.'};p.knowledge.history??=[];p.knowledge.history.push({at,type:'import',reason:'Historical knowledge retained; project pins require review.'});}if(p.workbench)for(const e of p.workbench.catalogue||[]){e.status='draft';if(e.organization)e.organization.assurance={eligible:false,status:'Restored history; review and adopt the signed release again.'};}
 try{
  for(const f of pack.files||[]){const key=prefix+crypto.randomUUID();await env.FILES.put(key,decoded(f.body));created.push(key);p.workspace.recovery.keys[f.originalKey||f.key]=key;p.workspace.recovery.files.push({kind:f.kind,key,originalKey:f.originalKey||f.key,metadata:f.metadata,hash:f.hash,bytes:f.bytes});}
  await env.FILES.put(p.workspace.recovery.auditKey,JSON.stringify({importedAt:at,authority:'Historical imported assertions, not current authenticated approvals.',audit:pack.audit||{}}));created.push(p.workspace.recovery.auditKey);
  const empty=createProject({name:p.name,template:'blank'},id,at);await env.DB.prepare('INSERT INTO projects(owner_id,id,document,revision,updated_at) VALUES(?,?,?,1,?)').bind(actor,id,JSON.stringify(empty),at).run();const saved=await saveStoredProject(env,actor,id,withFinalReview(p),1,at,new Map());if(!saved.meta.changes)throw Error('The restored project could not be saved.');return json({id,revision:2,name:p.name,objects:preview.objects,modelView},201);
 }catch(e){await env.DB.prepare('DELETE FROM requirement_index WHERE owner_id=? AND project_id=?').bind(actor,id).run();await env.DB.prepare('DELETE FROM projects WHERE owner_id=? AND id=?').bind(actor,id).run();await Promise.allSettled(created.map(key=>env.FILES.delete(key)));throw e;}
 }catch(e){return json({error:e.message},400);}}
export async function recoveredFile(env,owner,project,{kind,id,key}){const row=await env.DB.prepare('SELECT document FROM projects WHERE owner_id=? AND id=?').bind(owner,project).first();if(!row)return null;const files=JSON.parse(row.document).workspace?.recovery?.files||[],item=files.find(f=>f.kind===kind&&(id?f.metadata?.id===id:f.originalKey===key));if(!item)return null;if(!item.key.startsWith('recovery/'+encodeURIComponent(owner)+'/'+project+'/'))throw Error('Invalid imported file reference.');const file=await env.FILES.get(item.key);if(!file)throw Error('The restored original file is missing.');if(await sha256(await file.arrayBuffer())!==item.hash)throw Error('The restored original failed its integrity check.');return {row:{...item.metadata,storage_key:item.key},file};}
