import type { ArchitectureProject } from './types.js';

const now = new Date().toISOString();

export const sampleProject: ArchitectureProject = {
  schemaVersion: '0.8.0',
  tenantId: 'tenant-reference',
  id: 'project-order-to-payment',
  name: 'Order-to-Payment Reference Design',
  description: 'A reference project demonstrating scoped styles, lineage, validation and proposed architecture changes.',
  activeStage: 'logicalApplication',
  objectives: [
    'Process customer orders reliably',
    'Protect payment processing from dependency failures',
    'Support measurable availability and latency objectives',
  ],
  constraints: ['Cloud agnostic logical design', 'No direct storage of payment card data'],
  assumptions: ['Initial team size is eight engineers', 'Peak volume is 250 orders per second'],
  qualityPriorities: [
    { attributeId: 'availability', weight: 5, rationale: 'Revenue-critical order processing' },
    { attributeId: 'faultTolerance', weight: 5, rationale: 'External payment providers can fail' },
    { attributeId: 'scalability', weight: 4 },
    { attributeId: 'modifiability', weight: 4 },
    { attributeId: 'simplicity', weight: 3 },
    { attributeId: 'costEfficiency', weight: 3 },
  ],
  qualityScenarios: [
    {
      id: 'qs-payment-provider-latency',
      attributeId: 'availability',
      source: 'External payment provider',
      stimulus: 'Provider becomes unavailable or exceeds timeout',
      environment: 'Peak production traffic',
      artifact: 'Payment integration boundary',
      response: 'Isolate the failure and preserve order status for safe retry',
      responseMeasure: 'No confirmed order is lost; checkout degrades within 3 seconds',
      weight: 5,
    },
  ],
  styleDecisions: [
    {
      id: 'style-decision-orders',
      styleId: 'STYLE-EVENT-DRIVEN',
      scopeNodeId: 'logical-order-domain',
      stage: 'logicalApplication',
      rationale: 'Decouple order progression from payment provider availability while preserving explicit synchronous query paths where justified.',
      status: 'accepted',
    },
  ],
  patternSelections: [
    {
      id: 'pattern-selection-outbox',
      patternId: 'PAT-OUTBOX',
      scopeNodeId: 'logical-order-domain',
      stage: 'applicationRealization',
      rationale: 'Reliably publish order events after local state changes.',
      status: 'considering',
      obligationsAcknowledged: [],
    },
  ],
  nodes: [
    {
      id: 'system-order-payment',
      kind: 'System',
      stage: 'logicalApplication',
      label: 'Order-to-Payment Platform',
      description: 'Software system boundary for order capture, payment authorization and governed fulfilment handoff.',
      properties: { decompositionLevel: 'system', owner: 'Digital Commerce', objectiveIds: ['OBJ-001','OBJ-002','OBJ-003'], systemOfInterest: true },
      lineageFrom: [],
      positions: { logicalApplication: { x: 270, y: 30 } },
      tags: ['system','system-of-interest','context'],
      status: 'draft',
    },
    {
      id: 'actor-customer',
      kind: 'Actor',
      stage: 'logicalApplication',
      label: 'Customer',
      properties: { decompositionLevel: 'landscape' },
      lineageFrom: [],
      positions: { logicalApplication: { x: 40, y: 160 } },
      tags: ['external'],
      status: 'draft',
    },
    {
      id: 'logical-order-domain',
      kind: 'Domain',
      stage: 'logicalApplication',
      label: 'Order Domain',
      properties: { owner: 'Commerce Team', decompositionLevel: 'system' },
      lineageFrom: [],
      positions: { logicalApplication: { x: 280, y: 100 } },
      tags: ['core-domain'],
      status: 'draft',
    },
    {
      id: 'logical-order-service',
      kind: 'LogicalService',
      stage: 'logicalApplication',
      label: 'Order Service',
      properties: { communicationPreference: 'mixed', objectiveIds: ['OBJ-001','OBJ-003'], decompositionLevel: 'system' },
      lineageFrom: [],
      positions: { logicalApplication: { x: 310, y: 200 } },
      tags: ['business-service'],
      status: 'draft',
    },
    {
      id: 'logical-payment-service',
      kind: 'LogicalService',
      stage: 'logicalApplication',
      label: 'Payment Service',
      properties: { dataClassification: 'confidential', objectiveIds: ['OBJ-002'], decompositionLevel: 'system' },
      lineageFrom: [],
      positions: { logicalApplication: { x: 580, y: 200 } },
      tags: ['business-service'],
      status: 'draft',
    },
    {
      id: 'realization-api-gateway',
      kind: 'ApplicationComponent',
      stage: 'applicationRealization',
      label: 'Commerce API Gateway',
      properties: { responsibility: 'External API policy and routing', authentication: 'OIDC', rateLimitPerSecond: 500, decompositionLevel: 'container', parentScopeId: 'system-order-payment' },
      parentId: 'system-order-payment',
      lineageFrom: ['logical-order-service', 'logical-payment-service'],
      positions: { applicationRealization: { x: 70, y: 150 } },
      tags: ['api-gateway', 'security-boundary'],
      status: 'draft',
    },
    {
      id: 'deployable-order-api',
      kind: 'DeployableUnit',
      stage: 'applicationRealization',
      label: 'Order API',
      properties: { runtime: 'Node.js', public: true, expectedMonthlyCost: 420, decompositionLevel: 'container', parentScopeId: 'system-order-payment', sourceRepository: 'commerce-platform', implementationPath: 'apps/order-api' },
      parentId: 'system-order-payment',
      lineageFrom: ['logical-order-service'],
      positions: { applicationRealization: { x: 220, y: 170 } },
      tags: ['api'],
      status: 'draft',
    },
    {
      id: 'module-order-outbox',
      kind: 'Module',
      stage: 'applicationRealization',
      label: 'Order Outbox Publisher',
      properties: { pattern: 'Transactional Outbox', deliveryGuarantee: 'at-least-once', idempotency: 'required', decompositionLevel: 'component', parentScopeId: 'deployable-order-api', sourceRepository: 'commerce-platform', implementationPath: 'apps/order-api/src/outbox' },
      parentId: 'deployable-order-api',
      lineageFrom: ['logical-order-service'],
      positions: { applicationRealization: { x: 350, y: 330 } },
      tags: ['event-publisher', 'outbox'],
      status: 'draft',
    },
    {
      id: 'event-order-submitted',
      kind: 'Event',
      stage: 'applicationRealization',
      label: 'Order Submitted Event',
      properties: { schema: 'OrderSubmitted.v1', partitionKey: 'orderId', retentionHours: 72, decompositionLevel: 'component', parentScopeId: 'deployable-order-api', sourceRepository: 'commerce-contracts', implementationPath: 'asyncapi/order-events.yaml' },
      parentId: 'deployable-order-api',
      lineageFrom: ['logical-order-service'],
      positions: { applicationRealization: { x: 560, y: 330 } },
      tags: ['event', 'contract'],
      status: 'draft',
    },
    {
      id: 'deployable-payment-worker',
      kind: 'DeployableUnit',
      stage: 'applicationRealization',
      label: 'Payment Worker',
      properties: { runtime: 'Node.js', expectedMonthlyCost: 280, decompositionLevel: 'container', parentScopeId: 'system-order-payment', sourceRepository: 'commerce-platform', implementationPath: 'apps/payment-worker' },
      parentId: 'system-order-payment',
      lineageFrom: ['logical-payment-service'],
      positions: { applicationRealization: { x: 560, y: 170 } },
      tags: ['worker'],
      status: 'draft',
    },
    {
      id: 'module-payment-adapter',
      kind: 'Module',
      stage: 'applicationRealization',
      label: 'Payment Provider Adapter',
      properties: { timeoutMs: 2500, retryPolicy: 'bounded-exponential', circuitBreaker: true, decompositionLevel: 'component', parentScopeId: 'deployable-payment-worker', sourceRepository: 'commerce-platform', implementationPath: 'apps/payment-worker/src/providers' },
      parentId: 'deployable-payment-worker',
      lineageFrom: ['logical-payment-service'],
      positions: { applicationRealization: { x: 790, y: 170 } },
      tags: ['adapter', 'external-integration'],
      status: 'draft',
    },
    {
      id: 'store-order-state',
      kind: 'DataStore',
      stage: 'applicationRealization',
      label: 'Order State Store',
      properties: { owner: 'Commerce Team', classification: 'confidential', consistency: 'strong', rpoMinutes: 5, rtoMinutes: 30, decompositionLevel: 'container', parentScopeId: 'system-order-payment' },
      parentId: 'system-order-payment',
      lineageFrom: ['logical-order-service'],
      positions: { applicationRealization: { x: 290, y: 500 } },
      tags: ['data', 'system-of-record'],
      status: 'draft',
    },
    {
      id: 'code-order-command-handler',
      kind: 'Module',
      stage: 'applicationRealization',
      label: 'CreateOrderCommandHandler',
      properties: { decompositionLevel: 'code', parentScopeId: 'module-order-outbox', sourceRepository: 'commerce-platform', implementationPath: 'apps/order-api/src/application/CreateOrderCommandHandler.ts' },
      lineageFrom: ['module-order-outbox'],
      parentId: 'module-order-outbox',
      positions: { applicationRealization: { x: 390, y: 455 } },
      tags: ['code','class','application-service'],
      status: 'draft',
    },
    {
      id: 'code-payment-provider-client',
      kind: 'Module',
      stage: 'applicationRealization',
      label: 'PaymentProviderClient',
      properties: { decompositionLevel: 'code', parentScopeId: 'module-payment-adapter', sourceRepository: 'commerce-platform', implementationPath: 'apps/payment-worker/src/providers/PaymentProviderClient.ts' },
      lineageFrom: ['module-payment-adapter'],
      parentId: 'module-payment-adapter',
      positions: { applicationRealization: { x: 820, y: 305 } },
      tags: ['code','class','adapter'],
      status: 'draft',
    },
    {
      id: 'logical-api-management',
      kind: 'LogicalTechnologyCapability',
      stage: 'logicalTechnology',
      label: 'API Management Capability',
      properties: { policies: ['OIDC', 'rate-limiting', 'schema-validation'] },
      lineageFrom: ['realization-api-gateway'],
      positions: { logicalTechnology: { x: 70, y: 120 } },
      tags: ['api', 'security'],
      status: 'draft',
    },
    {
      id: 'logical-container-runtime',
      kind: 'LogicalTechnologyCapability',
      stage: 'logicalTechnology',
      label: 'Container Runtime Capability',
      properties: { autoscaling: true, multiZone: true, workloadIdentity: true },
      lineageFrom: ['deployable-order-api', 'deployable-payment-worker'],
      positions: { logicalTechnology: { x: 300, y: 120 } },
      tags: ['runtime', 'platform'],
      status: 'draft',
    },
    {
      id: 'logical-event-streaming',
      kind: 'LogicalTechnologyCapability',
      stage: 'logicalTechnology',
      label: 'Event Streaming Capability',
      properties: { deliveryGuarantee: 'at-least-once', replay: true, deadLetter: true },
      lineageFrom: ['module-order-outbox', 'event-order-submitted', 'deployable-payment-worker'],
      positions: { logicalTechnology: { x: 540, y: 120 } },
      tags: ['messaging', 'event'],
      status: 'draft',
    },
    {
      id: 'logical-relational-store',
      kind: 'LogicalTechnologyCapability',
      stage: 'logicalTechnology',
      label: 'Relational Data Service',
      properties: { consistency: 'strong' },
      lineageFrom: ['deployable-order-api'],
      positions: { logicalTechnology: { x: 300, y: 220 } },
      tags: ['data'],
      status: 'draft',
    },
    {
      id: 'logical-identity',
      kind: 'LogicalTechnologyCapability',
      stage: 'logicalTechnology',
      label: 'Identity and Access Capability',
      properties: { federation: 'OIDC', workloadIdentity: true, leastPrivilege: true },
      lineageFrom: ['realization-api-gateway', 'deployable-order-api'],
      positions: { logicalTechnology: { x: 70, y: 340 } },
      tags: ['identity', 'security'],
      status: 'draft',
    },
    {
      id: 'logical-observability',
      kind: 'LogicalTechnologyCapability',
      stage: 'logicalTechnology',
      label: 'Observability Capability',
      properties: { signals: ['metrics', 'logs', 'traces'], sloAware: true },
      lineageFrom: ['deployable-order-api', 'deployable-payment-worker', 'module-payment-adapter'],
      positions: { logicalTechnology: { x: 540, y: 340 } },
      tags: ['observability', 'operations'],
      status: 'draft',
    },
    {
      id: 'logical-secrets',
      kind: 'LogicalTechnologyCapability',
      stage: 'logicalTechnology',
      label: 'Secrets and Key Management Capability',
      properties: { rotationDays: 90, envelopeEncryption: true },
      lineageFrom: ['module-payment-adapter', 'store-order-state'],
      positions: { logicalTechnology: { x: 780, y: 340 } },
      tags: ['kms', 'security'],
      status: 'draft',
    },
    {
      id: 'physical-production',
      kind: 'Environment',
      stage: 'physicalTechnology',
      label: 'Production Environment',
      properties: { criticality: 'mission-critical', changePolicy: 'progressive-delivery' },
      lineageFrom: ['logical-container-runtime'],
      positions: { physicalTechnology: { x: 50, y: 40 } },
      tags: ['environment', 'production'],
      status: 'draft',
    },
    {
      id: 'physical-region-primary',
      kind: 'Region',
      stage: 'physicalTechnology',
      label: 'Primary Region',
      properties: { provider: 'portable', jurisdiction: 'approved', zones: 3 },
      lineageFrom: ['logical-container-runtime', 'logical-relational-store'],
      positions: { physicalTechnology: { x: 250, y: 40 } },
      tags: ['region', 'primary'],
      status: 'draft',
    },
    {
      id: 'physical-edge-zone',
      kind: 'NetworkZone',
      stage: 'physicalTechnology',
      label: 'Public Edge Zone',
      properties: { ingress: 'restricted', waf: true, defaultDeny: true },
      lineageFrom: ['logical-api-management'],
      positions: { physicalTechnology: { x: 60, y: 170 } },
      tags: ['network', 'trust-boundary'],
      status: 'draft',
    },
    {
      id: 'physical-app-zone',
      kind: 'NetworkZone',
      stage: 'physicalTechnology',
      label: 'Private Application Zone',
      properties: { egress: 'allow-listed', serviceIdentity: true },
      lineageFrom: ['logical-container-runtime'],
      positions: { physicalTechnology: { x: 330, y: 170 } },
      tags: ['network', 'private'],
      status: 'draft',
    },
    {
      id: 'physical-api-gateway',
      kind: 'TechnologyProduct',
      stage: 'physicalTechnology',
      label: 'Managed API Gateway',
      properties: { vendor: 'portable', product: 'Gateway', highlyAvailable: true, expectedMonthlyCost: 320 },
      lineageFrom: ['logical-api-management'],
      positions: { physicalTechnology: { x: 60, y: 300 } },
      tags: ['api-gateway', 'managed'],
      status: 'draft',
    },
    {
      id: 'physical-container-platform',
      kind: 'TechnologyProduct',
      stage: 'physicalTechnology',
      label: 'Managed Container Platform',
      properties: { vendor: 'portable', product: 'Kubernetes', version: '1.31', zones: 3, autoscaling: true, expectedMonthlyCost: 1250 },
      lineageFrom: ['logical-container-runtime'],
      positions: { physicalTechnology: { x: 330, y: 300 } },
      tags: ['kubernetes', 'runtime'],
      status: 'draft',
    },
    {
      id: 'physical-event-stream',
      kind: 'TechnologyProduct',
      stage: 'physicalTechnology',
      label: 'Managed Event Streaming',
      properties: { vendor: 'portable', product: 'Kafka-compatible', replicas: 3, retentionHours: 72, expectedMonthlyCost: 680 },
      lineageFrom: ['logical-event-streaming'],
      positions: { physicalTechnology: { x: 610, y: 300 } },
      tags: ['event-stream', 'managed'],
      status: 'draft',
    },
    {
      id: 'physical-postgres',
      kind: 'TechnologyProduct',
      stage: 'physicalTechnology',
      label: 'Managed PostgreSQL',
      properties: { vendor: 'generic', product: 'PostgreSQL', version: '15', replicas: 1, availabilityZones: 1, encryptedAtRest: true, expectedMonthlyCost: 500 },
      lineageFrom: ['logical-relational-store'],
      positions: { physicalTechnology: { x: 610, y: 440 } },
      tags: ['database'],
      status: 'draft',
    },
    {
      id: 'physical-identity-provider',
      kind: 'TechnologyProduct',
      stage: 'physicalTechnology',
      label: 'Enterprise Identity Provider',
      properties: { vendor: 'portable', product: 'OIDC Provider', mfa: true, expectedMonthlyCost: 180 },
      lineageFrom: ['logical-identity'],
      positions: { physicalTechnology: { x: 60, y: 470 } },
      tags: ['identity', 'security'],
      status: 'draft',
    },
    {
      id: 'physical-observability-stack',
      kind: 'TechnologyProduct',
      stage: 'physicalTechnology',
      label: 'Telemetry and SLO Platform',
      properties: { vendor: 'portable', product: 'OpenTelemetry Stack', retentionDays: 30, expectedMonthlyCost: 420 },
      lineageFrom: ['logical-observability'],
      positions: { physicalTechnology: { x: 330, y: 470 } },
      tags: ['observability', 'slo'],
      status: 'draft',
    },
    {
      id: 'physical-kms',
      kind: 'TechnologyProduct',
      stage: 'physicalTechnology',
      label: 'Managed Key Service',
      properties: { vendor: 'portable', product: 'KMS', rotationDays: 90, hsmBacked: true, expectedMonthlyCost: 120 },
      lineageFrom: ['logical-secrets'],
      positions: { physicalTechnology: { x: 880, y: 470 } },
      tags: ['kms', 'security'],
      status: 'draft',
    },
  ],
  edges: [
    {
      id: 'edge-customer-system',
      sourceId: 'actor-customer',
      targetId: 'system-order-payment',
      kind: 'communicatesWith',
      stage: 'logicalApplication',
      label: 'Places and tracks orders',
      properties: { protocolStyle: 'digital-channel' },
    },
    {
      id: 'edge-system-domain',
      sourceId: 'system-order-payment',
      targetId: 'logical-order-domain',
      kind: 'contains',
      stage: 'logicalApplication',
      properties: {},
    },
    {
      id: 'edge-customer-order',
      sourceId: 'actor-customer',
      targetId: 'logical-order-service',
      kind: 'communicatesWith',
      stage: 'logicalApplication',
      label: 'Places order',
      properties: { protocolStyle: 'synchronous' },
    },
    {
      id: 'edge-order-payment-event',
      sourceId: 'logical-order-service',
      targetId: 'logical-payment-service',
      kind: 'publishes',
      stage: 'logicalApplication',
      label: 'Order submitted',
      properties: { delivery: 'at-least-once' },
    },
    {
      id: 'edge-order-api-realizes',
      sourceId: 'deployable-order-api',
      targetId: 'logical-order-service',
      kind: 'realizes',
      stage: 'applicationRealization',
      properties: {},
    },
    {
      id: 'edge-payment-worker-realizes',
      sourceId: 'deployable-payment-worker',
      targetId: 'logical-payment-service',
      kind: 'realizes',
      stage: 'applicationRealization',
      properties: {},
    },
    {
      id: 'edge-gateway-order-api',
      sourceId: 'realization-api-gateway',
      targetId: 'deployable-order-api',
      kind: 'communicatesWith',
      stage: 'applicationRealization',
      label: 'Routes authenticated commands',
      properties: { protocol: 'HTTPS', contract: 'OpenAPI' },
    },
    {
      id: 'edge-order-api-outbox',
      sourceId: 'deployable-order-api',
      targetId: 'module-order-outbox',
      kind: 'writes',
      stage: 'applicationRealization',
      label: 'Commits event atomically',
      properties: { transactionBoundary: true },
    },
    {
      id: 'edge-outbox-event',
      sourceId: 'module-order-outbox',
      targetId: 'event-order-submitted',
      kind: 'publishes',
      stage: 'applicationRealization',
      label: 'Publishes OrderSubmitted.v1',
      properties: { delivery: 'at-least-once' },
    },
    {
      id: 'edge-event-payment-worker',
      sourceId: 'event-order-submitted',
      targetId: 'deployable-payment-worker',
      kind: 'subscribes',
      stage: 'applicationRealization',
      label: 'Consumes order event',
      properties: { retry: 'bounded', deadLetter: true },
    },
    {
      id: 'edge-payment-worker-adapter',
      sourceId: 'deployable-payment-worker',
      targetId: 'module-payment-adapter',
      kind: 'communicatesWith',
      stage: 'applicationRealization',
      label: 'Authorises payment',
      properties: { timeoutMs: 2500, circuitBreaker: true },
    },
    {
      id: 'edge-order-api-store',
      sourceId: 'deployable-order-api',
      targetId: 'store-order-state',
      kind: 'writes',
      stage: 'applicationRealization',
      label: 'Persists order state',
      properties: { consistency: 'strong' },
    },
    {
      id: 'edge-outbox-code-contains',
      sourceId: 'module-order-outbox',
      targetId: 'code-order-command-handler',
      kind: 'contains',
      stage: 'applicationRealization',
      properties: {},
    },
    {
      id: 'edge-adapter-code-contains',
      sourceId: 'module-payment-adapter',
      targetId: 'code-payment-provider-client',
      kind: 'contains',
      stage: 'applicationRealization',
      properties: {},
    },
    {
      id: 'edge-api-capability-runtime',
      sourceId: 'logical-api-management',
      targetId: 'logical-container-runtime',
      kind: 'supports',
      stage: 'logicalTechnology',
      label: 'Protects runtime entry points',
      properties: {},
    },
    {
      id: 'edge-runtime-event-stream',
      sourceId: 'logical-container-runtime',
      targetId: 'logical-event-streaming',
      kind: 'dependsOn',
      stage: 'logicalTechnology',
      label: 'Publishes and consumes events',
      properties: {},
    },
    {
      id: 'edge-runtime-data',
      sourceId: 'logical-container-runtime',
      targetId: 'logical-relational-store',
      kind: 'dependsOn',
      stage: 'logicalTechnology',
      label: 'Persists transaction state',
      properties: {},
    },
    {
      id: 'edge-runtime-identity',
      sourceId: 'logical-container-runtime',
      targetId: 'logical-identity',
      kind: 'protectedBy',
      stage: 'logicalTechnology',
      properties: {},
    },
    {
      id: 'edge-runtime-observability',
      sourceId: 'logical-container-runtime',
      targetId: 'logical-observability',
      kind: 'observedBy',
      stage: 'logicalTechnology',
      properties: {},
    },
    {
      id: 'edge-data-secrets',
      sourceId: 'logical-relational-store',
      targetId: 'logical-secrets',
      kind: 'protectedBy',
      stage: 'logicalTechnology',
      properties: {},
    },
    {
      id: 'edge-env-region',
      sourceId: 'physical-region-primary',
      targetId: 'physical-production',
      kind: 'locatedIn',
      stage: 'physicalTechnology',
      properties: {},
    },
    {
      id: 'edge-edge-region',
      sourceId: 'physical-edge-zone',
      targetId: 'physical-region-primary',
      kind: 'locatedIn',
      stage: 'physicalTechnology',
      properties: {},
    },
    {
      id: 'edge-app-region',
      sourceId: 'physical-app-zone',
      targetId: 'physical-region-primary',
      kind: 'locatedIn',
      stage: 'physicalTechnology',
      properties: {},
    },
    {
      id: 'edge-gateway-product-map',
      sourceId: 'physical-api-gateway',
      targetId: 'logical-api-management',
      kind: 'mapsTo',
      stage: 'physicalTechnology',
      properties: {},
    },
    {
      id: 'edge-container-product-map',
      sourceId: 'physical-container-platform',
      targetId: 'logical-container-runtime',
      kind: 'mapsTo',
      stage: 'physicalTechnology',
      properties: {},
    },
    {
      id: 'edge-stream-product-map',
      sourceId: 'physical-event-stream',
      targetId: 'logical-event-streaming',
      kind: 'mapsTo',
      stage: 'physicalTechnology',
      properties: {},
    },
    {
      id: 'edge-identity-product-map',
      sourceId: 'physical-identity-provider',
      targetId: 'logical-identity',
      kind: 'mapsTo',
      stage: 'physicalTechnology',
      properties: {},
    },
    {
      id: 'edge-observability-product-map',
      sourceId: 'physical-observability-stack',
      targetId: 'logical-observability',
      kind: 'mapsTo',
      stage: 'physicalTechnology',
      properties: {},
    },
    {
      id: 'edge-kms-product-map',
      sourceId: 'physical-kms',
      targetId: 'logical-secrets',
      kind: 'mapsTo',
      stage: 'physicalTechnology',
      properties: {},
    },
    {
      id: 'edge-gateway-runtime-product',
      sourceId: 'physical-api-gateway',
      targetId: 'physical-container-platform',
      kind: 'communicatesWith',
      stage: 'physicalTechnology',
      label: 'Routes private service traffic',
      properties: { protocol: 'HTTPS' },
    },
    {
      id: 'edge-runtime-stream-product',
      sourceId: 'physical-container-platform',
      targetId: 'physical-event-stream',
      kind: 'communicatesWith',
      stage: 'physicalTechnology',
      properties: { protocol: 'TLS' },
    },
    {
      id: 'edge-runtime-database-product',
      sourceId: 'physical-container-platform',
      targetId: 'physical-postgres',
      kind: 'communicatesWith',
      stage: 'physicalTechnology',
      properties: { protocol: 'TLS' },
    },
    {
      id: 'edge-runtime-observed-product',
      sourceId: 'physical-container-platform',
      targetId: 'physical-observability-stack',
      kind: 'observedBy',
      stage: 'physicalTechnology',
      properties: {},
    },
    {
      id: 'edge-runtime-protected-product',
      sourceId: 'physical-container-platform',
      targetId: 'physical-identity-provider',
      kind: 'protectedBy',
      stage: 'physicalTechnology',
      properties: {},
    },
    {
      id: 'edge-postgres-maps',
      sourceId: 'physical-postgres',
      targetId: 'logical-relational-store',
      kind: 'mapsTo',
      stage: 'physicalTechnology',
      properties: {},
    },
  ],
  interfaces: [
    {
      id: 'if-customer-order-api', name: 'Customer Order API', stage: 'applicationRealization',
      providerNodeId: 'deployable-order-api', consumerNodeIds: ['actor-customer'], interactionStyle: 'request-response',
      protocol: 'HTTPS', operationOrEvent: 'POST /orders', schemaRef: 'openapi/order-api.yaml', version: 'v1',
      authentication: 'OIDC', authorization: 'scope:orders.write', encryption: 'TLS 1.3', timeoutMs: 2500,
      retryPolicy: 'client bounded retry', idempotency: 'Idempotency-Key required', ordering: 'not-applicable',
      deliveryGuarantee: 'request-response', deadLetterPolicy: 'not-applicable', replayPolicy: 'not-applicable',
      slo: '99.9% availability; p95 < 500ms', dataClassification: 'confidential', owner: 'Commerce Team', lifecycleStatus: 'active',
      evidenceIds: [], contractLocation: 'openapi/order-api.yaml', deprecationPolicy: '12 month notice', createdAt: now, updatedAt: now,
    },
    {
      id: 'if-order-submitted-event', name: 'Order Submitted Event', stage: 'applicationRealization',
      providerNodeId: 'module-order-outbox', consumerNodeIds: ['deployable-payment-worker'], interactionStyle: 'event',
      protocol: 'Kafka-compatible', operationOrEvent: 'commerce.order.submitted.v1', schemaRef: 'asyncapi/order-events.yaml', version: 'v1',
      authentication: 'workload identity', authorization: 'topic ACL', encryption: 'mTLS', retryPolicy: 'bounded exponential',
      idempotency: 'consumer orderId deduplication', ordering: 'per orderId', deliveryGuarantee: 'at-least-once',
      deadLetterPolicy: 'commerce.order.submitted.dlq', replayPolicy: '72 hour replay', slo: '99.95% publish within 2s',
      dataClassification: 'confidential', owner: 'Commerce Team', lifecycleStatus: 'active', evidenceIds: [],
      contractLocation: 'asyncapi/order-events.yaml', deprecationPolicy: 'two supported versions', createdAt: now, updatedAt: now,
    },
    {
      id: 'if-payment-provider', name: 'Payment Provider Contract', stage: 'applicationRealization',
      providerNodeId: 'module-payment-adapter', consumerNodeIds: ['deployable-payment-worker'], interactionStyle: 'request-response',
      protocol: 'HTTPS', operationOrEvent: 'Authorise payment', version: 'v2', authentication: 'mTLS + signed request',
      authorization: 'merchant credential', encryption: 'TLS 1.3', timeoutMs: 2500, retryPolicy: 'bounded exponential with circuit breaker',
      idempotency: 'payment reference', ordering: 'not-applicable', deliveryGuarantee: 'request-response',
      deadLetterPolicy: 'manual exception queue', replayPolicy: 'controlled retry', slo: 'p95 < 2s; degrade within 3s',
      dataClassification: 'restricted', owner: 'Payments Team', lifecycleStatus: 'active', evidenceIds: [],
      contractLocation: 'contracts/payment-provider.md', deprecationPolicy: 'provider notice plus adapter compatibility', createdAt: now, updatedAt: now,
    },
  ],
  decisions: [
    {
      id: 'adr-event-driven-order-progression', title: 'Use event-driven order progression with explicit synchronous boundaries',
      context: 'Order capture must remain available when payment providers are slow or unavailable.',
      decision: 'Use synchronous commands for order capture and asynchronous events for payment progression, with an outbox at the order boundary.',
      drivers: ['availability', 'faultTolerance', 'scalability'],
      consideredOptions: ['Fully synchronous orchestration', 'Event choreography without transactional outbox', 'Event-driven progression with outbox'],
      consequences: ['Orders remain durable before payment processing.', 'Consumers must be idempotent.', 'Operational ownership of replay and dead-letter handling is required.'],
      status: 'accepted', createdAt: now, linkedRecordIds: ['STYLE-EVENT-DRIVEN', 'PAT-OUTBOX'], scopeNodeId: 'logical-order-domain',
    },
    {
      id: 'adr-portable-platform-first', title: 'Keep logical technology provider-neutral before product binding',
      context: 'The organisation requires portability across hybrid hosting environments.',
      decision: 'Model API, runtime, event, data, identity, observability and key-management capabilities independently of cloud products; bind products only in the physical view.',
      drivers: ['modifiability', 'costEfficiency', 'reversibility'],
      consideredOptions: ['Provider-first reference architecture', 'Portable capability model with governed overlays'],
      consequences: ['Provider substitutions remain reviewable.', 'Product mappings require explicit operational evidence.', 'Some provider-specific optimisation is deferred.'],
      status: 'accepted', createdAt: now, linkedRecordIds: ['REF-DIGITAL-TRANSACTION'], scopeNodeId: 'system-order-payment',
    },
  ],
  findings: [
    {
      id: 'finding-single-zone-postgres', ruleId: 'RULE-MULTI-ZONE-CRITICAL-DATA', severity: 'SIGNIFICANT',
      title: 'Critical order database remains single-zone', message: 'The physical database currently records one availability zone and does not meet the intended failure-domain posture.',
      rationale: 'A zone failure could interrupt order recovery and violate availability objectives.', affectedNodeIds: ['physical-postgres'], affectedEdgeIds: [],
      mitigations: ['Configure multi-zone failover.', 'Run backup restore and regional recovery exercises.', 'Attach measured RTO and RPO evidence.'], canOverride: false,
    },
    {
      id: 'finding-development-identity', ruleId: 'RULE-ENTERPRISE-IDENTITY', severity: 'HARD',
      title: 'Development authentication is enabled', message: 'Production acceptance is blocked while development authentication remains enabled and enterprise SSO is not required.',
      rationale: 'Role selection in the UI is not a substitute for authenticated enterprise authorization.', affectedNodeIds: ['physical-identity-provider'], affectedEdgeIds: [],
      mitigations: ['Require enterprise OIDC.', 'Disable development authentication.', 'Attach tenant and reviewer authorization evidence.'], canOverride: false,
    },
  ],
  context: {
    teamSize: 8,
    deliveryHorizonMonths: 6,
    operationalMaturity: 3,
    budgetSensitivity: 3,
    regulatoryExposure: 'high',
    stakeholders: ['Digital Commerce Product Owner', 'Solution Architecture', 'Security Architecture', 'Data Protection', 'Platform Engineering', 'Site Reliability Engineering', 'Payments Operations'],
    inScopeCapabilities: ['Order capture and status', 'Payment authorisation orchestration', 'Transactional event publication', 'Customer-facing order API', 'Operational telemetry and recovery controls'],
    outOfScopeCapabilities: ['Card-data storage', 'Core ledger replacement', 'Merchant settlement', 'Customer identity master-data management'],
    regulatoryJurisdictions: ['Approved operating jurisdictions'],
    existingSystems: ['Core ledger', 'Enterprise identity provider', 'Commerce analytics platform'],
    workloadProfile: 'Bursty digital commerce traffic with a 250 orders/second peak design point',
    availabilityTarget: '99.9% monthly for order capture; no confirmed order loss',
    recoveryObjectives: 'Order state RPO <= 5 minutes and RTO <= 30 minutes; event replay retained for 72 hours',
    teamTopology: 'Commerce product team with platform, security and SRE enablement',
    architectureExperience: 3,
    organizationalChangeReadiness: 3,
    deploymentModel: 'hybrid',
    dataSensitivity: 'restricted',
    sovereigntyRequirements: ['Customer data must remain within approved jurisdictions.'],
    legacyConstraints: ['Core ledger integration remains synchronous during transition.'],
    transitionState: 'incremental-modernization',
    reversibilityPreference: 4,
    supportModel: 'hybrid',
    changeCadence: 'weekly',
    peakLoadVariability: 'bursty',
  },
  branch: {
    id: 'branch-main',
    name: 'Main architecture',
    description: 'Primary governed architecture baseline.',
    baseRevision: 1,
    status: 'active',
    createdAt: now,
  },
  stageApprovals: [
    { id: 'approval-logical', stage: 'logicalApplication', status: 'approved', requestedAt: now, requestedBy: 'user-architect', decidedAt: now, reviewer: 'user-reviewer', assignedReviewerId: 'user-reviewer', comments: ['Logical responsibilities and event-driven direction accepted for reference use.'], snapshotId: 'snapshot-logical-reference' },
    { id: 'approval-realization', stage: 'applicationRealization', status: 'approved', requestedAt: now, requestedBy: 'user-architect', decidedAt: now, reviewer: 'user-reviewer', assignedReviewerId: 'user-reviewer', comments: ['Realization accepted subject to contract-test automation.'], snapshotId: 'snapshot-realization-reference' },
    { id: 'approval-technology', stage: 'logicalTechnology', status: 'approved', requestedAt: now, requestedBy: 'user-architect', decidedAt: now, reviewer: 'user-reviewer', assignedReviewerId: 'user-reviewer', comments: ['Provider-neutral capability model accepted.'], snapshotId: 'snapshot-technology-reference' },
    { id: 'approval-physical', stage: 'physicalTechnology', status: 'changes-requested', requestedAt: now, requestedBy: 'user-architect', reviewer: 'user-reviewer', assignedReviewerId: 'user-reviewer', comments: ['Resolve single-zone database and attach recovery evidence before approval.'] },
  ],
  activeRulePackIds: ['RULEPACK-ENTERPRISE-BASELINE'],
  members: [
    { id: 'user-owner', displayName: 'Amina Okafor', email: 'amina@example.com', role: 'owner', status: 'active', joinedAt: now },
    { id: 'user-architect', displayName: 'Daniel Mensah', email: 'daniel@example.com', role: 'architect', status: 'active', joinedAt: now },
    { id: 'user-reviewer', displayName: 'Lena Adeyemi', email: 'lena@example.com', role: 'reviewer', status: 'active', joinedAt: now },
    { id: 'user-governance', displayName: 'Architecture Review Board', email: 'arb@example.com', role: 'governance', status: 'active', joinedAt: now },
  ],
  reviewAssignments: [
    { id: 'review-physical-reference', stage: 'physicalTechnology', branchId: 'branch-main', assignedTo: 'user-reviewer', assignedBy: 'user-architect', status: 'in-progress', priority: 'high', instructions: 'Review resilience, enterprise identity and production evidence gaps.', createdAt: now },
  ],
  discussionThreads: [],
  notifications: [],
  coArchitectSessions: [],
  aiReviewHistory: [
    { id: 'review-run-reference', createdAt: now, stage: 'validationRealization', source: 'deterministic', summary: 'Reference review identified enterprise identity and single-zone database blockers.', healthScore: 74, proposalCount: 4, findingCount: 2 },
  ],
  collaborationSettings: {
    approvalValidityDays: 90,
    reviewDueDays: 5,
    requireIndependentReviewer: true,
    maxConcurrentEditors: 12,
    presenceTtlSeconds: 45,
    operationRetryLimit: 3,
  },
  securitySettings: {
    requireSso: false,
    allowedIdentityProviderIds: ['idp-reference-development'],
    allowDevelopmentAuth: true,
    sessionMaxAgeMinutes: 480,
    auditRetentionDays: 365,
    encryptionKeyReference: 'env://AIW_DATA_ENCRYPTION_KEY',
  },
  identityProviders: [
    {
      id: 'idp-reference-development',
      tenantId: 'tenant-reference',
      type: 'development',
      name: 'Reference development identity provider',
      issuer: 'aiw://development',
      clientId: 'aiw-reference-client',
      scopes: ['openid', 'profile', 'email'],
      enabled: true,
    },
  ],
  secretReferences: [
    { id: 'secret-ai-provider', provider: 'environment', locator: 'env://OPENAI_API_KEY', purpose: 'Optional AI-assisted architecture audit' },
    { id: 'secret-data-key', provider: 'environment', locator: 'env://AIW_DATA_ENCRYPTION_KEY', purpose: 'Application-level encryption key reference' },
  ],
  observabilitySettings: {
    serviceName: 'aiw-reference-workbench',
    tracesEnabled: true,
    metricsEnabled: true,
    logsEnabled: true,
    samplingRatio: 0.2,
    otlpEndpointReference: 'env://OTEL_EXPORTER_OTLP_ENDPOINT',
    targetAvailabilityPercent: 99.9,
    targetP95LatencyMs: 500,
  },
  repositoryBindings: [
    {
      id: 'repo-reference-local', provider: 'local', repositoryUrl: 'file://architecture-reference', defaultBranch: 'main',
      architecturePath: 'architecture/aiw-project.json', runtimeInventoryPath: 'architecture/runtime-inventory.json',
      policyGatePath: 'architecture/policy-gate.json', status: 'configured',
    },
  ],
  runtimeInventories: [],
  driftReports: [],
  policyGates: [
    {
      id: 'gate-reference', name: 'Reference architecture gate', enabled: true, hardFindingThreshold: 0,
      significantFindingThreshold: 5, advisoryFindingThreshold: 25, maxMissingResources: 0, maxUnmanagedResources: 3,
      requiredApprovedStages: ['logicalApplication', 'applicationRealization', 'logicalTechnology'],
    },
  ],
  inventoryCollectors: [
    { id: 'collector-k8s-reference', name: 'Reference Kubernetes collector', provider: 'kubernetes', enabled: true, schedule: '0 */6 * * *', scope: { cluster: 'reference' }, secretReferenceIds: [], status: 'configured' },
  ],
  collectorRuns: [],
  operationalDriftReports: [],
  driftWaivers: [],
  remediationPlans: [],
  serviceLevelObjectives: [
    { id: 'slo-order-availability', name: 'Order API availability', targetNodeId: 'deployable-order-api', indicator: 'availability', target: 99.9, window: '30d', warningThreshold: 99.95, criticalThreshold: 99.9, enabled: true },
    { id: 'slo-order-latency', name: 'Order API p95 latency', targetNodeId: 'deployable-order-api', indicator: 'latency-p95', target: 500, window: '24h', warningThreshold: 450, criticalThreshold: 500, enabled: true },
  ],
  alertPolicies: [
    { id: 'alert-order-availability', sloId: 'slo-order-availability', name: 'Order availability burn alert', channels: ['email','chat'], severity: 'critical', burnRateThreshold: 2, evaluationWindowMinutes: 60, enabled: true },
  ],
  repositoryPullRequests: [],
  eventBrokerSettings: { adapter: 'memory', topic: 'aiw.architecture.events', maxAttempts: 5, retryDelayMs: 1000, deadLetterEnabled: true },
  deploymentProfiles: [
    { id: 'deploy-profile-reference', name: 'Reference production profile', environment: 'production', replicas: 2, cpuRequest: '500m', memoryRequest: '512Mi', publicIngress: true, autoscaling: true, minReplicas: 2, maxReplicas: 8 },
  ],
  portfolio: {
    portfolioId: 'portfolio-digital-channels', businessUnit: 'Digital Commerce', owner: 'Amina Okafor',
    criticality: 'mission-critical', lifecycle: 'invest', annualChangeBudget: 1200000, currency: 'USD',
  },
  projectDependencies: [
    { id: 'dependency-order-identity', sourceProjectId: 'project-order-to-payment', targetProjectId: 'project-customer-identity', kind: 'api', criticality: 'high', interfaceName: 'Customer Identity API', dataClassification: 'confidential', status: 'active' },
    { id: 'dependency-order-analytics', sourceProjectId: 'project-order-to-payment', targetProjectId: 'project-commerce-analytics', kind: 'event', criticality: 'medium', interfaceName: 'Order Events', dataClassification: 'internal', status: 'active' },
  ],
  technologyStandardExceptions: [],
  technicalDebtItems: [
    { id: 'debt-single-zone-db', title: 'Database remains single-zone', category: 'operations', severity: 'SIGNIFICANT', description: 'The current physical database topology does not yet meet the target failure-domain requirement.', linkedNodeIds: ['physical-postgres'], estimatedEffortDays: 8, annualCostImpact: 18000, status: 'planned' },
    { id: 'debt-manual-contract-tests', title: 'Integration contracts are validated manually', category: 'delivery', severity: 'ADVISORY', description: 'Consumer-driven contract testing has not been automated.', linkedNodeIds: ['deployable-order-api'], estimatedEffortDays: 5, annualCostImpact: 9000, status: 'open' },
  ],
  buildingBlockUsages: [
    { id: 'usage-secure-api', buildingBlockId: 'ABB-SECURE-API-SERVICE', version: '1.0.0', scopeNodeId: 'deployable-order-api', status: 'adopted' },
  ],
  referenceArchitectureAssignments: [
    { id: 'assignment-digital-transaction', referenceArchitectureId: 'REF-DIGITAL-TRANSACTION-PLATFORM', version: '1.0.0', status: 'applicable' },
  ],
  revision: 1,
  updatedAt: now,
};
