import { AIW_RELEASE } from '@aiw/domain';
import type { FastifyInstance, FastifyRequest } from 'fastify';
import { FileDurableJobQueue, InMemoryJobQueue, PostgresJobQueue, type JobQueueAdapter, type ProductionJobStatus } from '@aiw/integrations';
import { ProductionOperationsRepository } from '../productionOperations.js';
import { buildProductionBrainAcceptance } from '../productionBrainAcceptance.js';
import { hasPermission } from '@aiw/engine';

interface Principal { tenantId: string; subject: string; roles?: string[]; authMode?: string }
export interface ProductionMindFactoryDeps { principalFor: (request: FastifyRequest) => Principal; queue?: JobQueueAdapter; operations?: ProductionOperationsRepository }
let sharedQueue: Promise<JobQueueAdapter> | undefined;
async function queueFromEnvironment(): Promise<JobQueueAdapter> {
  if (sharedQueue) return sharedQueue;
  sharedQueue = (async () => {
    const adapter = process.env.AIW_JOB_QUEUE_ADAPTER || (process.env.NODE_ENV === 'production' ? 'postgres' : 'file');
    if (adapter === 'memory') return new InMemoryJobQueue();
    if (adapter === 'file') return new FileDurableJobQueue();
    if (adapter === 'postgres') { if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL_REQUIRED_FOR_PRODUCTION_JOB_QUEUE'); const { Pool } = await import('pg'); return new PostgresJobQueue(new Pool({ connectionString: process.env.DATABASE_URL })); }
    throw new Error(`UNSUPPORTED_JOB_QUEUE_ADAPTER:${adapter}`);
  })();
  return sharedQueue;
}
function allowed(principal: Principal): boolean { return (principal.roles ?? []).some((role) => ['platform-admin','knowledge-admin','knowledge-curator','architecture-reviewer','compliance-reviewer','repository-admin'].includes(role)) || process.env.NODE_ENV !== 'production'; }
function guard(principal: Principal, permission: string): boolean { return hasPermission(principal, permission).ok || process.env.NODE_ENV !== 'production'; }
function actor(principal: Principal): string { return principal.subject || 'unknown'; }

export async function productionMindFactoryRoutes(app: FastifyInstance, deps: ProductionMindFactoryDeps): Promise<void> {
  const operations = deps.operations ?? new ProductionOperationsRepository();
  const getQueue = () => deps.queue ? Promise.resolve(deps.queue) : queueFromEnvironment();
  app.get('/api/admin/production-mind-factory/acceptance', async (request, reply) => { const principal = deps.principalFor(request); if (!allowed(principal)) return reply.code(403).send({ error: 'PERMISSION_DENIED' }); return buildProductionBrainAcceptance({ queue: await getQueue(), operations, active: true }); });
  app.get('/api/admin/production-mind-factory/status', async (request, reply) => { const principal = deps.principalFor(request); if (!allowed(principal)) return reply.code(403).send({ error: 'PERMISSION_DENIED' }); const queue = await getQueue(); return { release: '0.10.0-rc.10.58.0', queue: await queue.health(), operations: await operations.health(), deterministicDesignFallback: true, productionActivationRule: 'mandatory blockers must be zero' }; });
  app.post('/api/admin/production-mind-factory/jobs', async (request, reply) => { const principal = deps.principalFor(request); if (!guard(principal, 'mind-factory.worker')) return reply.code(403).send({ error: 'PERMISSION_DENIED' }); const body = (request.body ?? {}) as { queue?: string; payload?: Record<string, unknown>; maxAttempts?: number; correlationId?: string }; if (!body.queue) return reply.code(400).send({ error: 'QUEUE_REQUIRED' }); const queue = await getQueue(); const job = await queue.enqueue({ tenantId: principal.tenantId, queue: body.queue, payload: body.payload ?? {}, ...(body.maxAttempts === undefined ? {} : { maxAttempts: body.maxAttempts }), ...(body.correlationId ? { correlationId: body.correlationId } : {}) }); return reply.code(202).send({ job, execution: 'asynchronous-durable' }); });
  app.get('/api/admin/production-mind-factory/jobs', async (request, reply) => { const principal = deps.principalFor(request); if (!allowed(principal)) return reply.code(403).send({ error: 'PERMISSION_DENIED' }); const query = request.query as { status?: string }; const statuses = query.status?.split(',').filter(Boolean) as ProductionJobStatus[] | undefined; return { jobs: await (await getQueue()).list(principal.tenantId, statuses) }; });
  app.post('/api/admin/production-mind-factory/jobs/:jobId/cancel', async (request, reply) => { const principal = deps.principalFor(request); if (!guard(principal, 'mind-factory.worker')) return reply.code(403).send({ error: 'PERMISSION_DENIED' }); try { return { job: await (await getQueue()).cancel(principal.tenantId, (request.params as { jobId: string }).jobId) }; } catch (error) { return reply.code(409).send({ error: error instanceof Error ? error.message : String(error) }); } });

  app.post('/api/admin/evidence', async (request, reply) => { const principal = deps.principalFor(request); if (!guard(principal, 'evidence.write')) return reply.code(403).send({ error: 'PERMISSION_DENIED' }); const body = (request.body ?? {}) as { projectId?: string; evidenceType?: string; title?: string; contentBase64?: string; contentText?: string; mediaType?: string; expiresAt?: string; metadata?: Record<string, unknown> }; if (!body.evidenceType || !body.title) return reply.code(400).send({ error: 'EVIDENCE_TYPE_AND_TITLE_REQUIRED' }); try { const evidence = await operations.putEvidence({ tenantId: principal.tenantId, ...(body.projectId ? { projectId: body.projectId } : {}), evidenceType: body.evidenceType, title: body.title, ...(body.contentBase64 ? { contentBase64: body.contentBase64 } : {}), ...(body.contentText === undefined ? {} : { contentText: body.contentText }), ...(body.mediaType ? { mediaType: body.mediaType } : {}), ...(body.expiresAt ? { expiresAt: body.expiresAt } : {}), metadata: { ...body.metadata, uploadedBy: actor(principal) } }); return reply.code(201).send({ evidence }); } catch (error) { return reply.code(400).send({ error: error instanceof Error ? error.message : String(error) }); } });
  app.get('/api/admin/evidence', async (request, reply) => { const principal = deps.principalFor(request); if (!allowed(principal)) return reply.code(403).send({ error: 'PERMISSION_DENIED' }); return { evidence: await operations.listEvidence(principal.tenantId, (request.query as { projectId?: string }).projectId) }; });
  app.get('/api/admin/evidence/:evidenceId/content', async (request, reply) => { const principal = deps.principalFor(request); if (!allowed(principal)) return reply.code(403).send({ error: 'PERMISSION_DENIED' }); const found = await operations.getEvidence(principal.tenantId, (request.params as { evidenceId: string }).evidenceId); if (!found) return reply.code(404).send({ error: 'EVIDENCE_NOT_FOUND' }); reply.header('content-type', found.record.mediaType); reply.header('x-aiw-evidence-sha256', found.record.sha256); return Buffer.from(found.content); });
  app.delete('/api/admin/evidence/:evidenceId', async (request, reply) => { const principal = deps.principalFor(request); if (!guard(principal, 'evidence.write')) return reply.code(403).send({ error: 'PERMISSION_DENIED' }); try { return { evidence: await operations.deleteEvidence(principal.tenantId, (request.params as { evidenceId: string }).evidenceId) }; } catch (error) { return reply.code(404).send({ error: error instanceof Error ? error.message : String(error) }); } });

  app.post('/api/admin/environment-promotions', async (request, reply) => { const principal = deps.principalFor(request); if (!guard(principal, 'environment.promote')) return reply.code(403).send({ error: 'PERMISSION_DENIED' }); const body = (request.body ?? {}) as { sourceEnvironment?: string; targetEnvironment?: string; releaseVersion?: string; pinnedKnowledgeReleaseId?: string; mandatoryBlockers?: string[]; acceptanceReport?: Record<string, unknown> }; if (!body.sourceEnvironment || !body.targetEnvironment || !body.pinnedKnowledgeReleaseId) return reply.code(400).send({ error: 'PROMOTION_CONTEXT_INCOMPLETE' }); const promotion = await operations.requestPromotion({ tenantId: principal.tenantId, sourceEnvironment: body.sourceEnvironment, targetEnvironment: body.targetEnvironment, releaseVersion: body.releaseVersion ?? AIW_RELEASE.version, pinnedKnowledgeReleaseId: body.pinnedKnowledgeReleaseId, requestedBy: actor(principal), ...(body.mandatoryBlockers ? { mandatoryBlockers: body.mandatoryBlockers } : {}), ...(body.acceptanceReport ? { acceptanceReport: body.acceptanceReport } : {}) }); return reply.code(promotion.status === 'blocked' ? 409 : 201).send({ promotion }); });
  app.get('/api/admin/environment-promotions', async (request, reply) => { const principal = deps.principalFor(request); if (!allowed(principal)) return reply.code(403).send({ error: 'PERMISSION_DENIED' }); return { promotions: await operations.listPromotions(principal.tenantId) }; });
  app.post('/api/admin/environment-promotions/:promotionId/promote', async (request, reply) => { const principal = deps.principalFor(request); if (!guard(principal, 'environment.promote')) return reply.code(403).send({ error: 'PERMISSION_DENIED' }); try { return { promotion: await operations.promote(principal.tenantId, (request.params as { promotionId: string }).promotionId) }; } catch (error) { return reply.code(409).send({ error: error instanceof Error ? error.message : String(error) }); } });
}
