export type ArchitectureSourceType =
  | 'standard'
  | 'open-standard'
  | 'specification'
  | 'official-method'
  | 'research-method'
  | 'vendor-guidance'
  | 'internal-standard';

export interface TrustedArchitectureSource {
  id: string;
  title: string;
  publisher: string;
  sourceType: ArchitectureSourceType;
  authorityLevel: 1 | 2 | 3 | 4 | 5;
  url: string;
  scopeTags: string[];
  status: 'approved' | 'candidate' | 'deprecated';
  reviewedAt: string;
  refreshCadenceDays: number;
  ingestionMode: 'manual-reviewed' | 'allowlisted-refresh';
}

export interface AntiPatternRecord {
  id: string;
  name: string;
  category: string;
  description: string;
  signals: string[];
  risks: string[];
  mitigations: string[];
  evidenceSourceIds: string[];
}

export interface KnowledgeClaim {
  id: string;
  recordId: string;
  claimType: 'applicability' | 'tradeoff' | 'prerequisite' | 'obligation' | 'risk' | 'anti-pattern-signal';
  statement: string;
  sourceIds: string[];
  confidence: number;
  contextTags: string[];
  reviewedAt: string;
  reviewStatus: 'verified' | 'provisional' | 'disputed';
}

export const trustedArchitectureSources: TrustedArchitectureSource[] = [
  { id: 'SRC-C4', title: 'C4 model for visualising software architecture', publisher: 'C4 Model / Simon Brown', sourceType: 'official-method', authorityLevel: 5, url: 'https://c4model.com/', scopeTags: ['viewpoints','software-system','container','component','deployment'], status: 'approved', reviewedAt: '2026-07-02', refreshCadenceDays: 180, ingestionMode: 'manual-reviewed' },
  { id: 'SRC-ISO-42010', title: 'ISO/IEC/IEEE 42010:2022 Architecture Description', publisher: 'ISO/IEC/IEEE', sourceType: 'standard', authorityLevel: 5, url: 'https://www.iso.org/standard/74393.html', scopeTags: ['architecture-description','stakeholder','concern','viewpoint','model-kind'], status: 'approved', reviewedAt: '2026-07-02', refreshCadenceDays: 365, ingestionMode: 'manual-reviewed' },
  { id: 'SRC-SEI-QAW', title: 'SEI Quality Attribute Workshop', publisher: 'Carnegie Mellon Software Engineering Institute', sourceType: 'research-method', authorityLevel: 5, url: 'https://www.sei.cmu.edu/library/the-sei-quality-attribute-workshop/', scopeTags: ['quality-attributes','scenarios','stakeholders','design-drivers'], status: 'approved', reviewedAt: '2026-07-02', refreshCadenceDays: 365, ingestionMode: 'manual-reviewed' },
  { id: 'SRC-AWS-WAF', title: 'AWS Well-Architected Framework', publisher: 'Amazon Web Services', sourceType: 'vendor-guidance', authorityLevel: 4, url: 'https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html', scopeTags: ['reliability','security','performance','cost','operations','sustainability','cloud'], status: 'approved', reviewedAt: '2026-07-02', refreshCadenceDays: 90, ingestionMode: 'allowlisted-refresh' },
  { id: 'SRC-AZURE-AAC', title: 'Azure Architecture Center and Cloud Design Patterns', publisher: 'Microsoft', sourceType: 'vendor-guidance', authorityLevel: 4, url: 'https://learn.microsoft.com/en-us/azure/architecture/', scopeTags: ['patterns','anti-patterns','reliability','integration','data','cloud'], status: 'approved', reviewedAt: '2026-07-02', refreshCadenceDays: 90, ingestionMode: 'allowlisted-refresh' },
  { id: 'SRC-GCP-WAF', title: 'Google Cloud Well-Architected Framework', publisher: 'Google Cloud', sourceType: 'vendor-guidance', authorityLevel: 4, url: 'https://docs.cloud.google.com/architecture/framework', scopeTags: ['reliability','security','performance','cost','operations','sustainability','cloud'], status: 'approved', reviewedAt: '2026-07-02', refreshCadenceDays: 90, ingestionMode: 'allowlisted-refresh' },
  { id: 'SRC-OWASP-ASVS', title: 'OWASP Application Security Verification Standard', publisher: 'OWASP Foundation', sourceType: 'open-standard', authorityLevel: 5, url: 'https://owasp.org/www-project-application-security-verification-standard/', scopeTags: ['security','authentication','authorization','data-protection','application-security'], status: 'approved', reviewedAt: '2026-07-02', refreshCadenceDays: 180, ingestionMode: 'allowlisted-refresh' },
  { id: 'SRC-NIST-SSDF', title: 'NIST Secure Software Development Framework SP 800-218', publisher: 'National Institute of Standards and Technology', sourceType: 'standard', authorityLevel: 5, url: 'https://csrc.nist.gov/pubs/sp/800/218/final', scopeTags: ['secure-development','governance','supply-chain','verification'], status: 'approved', reviewedAt: '2026-07-02', refreshCadenceDays: 180, ingestionMode: 'manual-reviewed' },
  { id: 'SRC-OPENAPI', title: 'OpenAPI Specification', publisher: 'OpenAPI Initiative / Linux Foundation', sourceType: 'specification', authorityLevel: 5, url: 'https://spec.openapis.org/oas/', scopeTags: ['api','http','interface-contract','versioning'], status: 'approved', reviewedAt: '2026-07-02', refreshCadenceDays: 90, ingestionMode: 'allowlisted-refresh' },
  { id: 'SRC-OTEL', title: 'OpenTelemetry Specification', publisher: 'Cloud Native Computing Foundation', sourceType: 'specification', authorityLevel: 5, url: 'https://opentelemetry.io/docs/specs/', scopeTags: ['observability','tracing','metrics','logs','telemetry'], status: 'approved', reviewedAt: '2026-07-02', refreshCadenceDays: 90, ingestionMode: 'allowlisted-refresh' },

  { id: 'SRC-ASYNCAPI', title: 'AsyncAPI Specification', publisher: 'AsyncAPI Initiative', sourceType: 'specification', authorityLevel: 5, url: 'https://www.asyncapi.com/docs/reference/specification/latest', scopeTags: ['event','message','channel','async-interface','contract'], status: 'approved', reviewedAt: '2026-07-11', refreshCadenceDays: 90, ingestionMode: 'allowlisted-refresh' },
  { id: 'SRC-CALM', title: 'FINOS Common Architecture Language Model', publisher: 'FINOS', sourceType: 'open-standard', authorityLevel: 5, url: 'https://github.com/finos/architecture-as-code', scopeTags: ['architecture-as-code','interoperability','controls','patterns','validation'], status: 'approved', reviewedAt: '2026-07-11', refreshCadenceDays: 30, ingestionMode: 'allowlisted-refresh' },
  { id: 'SRC-CNCF-TAG-SECURITY', title: 'CNCF TAG Security guidance', publisher: 'Cloud Native Computing Foundation', sourceType: 'official-method', authorityLevel: 5, url: 'https://github.com/cncf/tag-security', scopeTags: ['cloud-native','security','supply-chain','controls','threat-model'], status: 'approved', reviewedAt: '2026-07-11', refreshCadenceDays: 90, ingestionMode: 'allowlisted-refresh' },
  { id: 'SRC-CAMBRIDGE-SDD', title: 'Cambridge Software Architecture and SDD Reasoning Grammar', publisher: 'Cambridge course materials / governed internal adaptation', sourceType: 'internal-standard', authorityLevel: 4, url: 'internal://cambridge-sdd-reasoning-grammar', scopeTags: ['stakeholders','quality-scenarios','viewpoints','components','interfaces','trade-offs','sdd','traceability'], status: 'approved', reviewedAt: '2026-07-11', refreshCadenceDays: 180, ingestionMode: 'manual-reviewed' },
  { id: 'SRC-INTERNAL-PRINCIPLES', title: 'AIW Architecture Principles Baseline', publisher: 'Architecture Knowledge Council', sourceType: 'internal-standard', authorityLevel: 4, url: 'internal://architecture-principles', scopeTags: ['traceability','governance','hybrid-architecture','human-approval'], status: 'approved', reviewedAt: '2026-07-02', refreshCadenceDays: 180, ingestionMode: 'manual-reviewed' },
  // Governed repository dossiers resolved by the rc.10.59 knowledge-to-tooling pipeline.
  { id: "GH-FINOS-CALM", title: "FINOS Common Architecture Language Model (CALM)", publisher: "FINOS", sourceType: "open-standard", authorityLevel: 5, url: "https://github.com/finos/architecture-as-code", scopeTags: ["modeling-language", "pattern-library", "architecture-conformance", "claim-evidence", "pattern-extraction", "component-taxonomy", "topology-template", "interoperability-adapter", "architecture-test-generation"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 14, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-MICROSOFT-ARCH-CENTER", title: "Microsoft Azure Architecture Center", publisher: "Microsoft", sourceType: "vendor-guidance", authorityLevel: 5, url: "https://github.com/MicrosoftDocs/architecture-center", scopeTags: ["pattern-library", "anti-pattern-library", "reference-architecture", "component-library", "claim-evidence", "pattern-extraction", "anti-pattern-extraction", "component-taxonomy", "reference-example", "quality-attribute-calibration"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 14, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-AWS-SERVERLESS-PATTERNS", title: "AWS Serverless Patterns Collection", publisher: "AWS Samples", sourceType: "vendor-guidance", authorityLevel: 5, url: "https://github.com/aws-samples/serverless-patterns", scopeTags: ["pattern-library", "component-library", "implementation-example", "pattern-extraction", "component-taxonomy", "topology-template", "reference-example"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 14, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-AWS-SOLUTIONS-CONSTRUCTS", title: "AWS Solutions Constructs", publisher: "AWS Labs", sourceType: "vendor-guidance", authorityLevel: 5, url: "https://github.com/awslabs/aws-solutions-constructs", scopeTags: ["component-library", "pattern-library", "implementation-example", "component-taxonomy", "pattern-extraction", "topology-template", "reference-example"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 30, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-AZURE-RESOURCE-MODULES", title: "Azure Common Resource Modules / Verified Modules", publisher: "Azure", sourceType: "vendor-guidance", authorityLevel: 5, url: "https://github.com/Azure/ResourceModules", scopeTags: ["component-library", "reference-architecture", "implementation-example", "component-taxonomy", "topology-template", "reference-example", "interoperability-adapter"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 30, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-GCP-CLOUD-FOUNDATION-FABRIC", title: "Google Cloud Foundation Fabric", publisher: "Google Cloud Platform", sourceType: "vendor-guidance", authorityLevel: 5, url: "https://github.com/GoogleCloudPlatform/cloud-foundation-fabric", scopeTags: ["component-library", "reference-architecture", "implementation-example", "component-taxonomy", "topology-template", "reference-example", "interoperability-adapter"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 30, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-DDD-CREW", title: "Domain-Driven Design Crew Methods", publisher: "DDD Crew", sourceType: "official-method", authorityLevel: 4, url: "https://github.com/ddd-crew/ddd-starter-modelling-process", scopeTags: ["architecture-method", "pattern-library", "documentation-framework", "claim-evidence", "pattern-extraction", "topology-template", "reference-example"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 60, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-APACHE-CAMEL", title: "Apache Camel Enterprise Integration Patterns", publisher: "Apache Software Foundation", sourceType: "official-method", authorityLevel: 5, url: "https://github.com/apache/camel", scopeTags: ["pattern-library", "component-library", "implementation-example", "pattern-extraction", "component-taxonomy", "topology-template", "reference-example"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 30, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-ASYNCAPI", title: "AsyncAPI Specification and Tooling", publisher: "AsyncAPI Initiative", sourceType: "open-standard", authorityLevel: 5, url: "https://github.com/asyncapi/spec", scopeTags: ["contract-specification", "modeling-language", "component-library", "claim-evidence", "component-taxonomy", "interoperability-adapter", "architecture-test-generation", "reference-example"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 30, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-OAM-SPEC", title: "Open Application Model", publisher: "OAM Dev", sourceType: "open-standard", authorityLevel: 4, url: "https://github.com/oam-dev/spec", scopeTags: ["modeling-language", "component-library", "architecture-method", "component-taxonomy", "interoperability-adapter", "topology-template", "claim-evidence"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 90, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-K8S-PATTERNS", title: "Kubernetes Patterns Examples", publisher: "Kubernetes Patterns", sourceType: "official-method", authorityLevel: 4, url: "https://github.com/k8spatterns/examples", scopeTags: ["pattern-library", "implementation-example", "component-library", "pattern-extraction", "topology-template", "component-taxonomy", "reference-example"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 90, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-SERVICE-MESH-PATTERNS", title: "Service Mesh Patterns", publisher: "Service Mesh Patterns / Layer5", sourceType: "official-method", authorityLevel: 4, url: "https://github.com/service-mesh-patterns/service-mesh-patterns", scopeTags: ["pattern-library", "component-library", "implementation-example", "pattern-extraction", "topology-template", "component-taxonomy", "reference-example"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 60, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-LIKEC4", title: "LikeC4", publisher: "LikeC4", sourceType: "open-standard", authorityLevel: 4, url: "https://github.com/likec4/likec4", scopeTags: ["modeling-language", "documentation-framework", "interoperability-adapter", "reference-example", "component-taxonomy"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 30, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-STRUCTURIZR-JAVA", title: "Structurizr DSL and Java Model", publisher: "Structurizr", sourceType: "open-standard", authorityLevel: 5, url: "https://github.com/structurizr/java", scopeTags: ["modeling-language", "documentation-framework", "interoperability-adapter", "reference-example", "architecture-test-generation"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 30, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-C4-PLANTUML", title: "C4-PlantUML", publisher: "PlantUML Standard Library", sourceType: "open-standard", authorityLevel: 4, url: "https://github.com/plantuml-stdlib/C4-PlantUML", scopeTags: ["modeling-language", "documentation-framework", "interoperability-adapter", "reference-example"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 90, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-ARC42", title: "arc42 Architecture Documentation Template", publisher: "arc42", sourceType: "official-method", authorityLevel: 4, url: "https://github.com/arc42/arc42-template", scopeTags: ["documentation-framework", "architecture-method", "claim-evidence", "interoperability-adapter", "reference-example"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 90, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-ARCHUNIT", title: "ArchUnit", publisher: "TNG Technology Consulting", sourceType: "official-method", authorityLevel: 5, url: "https://github.com/TNG/ArchUnit", scopeTags: ["architecture-conformance", "implementation-example", "architecture-test-generation", "reference-example", "interoperability-adapter"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 60, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-JQASSISTANT", title: "jQAssistant", publisher: "jQAssistant", sourceType: "official-method", authorityLevel: 5, url: "https://github.com/jQAssistant/jqassistant", scopeTags: ["architecture-conformance", "component-library", "implementation-example", "architecture-test-generation", "interoperability-adapter", "component-taxonomy", "reference-example"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 60, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-BACKSTAGE", title: "Backstage Software Catalog", publisher: "Backstage / CNCF", sourceType: "official-method", authorityLevel: 5, url: "https://github.com/backstage/backstage", scopeTags: ["component-library", "reference-architecture", "implementation-example", "component-taxonomy", "interoperability-adapter", "reference-example"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 30, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-FINOS-AI-RA", title: "FINOS AI Reference Architecture Library", publisher: "FINOS", sourceType: "official-method", authorityLevel: 5, url: "https://github.com/finos/ai-reference-architecture-library", scopeTags: ["reference-architecture", "pattern-library", "component-library", "claim-evidence", "topology-template", "component-taxonomy", "reference-example"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 30, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-SAP-ARCH-CENTER", title: "SAP Architecture Center", publisher: "SAP", sourceType: "official-method", authorityLevel: 5, url: "https://github.com/SAP/architecture-center", scopeTags: ["reference-architecture", "component-library", "pattern-library", "reference-example", "component-taxonomy", "topology-template", "claim-evidence"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 30, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-CNCF-TAG-SECURITY", title: "CNCF TAG Security Reference Architectures", publisher: "CNCF", sourceType: "official-method", authorityLevel: 5, url: "https://github.com/cncf/tag-security", scopeTags: ["reference-architecture", "quality-model", "pattern-library", "claim-evidence", "pattern-extraction", "quality-attribute-calibration", "topology-template"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 60, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-IBM-CLOUD-NATIVE-PATTERNS", title: "IBM Cloud-Native Patterns", publisher: "IBM", sourceType: "official-method", authorityLevel: 4, url: "https://github.com/IBM/cloud-native-patterns", scopeTags: ["pattern-library", "implementation-example", "pattern-extraction", "topology-template", "reference-example"], status: "candidate", reviewedAt: '2026-07-11', refreshCadenceDays: 180, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-CNA-QUALITY-MODEL", title: "Cloud-Native Architecture Quality Model", publisher: "Research project", sourceType: "official-method", authorityLevel: 4, url: "https://github.com/r0light/cna-quality-model", scopeTags: ["quality-model", "architecture-method", "quality-attribute-calibration", "claim-evidence", "anti-pattern-extraction"], status: "candidate", reviewedAt: '2026-07-11', refreshCadenceDays: 180, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-OTEL-DEMO", title: "OpenTelemetry Astronomy Shop Demo", publisher: "OpenTelemetry", sourceType: "official-method", authorityLevel: 5, url: "https://github.com/open-telemetry/opentelemetry-demo", scopeTags: ["reference-architecture", "implementation-example", "component-library", "reference-example", "component-taxonomy", "topology-template", "architecture-test-generation"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 30, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-GCP-MICROSERVICES-DEMO", title: "Google Cloud Microservices Demo", publisher: "Google Cloud Platform", sourceType: "vendor-guidance", authorityLevel: 5, url: "https://github.com/GoogleCloudPlatform/microservices-demo", scopeTags: ["reference-architecture", "implementation-example", "component-library", "reference-example", "component-taxonomy", "topology-template", "architecture-test-generation"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 60, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-GCP-SOFTWARE-DELIVERY-BLUEPRINT", title: "Google Cloud Software Delivery Blueprint", publisher: "Google Cloud Platform", sourceType: "vendor-guidance", authorityLevel: 5, url: "https://github.com/GoogleCloudPlatform/software-delivery-blueprint", scopeTags: ["reference-architecture", "component-library", "implementation-example", "reference-example", "component-taxonomy", "topology-template", "claim-evidence"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 60, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-AWS-SAAS-EKS", title: "AWS SaaS Factory EKS Reference Architecture", publisher: "AWS Samples", sourceType: "vendor-guidance", authorityLevel: 5, url: "https://github.com/aws-samples/aws-saas-factory-eks-reference-architecture", scopeTags: ["reference-architecture", "implementation-example", "component-library", "reference-example", "topology-template", "component-taxonomy", "claim-evidence"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 90, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-MICROSOFT-AGENT-SKILLS", title: "Microsoft Agent Skills — Azure Architecture", publisher: "Microsoft Docs", sourceType: "vendor-guidance", authorityLevel: 4, url: "https://github.com/MicrosoftDocs/agent-skills", scopeTags: ["architecture-method", "pattern-library", "discovery-index", "reference-example", "discovery-only"], status: "candidate", reviewedAt: '2026-07-11', refreshCadenceDays: 30, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-JAVA-DESIGN-PATTERNS", title: "Java Design Patterns", publisher: "Open-source community", sourceType: "official-method", authorityLevel: 3, url: "https://github.com/iluwatar/java-design-patterns", scopeTags: ["pattern-library", "implementation-example", "pattern-extraction", "reference-example", "component-taxonomy"], status: "candidate", reviewedAt: '2026-07-11', refreshCadenceDays: 90, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-AWESOME-DESIGN-PATTERNS", title: "Awesome Software and Architectural Design Patterns", publisher: "Community curator", sourceType: "official-method", authorityLevel: 3, url: "https://github.com/DovAmir/awesome-design-patterns", scopeTags: ["discovery-index", "pattern-library", "discovery-only"], status: "candidate", reviewedAt: '2026-07-11', refreshCadenceDays: 180, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-AWESOME-SOFTWARE-ARCH", title: "Awesome Software Architecture", publisher: "Community curator", sourceType: "official-method", authorityLevel: 3, url: "https://github.com/mehdihadeli/awesome-software-architecture", scopeTags: ["discovery-index", "pattern-library", "discovery-only"], status: "candidate", reviewedAt: '2026-07-11', refreshCadenceDays: 90, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-AWESOME-ANTIPATTERN", title: "Awesome Anti-Pattern Index", publisher: "Community curator", sourceType: "official-method", authorityLevel: 3, url: "https://github.com/fauzisho/awesome-antipattern", scopeTags: ["discovery-index", "anti-pattern-library", "discovery-only"], status: "candidate", reviewedAt: '2026-07-11', refreshCadenceDays: 180, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-SYSTEM-DESIGN-PRIMER", title: "System Design Primer", publisher: "Community", sourceType: "official-method", authorityLevel: 3, url: "https://github.com/donnemartin/system-design-primer", scopeTags: ["discovery-index", "implementation-example", "discovery-only", "reference-example"], status: "candidate", reviewedAt: '2026-07-11', refreshCadenceDays: 180, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-JMOLECULES", title: "jMolecules Architectural Abstractions", publisher: "xMolecules", sourceType: "official-method", authorityLevel: 4, url: "https://github.com/xmolecules/jmolecules", scopeTags: ["component-library", "pattern-library", "architecture-conformance", "implementation-example", "component-taxonomy", "pattern-extraction", "architecture-test-generation", "reference-example", "interoperability-adapter"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 30, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-SPRING-MODULITH", title: "Spring Modulith", publisher: "Spring Projects", sourceType: "official-method", authorityLevel: 4, url: "https://github.com/spring-projects/spring-modulith", scopeTags: ["architecture-conformance", "component-library", "documentation-framework", "implementation-example", "component-taxonomy", "architecture-test-generation", "reference-example", "interoperability-adapter", "claim-evidence"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 30, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-CONTEXT-MAPPER-DSL", title: "Context Mapper DSL", publisher: "Context Mapper", sourceType: "open-standard", authorityLevel: 4, url: "https://github.com/ContextMapper/context-mapper-dsl", scopeTags: ["modeling-language", "pattern-library", "architecture-conformance", "documentation-framework", "pattern-extraction", "component-taxonomy", "interoperability-adapter", "topology-template", "reference-example"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 45, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-CONTEXT-MAP-DISCOVERY", title: "Context Mapper Discovery Library", publisher: "Context Mapper", sourceType: "open-standard", authorityLevel: 4, url: "https://github.com/ContextMapper/context-map-discovery", scopeTags: ["architecture-conformance", "implementation-example", "modeling-language", "interoperability-adapter", "architecture-test-generation", "reference-example"], status: "candidate", reviewedAt: '2026-07-11', refreshCadenceDays: 60, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-CNCF-LANDSCAPE-GRAPH", title: "CNCF Landscape Graph", publisher: "CNCF", sourceType: "official-method", authorityLevel: 4, url: "https://github.com/cncf/landscape-graph", scopeTags: ["component-library", "discovery-index", "component-taxonomy", "discovery-only", "interoperability-adapter"], status: "candidate", reviewedAt: '2026-07-11', refreshCadenceDays: 30, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-MESHERY", title: "Meshery Models and Design Templates", publisher: "Layer5 / CNCF", sourceType: "open-standard", authorityLevel: 4, url: "https://github.com/meshery/meshery", scopeTags: ["component-library", "reference-architecture", "modeling-language", "implementation-example", "component-taxonomy", "topology-template", "interoperability-adapter", "reference-example"], status: "approved", reviewedAt: '2026-07-11', refreshCadenceDays: 30, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-ARCHITECTURE-CATALOG", title: "Git-native Architecture Catalog", publisher: "EA Toolkit", sourceType: "open-standard", authorityLevel: 3, url: "https://github.com/ea-toolkit/architecture-catalog", scopeTags: ["documentation-framework", "component-library", "modeling-language", "interoperability-adapter", "component-taxonomy", "reference-example"], status: "candidate", reviewedAt: '2026-07-11', refreshCadenceDays: 60, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-ITATM-REFARCH", title: "it@M Reference Architecture Components", publisher: "City of Munich / it@M", sourceType: "official-method", authorityLevel: 3, url: "https://github.com/it-at-m/refarch", scopeTags: ["reference-architecture", "component-library", "implementation-example", "component-taxonomy", "reference-example", "topology-template"], status: "candidate", reviewedAt: '2026-07-11', refreshCadenceDays: 60, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-ARDALIS-CLEAN-ARCH", title: "Ardalis Clean Architecture Template", publisher: "Ardalis", sourceType: "official-method", authorityLevel: 3, url: "https://github.com/ardalis/CleanArchitecture", scopeTags: ["reference-architecture", "implementation-example", "pattern-library", "reference-example", "pattern-extraction", "architecture-test-generation"], status: "candidate", reviewedAt: '2026-07-11', refreshCadenceDays: 60, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-DEVELOPER-ROADMAP", title: "Developer Roadmap", publisher: "Community", sourceType: "official-method", authorityLevel: 3, url: "https://github.com/nilbuild/developer-roadmap", scopeTags: ["discovery-index", "architecture-method", "discovery-only", "reference-example"], status: "candidate", reviewedAt: '2026-07-11', refreshCadenceDays: 180, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-SYSTEM-DESIGN-101", title: "System Design 101", publisher: "ByteByteGo", sourceType: "official-method", authorityLevel: 3, url: "https://github.com/ByteByteGoHq/system-design-101", scopeTags: ["discovery-index", "implementation-example", "discovery-only", "reference-example"], status: "candidate", reviewedAt: '2026-07-11', refreshCadenceDays: 180, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-AWESOME-SCALABILITY", title: "Awesome Scalability", publisher: "Community", sourceType: "official-method", authorityLevel: 3, url: "https://github.com/binhnguyennus/awesome-scalability", scopeTags: ["discovery-index", "reference-architecture", "discovery-only", "reference-example"], status: "candidate", reviewedAt: '2026-07-11', refreshCadenceDays: 180, ingestionMode: 'allowlisted-refresh' },
  { id: "GH-AWESOME-SYSTEM-DESIGN-RESOURCES", title: "Awesome System Design Resources", publisher: "Community", sourceType: "official-method", authorityLevel: 3, url: "https://github.com/ashishps1/awesome-system-design-resources", scopeTags: ["discovery-index", "implementation-example", "discovery-only", "reference-example"], status: "candidate", reviewedAt: '2026-07-11', refreshCadenceDays: 180, ingestionMode: 'allowlisted-refresh' },

];

export const coreAntiPatterns: AntiPatternRecord[] = [
  { id: 'ANTI-DISTRIBUTED-MONOLITH', name: 'Distributed Monolith', category: 'service-boundaries', description: 'Separately deployed services remain tightly coupled through synchronous chains, shared release coordination or shared data ownership.', signals: ['dense synchronous service graph','coordinated deployment','shared database across independent services'], risks: ['cascading failure','slow delivery','poor autonomy'], mitigations: ['revisit bounded contexts','reduce chatty calls','clarify data ownership','consider a modular monolith where independence is not real'], evidenceSourceIds: ['SRC-AZURE-AAC','SRC-AWS-WAF','SRC-INTERNAL-PRINCIPLES'] },
  { id: 'ANTI-CHATTER', name: 'Chatty Service Interface', category: 'integration', description: 'A user operation requires many small remote calls, amplifying latency and partial-failure risk.', signals: ['long synchronous call chains','many fine-grained remote calls'], risks: ['latency amplification','cascading failure'], mitigations: ['coarsen service interfaces','aggregate calls','use asynchronous workflow where appropriate'], evidenceSourceIds: ['SRC-AZURE-AAC','SRC-GCP-WAF'] },
  { id: 'ANTI-SHARED-DATABASE-COUPLING', name: 'Shared Database Coupling', category: 'data', description: 'Multiple independently changing deployables depend directly on the same schema without explicit ownership boundaries.', signals: ['multiple deployables write same tables','schema changes require coordinated release'], risks: ['deployment coupling','data ownership ambiguity'], mitigations: ['assign schema ownership','introduce contracts or anti-corruption layers','use staged extraction'], evidenceSourceIds: ['SRC-INTERNAL-PRINCIPLES','SRC-AZURE-AAC'] },
  { id: 'ANTI-RETRY-STORM', name: 'Retry Storm', category: 'resilience', description: 'Unbounded or synchronized retries increase load on an already failing dependency.', signals: ['retry without jitter','unbounded attempts','no retry budget'], risks: ['resource exhaustion','extended outage'], mitigations: ['exponential backoff with jitter','retry budgets','circuit breaker','load shedding'], evidenceSourceIds: ['SRC-AWS-WAF','SRC-AZURE-AAC','SRC-GCP-WAF'] },
  { id: 'ANTI-SINGLE-FAILURE-DOMAIN', name: 'Single Failure Domain for Critical Workload', category: 'deployment', description: 'A critical component and its dependencies are concentrated in one failure domain.', signals: ['single zone','single instance','single region without recovery plan'], risks: ['availability loss','recovery delay'], mitigations: ['multi-zone placement','tested failover','backup and recovery objectives'], evidenceSourceIds: ['SRC-AWS-WAF','SRC-GCP-WAF'] },
  { id: 'ANTI-UNVERSIONED-CONTRACT', name: 'Unversioned Interface Contract', category: 'integration', description: 'API or event contracts evolve without compatibility or consumer-management rules.', signals: ['no API versioning','no event schema ownership','breaking changes'], risks: ['consumer outages','release coupling'], mitigations: ['explicit compatibility policy','contract testing','schema registry','deprecation window'], evidenceSourceIds: ['SRC-OPENAPI','SRC-INTERNAL-PRINCIPLES'] },
  { id: 'ANTI-OBSERVABILITY-AFTERTHOUGHT', name: 'Observability as an Afterthought', category: 'operations', description: 'The architecture lacks trace, metric and log responsibilities for important flows.', signals: ['no correlation identifiers','no service-level indicators','no failure telemetry'], risks: ['slow diagnosis','unknown reliability posture'], mitigations: ['define telemetry at design time','distributed tracing','service-level objectives'], evidenceSourceIds: ['SRC-OTEL','SRC-AWS-WAF','SRC-GCP-WAF'] },
  { id: 'ANTI-GOD-SERVICE', name: 'God Service', category: 'application-structure', description: 'One service owns unrelated responsibilities and becomes the change and scaling bottleneck.', signals: ['many unrelated capabilities','high fan-in and fan-out','frequent unrelated changes'], risks: ['low modifiability','team contention'], mitigations: ['decompose by cohesive responsibility','use bounded-context analysis'], evidenceSourceIds: ['SRC-SEI-QAW','SRC-INTERNAL-PRINCIPLES'] },
  { id: 'ANTI-PREMATURE-DISTRIBUTION', name: 'Premature Distribution', category: 'architecture-style', description: 'Distributed deployment is selected before independent scaling, ownership or release needs justify the operational cost.', signals: ['small team','short delivery horizon','low operational maturity','many services with little autonomy'], risks: ['excess complexity','higher cost','slower delivery'], mitigations: ['modular monolith','service-based architecture','extract only proven boundaries'], evidenceSourceIds: ['SRC-SEI-QAW','SRC-INTERNAL-PRINCIPLES'] },
  { id: 'ANTI-SECURITY-BOLTON', name: 'Security Bolt-On', category: 'security', description: 'Trust boundaries, identity, data protection and abuse cases are deferred until implementation or review.', signals: ['no trust boundaries','public API without auth design','sensitive data without control mapping'], risks: ['design rework','control gaps','attack exposure'], mitigations: ['secure-by-design review','threat modeling','map controls to components and data flows'], evidenceSourceIds: ['SRC-OWASP-ASVS','SRC-NIST-SSDF'] },
  { id: 'ANTI-TECHNOLOGY-FIRST', name: 'Technology-First Architecture', category: 'decision-quality', description: 'Products are selected before logical requirements and quality scenarios are established.', signals: ['vendor product in logical view','no measurable quality scenarios','requirements copied from product features'], risks: ['vendor lock-in','poor requirement fit'], mitigations: ['separate logical capability from physical product','record decision drivers'], evidenceSourceIds: ['SRC-ISO-42010','SRC-SEI-QAW'] },
  { id: 'ANTI-IMPLICIT-OWNERSHIP', name: 'Implicit Ownership', category: 'governance', description: 'Components, data, interfaces or operational responsibilities lack an accountable owner.', signals: ['missing owner','unclear on-call responsibility','shared data with no steward'], risks: ['slow incident response','unmanaged change'], mitigations: ['record owning team','define data and interface stewardship','include ownership in ADRs'], evidenceSourceIds: ['SRC-AWS-WAF','SRC-INTERNAL-PRINCIPLES'] },
];
