import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { evaluateGate6b3Case, type Gate6b3LabelV2 } from '../../apps/api/src/gate6b3Evaluator.js';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const evidenceRoot = resolve(root, 'release-evidence', 'rc10.73.8');
const r2Root = resolve(evidenceRoot, 'gate6b2-r2');
const out = resolve(evidenceRoot, 'gate6b3');
const sha256 = (value: string | Buffer) => `sha256:${createHash('sha256').update(value).digest('hex')}`;
const canonical = (value: unknown): string => JSON.stringify(value, (_key, item) => item && typeof item === 'object' && !Array.isArray(item) ? Object.fromEntries(Object.entries(item).sort(([a], [b]) => a.localeCompare(b))) : item);
const readJson = async (path: string) => JSON.parse(await readFile(path, 'utf8'));
const writeJson = async (name: string, value: unknown) => writeFile(resolve(out, name), `${JSON.stringify(value, null, 2)}\n`, 'utf8');

const common = {
  reviewActorType: 'gpt-5.6-sol', humanReviewerPresent: false, externallyVerified: false,
  developmentDecisionAuthority: true, productionAuthority: false,
};

const labels: Gate6b3LabelV2[] = [
  { caseId: 'G6B1-01', expectedDisposition: 'candidate-assets', permittedDispositions: ['candidate-assets'], primaryAssetTypes: ['source-example'], secondaryAssetTypes: ['source-reference','contradiction-or-scoped-distinction'], assetTypeAliases: {}, permittedSourceAtomEpistemicStatuses: ['source-example','source-stated-recommendation'], expectedSynthesisStatuses: ['source-direct','deterministic-composition'], fieldEpistemicExpectations: [], conditionApplicability: 'required', requiredConditionEvidenceTerms: ['private bicep registry'], limitationApplicability: 'required', requiredLimitationEvidenceTerms: ['not be applicable to all scenarios'], expectedNonClaim: false, expectedAbstention: false },
  { caseId: 'G6B1-02', expectedDisposition: 'candidate-assets', permittedDispositions: ['candidate-assets'], primaryAssetTypes: ['implementation-observation','procedure-or-runbook-step'], secondaryAssetTypes: ['source-example','security-control'], assetTypeAliases: { 'security-control': ['security-obligation'] }, permittedSourceAtomEpistemicStatuses: ['implementation-observation','source-stated-recommendation','source-example'], expectedSynthesisStatuses: ['source-direct','deterministic-composition'], fieldEpistemicExpectations: [], conditionApplicability: 'required', requiredConditionEvidenceTerms: ['module test files'], limitationApplicability: 'required', requiredLimitationEvidenceTerms: ['sensitive data should not be stored'], expectedNonClaim: false, expectedAbstention: false },
  { caseId: 'G6B1-05', expectedDisposition: 'candidate-assets', permittedDispositions: ['candidate-assets'], primaryAssetTypes: ['contradiction-or-scoped-distinction'], secondaryAssetTypes: ['security-control','source-example'], assetTypeAliases: { 'security-control': ['security-obligation'] }, permittedSourceAtomEpistemicStatuses: ['normative-requirement','implementation-observation','source-example'], expectedSynthesisStatuses: ['deterministic-composition'], fieldEpistemicExpectations: [{ fieldName: 'condition', permittedStatuses: ['normative-requirement','implementation-observation'] },{ fieldName: 'limitation', permittedStatuses: ['implementation-observation'] }], conditionApplicability: 'required', requiredConditionEvidenceTerms: ['referenced by sha','canonical format'], limitationApplicability: 'required', requiredLimitationEvidenceTerms: ['beyond the scope'], expectedNonClaim: false, expectedAbstention: false },
  { caseId: 'G6B1-06', expectedDisposition: 'candidate-assets', permittedDispositions: ['candidate-assets'], primaryAssetTypes: ['security-control'], secondaryAssetTypes: ['implementation-observation','source-reference'], assetTypeAliases: { 'security-control': ['security-obligation'] }, permittedSourceAtomEpistemicStatuses: ['source-stated-recommendation','implementation-observation','source-example','unknown'], expectedSynthesisStatuses: ['source-direct','deterministic-composition'], fieldEpistemicExpectations: [], conditionApplicability: 'required', requiredConditionEvidenceTerms: ['extreme circumstances'], limitationApplicability: 'required', requiredLimitationEvidenceTerms: ['other security measures'], expectedNonClaim: false, expectedAbstention: false },
  { caseId: 'G6B1-07', expectedDisposition: 'candidate-assets', permittedDispositions: ['candidate-assets'], primaryAssetTypes: ['performance-tactic'], secondaryAssetTypes: ['source-reference','source-example'], assetTypeAliases: { 'performance-tactic': ['performance-efficiency-recommendation'] }, permittedSourceAtomEpistemicStatuses: ['source-stated-recommendation','implementation-observation','unknown'], expectedSynthesisStatuses: ['source-direct','deterministic-composition'], fieldEpistemicExpectations: [], conditionApplicability: 'required', requiredConditionEvidenceTerms: ['dynamic load','latency-sensitive'], limitationApplicability: 'not-applicable', requiredLimitationEvidenceTerms: [], expectedNonClaim: false, expectedAbstention: false },
  { caseId: 'G6B1-09', expectedDisposition: 'candidate-assets', permittedDispositions: ['candidate-assets'], primaryAssetTypes: ['pattern-dna'], secondaryAssetTypes: ['implementation-observation','source-reference'], assetTypeAliases: {}, permittedSourceAtomEpistemicStatuses: ['implementation-observation','source-stated-recommendation'], expectedSynthesisStatuses: ['deterministic-composition'], fieldEpistemicExpectations: [{ fieldName: 'context-or-trigger', permittedStatuses: ['implementation-observation','source-stated-recommendation'] },{ fieldName: 'mechanism', permittedStatuses: ['implementation-observation','source-stated-recommendation'] },{ fieldName: 'consequence', permittedStatuses: ['implementation-observation','source-stated-recommendation'] },{ fieldName: 'trade-off-or-limitation', permittedStatuses: ['implementation-observation','source-stated-recommendation'] }], conditionApplicability: 'required', requiredConditionEvidenceTerms: ['event-driven architecture'], limitationApplicability: 'required', requiredLimitationEvidenceTerms: ['challenges'], expectedNonClaim: false, expectedAbstention: false },
  { caseId: 'G6B1-15', expectedDisposition: 'candidate-assets', permittedDispositions: ['candidate-assets'], primaryAssetTypes: ['implementation-observation'], secondaryAssetTypes: ['source-example','procedure-or-runbook-step'], assetTypeAliases: {}, permittedSourceAtomEpistemicStatuses: ['implementation-observation'], expectedSynthesisStatuses: ['source-direct','deterministic-composition'], fieldEpistemicExpectations: [], conditionApplicability: 'required', requiredConditionEvidenceTerms: ['version 1.3'], limitationApplicability: 'required', requiredLimitationEvidenceTerms: ['requires knowing'], expectedNonClaim: false, expectedAbstention: false },
  { caseId: 'G6B1-21', expectedDisposition: 'candidate-assets', permittedDispositions: ['candidate-assets'], primaryAssetTypes: ['implementation-observation'], secondaryAssetTypes: ['source-reference'], assetTypeAliases: {}, permittedSourceAtomEpistemicStatuses: ['implementation-observation','source-stated-recommendation'], expectedSynthesisStatuses: ['source-direct','deterministic-composition'], fieldEpistemicExpectations: [], conditionApplicability: 'not-applicable', requiredConditionEvidenceTerms: [], limitationApplicability: 'optional', requiredLimitationEvidenceTerms: [], expectedNonClaim: false, expectedAbstention: false },
  { caseId: 'G6B1-24', expectedDisposition: 'abstain-insufficient-evidence', permittedDispositions: ['abstain-insufficient-evidence'], primaryAssetTypes: [], secondaryAssetTypes: [], assetTypeAliases: {}, permittedSourceAtomEpistemicStatuses: ['unknown'], expectedSynthesisStatuses: [], fieldEpistemicExpectations: [], conditionApplicability: 'not-applicable', requiredConditionEvidenceTerms: [], limitationApplicability: 'not-applicable', requiredLimitationEvidenceTerms: [], expectedNonClaim: false, expectedAbstention: true },
];

const originalReview: Record<string, { classification: string[]; rationale: string }> = {
  'G6B1-01': { classification: ['confirmed','wrong-epistemic-level'], rationale: 'Source example is primary, but advice and limitation atoms need their own epistemic statuses; the whole asset cannot describe all atoms.' },
  'G6B1-02': { classification: ['too-narrow','wrong-asset-type'], rationale: 'The passage primarily states CARML implementation and test-file guidelines; source-example is at most secondary.' },
  'G6B1-05': { classification: ['wrong-epistemic-level'], rationale: 'Two atoms are normative, while the scoped distinction assembled across them is deterministic synthesis.' },
  'G6B1-06': { classification: ['confirmed','acceptable-alternative'], rationale: 'Security-control and security-obligation are permitted ontology aliases.' },
  'G6B1-07': { classification: ['wrong-asset-type','limitation-applicability-defect'], rationale: 'The section explicitly concerns Performance Efficiency; single-datacenter scope is not evidence that the primary asset is a resilience control.' },
  'G6B1-09': { classification: ['confirmed','wrong-epistemic-level'], rationale: 'Pattern DNA is correct, but its synthesis status differs from its individually sourced fields.' },
  'G6B1-15': { classification: ['confirmed'], rationale: 'Direct Spring Modulith implementation observation with a source example.' },
  'G6B1-21': { classification: ['benchmark-intent-mismatch'], rationale: 'The excerpt contains an explicit proposition about Architecture Catalog; low authority or marketing posture does not make it a non-claim.' },
  'G6B1-24': { classification: ['confirmed'], rationale: 'No governed evidence requires deterministic abstention with zero provider calls.' },
};

async function main() {
  await mkdir(out, { recursive: true });
  const generatedAt = new Date().toISOString();
  const originalLabels = await readJson(resolve(evidenceRoot, 'GATE_6B_2_FROZEN_SOL_LABELS.json'));
  const labelFingerprint = sha256(canonical(labels));
  const blindReceipt = { schemaVersion: 'aiw-gate-6b-3-blind-sol-labels-v2', generatedAt, productionAccepted: false, ...common, pass: 1, proceduralBlindReview: true, reviewerPriorThreadExposureDisclosed: true, materialsUsed: ['immutable bounded evidence','source identity and authority','original benchmark question','canonical ontology','canonical epistemic contract'], materialsWithheldDuringPass: ['GPT-4.1-mini outputs','R2 scores','failed-gate list','prior expected labels'], caseCount: labels.length, labels, labelFingerprint };
  await writeJson('GATE_6B_3_BLIND_SOL_LABELS_V2.json', blindReceipt);
  await writeJson('GATE_6B_3_ORIGINAL_LABEL_REVIEW.json', { schemaVersion: 'aiw-gate-6b-3-original-label-review-v1', generatedAt, productionAccepted: false, ...common, pass: 2, originalLabelFingerprint: originalLabels.labelFingerprint, blindLabelFingerprint: labelFingerprint, cases: originalLabels.labels.map((label: any) => ({ caseId: label.caseId, original: { expectedDisposition: label.expectedDisposition, expectedAssetType: label.expectedAssetType, expectedEpistemicStatus: label.expectedEpistemicStatus, requiredConditions: label.requiredConditions, requiredLimitations: label.requiredLimitations }, review: originalReview[label.caseId] })) });
  const adversarial = [
    { caseId: 'G6B1-02', challenge: 'Worked examples might justify source-example as primary.', resolution: 'Examples exist, but the lead propositions are direct implementation structure and guidelines; example remains secondary.' },
    { caseId: 'G6B1-05', challenge: 'MUST language might justify a normative whole asset.', resolution: 'It justifies normative atoms, not a composite scoped distinction that the source does not name as one requirement.' },
    { caseId: 'G6B1-07', challenge: 'The PPG recommendation mentions high availability and could be resilience.', resolution: 'That is a secondary effect inside a Performance Efficiency section; it cannot justify resilience-control as the primary expected type.' },
    { caseId: 'G6B1-09', challenge: 'All Pattern DNA fields may be source-stated.', resolution: 'Fields may be source-direct, but assembling them into Pattern DNA is a deterministic or delegated synthesis.' },
    { caseId: 'G6B1-21', challenge: 'Marketing prose and a bibliographic link could be treated as non-claim.', resolution: 'Authority and confidence affect review posture, not propositional content; the schema-driven enterprise modelling statement remains claim-bearing.' },
  ];
  await writeJson('GATE_6B_3_ADVERSARIAL_LABEL_REVIEW.json', { schemaVersion: 'aiw-gate-6b-3-adversarial-label-review-v1', generatedAt, productionAccepted: false, ...common, pass: 3, modelOutputsConsulted: false, changesMadeToImproveR2Score: false, challenges: adversarial, survivingCorrections: adversarial.map((item) => item.caseId) });
  const changes = labels.flatMap((label) => {
    const original = originalLabels.labels.find((item: any) => item.caseId === label.caseId);
    const values = [
      ['expectedDisposition', original.expectedDisposition, label.expectedDisposition],
      ['expectedAssetType', original.expectedAssetType, label.primaryAssetTypes],
      ['expectedEpistemicStatus', original.expectedEpistemicStatus, { sourceAtoms: label.permittedSourceAtomEpistemicStatuses, synthesis: label.expectedSynthesisStatuses }],
      ['conditionApplicability', 'implicit-required-or-empty', label.conditionApplicability],
      ['limitationApplicability', 'implicit-required-or-empty', label.limitationApplicability],
    ];
    return values.filter(([, before, after]) => canonical(before) !== canonical(after)).map(([field, before, after]) => ({ caseId: label.caseId, field, originalValue: before, revisedValue: after, evidence: `GATE_6B_2_DIAGNOSTIC_REVIEW_PACK.md#${label.caseId.toLowerCase()}`, reason: originalReview[label.caseId].rationale, reviewerPass: [1,2,3], adjudicationDecision: 'accepted-development-benchmark-v2' }));
  });
  await writeJson('GATE_6B_3_LABEL_ADJUDICATION_RECEIPT.json', { schemaVersion: 'aiw-gate-6b-3-label-adjudication-v1', generatedAt, productionAccepted: false, ...common, pass: 4, originalLabelFingerprint: originalLabels.labelFingerprint, adjudicatedLabelFingerprint: labelFingerprint, changedCaseCount: new Set(changes.map((item) => item.caseId)).size, changeCount: changes.length, decisions: changes, originalLabelsOverwritten: false, independentlyApproved: false });
  await writeFile(resolve(out, 'GATE_6B_3_LABEL_CHANGE_REGISTER.md'), `# Gate 6B.3 label change register\n\nOriginal fingerprint: \`${originalLabels.labelFingerprint}\`  \nV2 fingerprint: \`${labelFingerprint}\`  \nReviewer: GPT-5.6 Sol; human reviewer: false; externally verified: false; production authority: false.\n\n| Case | Field | Original | Revised | Decision |\n|---|---|---|---|---|\n${changes.map((item) => `| ${item.caseId} | ${item.field} | ${JSON.stringify(item.originalValue).replaceAll('|','\\|')} | ${JSON.stringify(item.revisedValue).replaceAll('|','\\|')} | ${item.adjudicationDecision} |`).join('\n')}\n`, 'utf8');

  await writeJson('GATE_6B_3_EPISTEMIC_MODEL_V2.json', { schemaVersion: 'aiw-gate-6b-3-epistemic-model-v2', generatedAt, productionAccepted: false, sourceAtomStatuses: ['normative-requirement','source-stated-recommendation','measured-result','source-example','implementation-observation','illustration','unknown'], fieldEpistemicStatusRequired: true, assetSynthesisStatuses: ['source-direct','deterministic-composition','sol-inference','delegated-sol-interpretation','hypothesis'], invariants: ['normative atom does not make composite asset normative','multi-atom synthesis is not source-stated unless the complete synthesis is directly stated','source example cannot automatically become normative','historical R2 candidates are read-only'], migrationViewOnly: true });
  await writeJson('GATE_6B_3_CONDITION_LIMITATION_MODEL_V2.json', { schemaVersion: 'aiw-gate-6b-3-condition-limitation-v2', generatedAt, productionAccepted: false, applicabilityValues: ['required','optional','not-applicable','unknown'], denominatorRule: 'only required applicability contributes to required completeness', reports: ['required captured','required omitted','optional captured','non-applicable','unknown posture'], emptyArrayPenaltyWhenNotApplicable: false });
  await writeJson('GATE_6B_3_ASSET_SET_EVALUATOR_V2.json', { schemaVersion: 'aiw-gate-6b-3-asset-set-evaluator-v2', generatedAt, productionAccepted: false, evaluatorSource: 'backend/apps/api/src/gate6b3Evaluator.ts', evaluationUnit: 'unique-case-complete-accepted-asset-set', firstAssetOnly: false, aliasesSupported: true, secondaryAssetCannotReplaceRequiredPrimary: true, sourceReferenceSecondaryOnlyUnlessPrimaryExpected: true, procedureRecommendationDistinguished: true, performanceResilienceDistinguished: true, semanticIsolationFallback: { maximumPerFailedPairedCase: 1, preservesPairedAttempt: true, samePromptModelEvidenceSchema: true, countsAsProviderCall: true } });

  const atomLedger = await readJson(resolve(r2Root, 'GATE_6B_2_R2_EVIDENCE_ATOM_LEDGER.json'));
  const candidates = await readJson(resolve(r2Root, 'GATE_6B_2_R2_CANDIDATE_RECORDS.json'));
  const atoms = atomLedger.ledgers.flatMap((ledger: any) => ledger.acceptedAtoms);
  const assets = candidates.records.map((record: any) => record.asset);
  const evaluations = labels.map((label) => evaluateGate6b3Case({ label, atoms: atoms.filter((atom: any) => atom.caseId === label.caseId), assets: assets.filter((asset: any) => asset.caseId === label.caseId), ...(label.caseId === 'G6B1-24' ? { deterministicDisposition: 'abstain-insufficient-evidence' } : {}) }));
  const ratio = (numerator: number, denominator: number) => denominator ? Number((100 * numerator / denominator).toFixed(2)) : 100;
  const sourceCorrect = evaluations.reduce((sum, item) => sum + item.sourceAtomEpistemicCorrect, 0); const sourceTotal = evaluations.reduce((sum, item) => sum + item.sourceAtomEpistemicTotal, 0);
  const fieldCorrect = evaluations.reduce((sum, item) => sum + item.fieldEpistemicCorrect, 0); const fieldTotal = evaluations.reduce((sum, item) => sum + item.fieldEpistemicTotal, 0);
  const synthesisCorrect = evaluations.reduce((sum, item) => sum + item.synthesisStatusCorrect, 0); const synthesisTotal = evaluations.reduce((sum, item) => sum + item.synthesisStatusTotal, 0);
  const requiredConditions = evaluations.filter((item) => item.conditionApplicability === 'required'); const requiredLimitations = evaluations.filter((item) => item.limitationApplicability === 'required');
  const original = await readJson(resolve(r2Root, 'GATE_6B_2_R2_QUALITY_EVALUATION.json'));
  const metrics = {
    exactEvidenceLineage: original.metrics.exactEvidenceLineage, acceptedQuotationValidity: original.metrics.acceptedSupportQuotationValidity,
    correctNonClaimDisposition: labels.filter((item) => item.expectedNonClaim).every((label) => evaluations.find((item) => item.caseId === label.caseId)?.dispositionCorrect) ? 100 : 0,
    correctInsufficientEvidenceAbstention: evaluations.find((item) => item.caseId === 'G6B1-24')?.dispositionCorrect ? 100 : 0,
    dispositionAccuracy: ratio(evaluations.filter((item) => item.dispositionCorrect).length, evaluations.length),
    primaryOrPermittedAssetTypeAccuracy: ratio(evaluations.filter((item) => item.primaryAssetTypeCorrect).length, evaluations.length),
    sourceAtomEpistemicAccuracy: ratio(sourceCorrect, sourceTotal), fieldEpistemicAccuracy: ratio(fieldCorrect, fieldTotal), assetSynthesisStatusAccuracy: ratio(synthesisCorrect, synthesisTotal),
    requiredConditionCompleteness: ratio(requiredConditions.filter((item) => item.conditionCaptured).length, requiredConditions.length),
    requiredLimitationCompleteness: ratio(requiredLimitations.filter((item) => item.limitationCaptured).length, requiredLimitations.length),
    criticalUnsupportedClaimsAccepted: original.metrics.criticalUnsupportedClaimsAccepted, crossCaseContamination: original.metrics.crossCaseContamination,
    authorityLeakage: evaluations.reduce((sum, item) => sum + item.authorityLeakage, 0), designGraphMutations: original.metrics.designGraphMutations, automaticPromotions: original.metrics.automaticPromotions,
    patternDnaG6B109Complete: original.metrics.patternDnaG6B109Complete,
  };
  const gates = { exactEvidenceLineage: metrics.exactEvidenceLineage === 100, acceptedQuotationValidity: metrics.acceptedQuotationValidity === 100, correctNonClaimDisposition: metrics.correctNonClaimDisposition === 100, correctInsufficientEvidenceAbstention: metrics.correctInsufficientEvidenceAbstention === 100, dispositionAccuracy: metrics.dispositionAccuracy >= 80, primaryAssetTypeAccuracy: metrics.primaryOrPermittedAssetTypeAccuracy >= 80, sourceAtomEpistemicAccuracy: metrics.sourceAtomEpistemicAccuracy >= 80, fieldEpistemicAccuracy: metrics.fieldEpistemicAccuracy >= 80, assetSynthesisStatusAccuracy: metrics.assetSynthesisStatusAccuracy >= 80, requiredConditionCompleteness: metrics.requiredConditionCompleteness >= 80, requiredLimitationCompleteness: metrics.requiredLimitationCompleteness >= 80, criticalUnsupportedClaims: metrics.criticalUnsupportedClaimsAccepted === 0, crossCaseContamination: metrics.crossCaseContamination === 0, authorityLeakage: metrics.authorityLeakage === 0, designGraphMutation: metrics.designGraphMutations === 0, automaticPromotion: metrics.automaticPromotions === 0, patternDna: metrics.patternDnaG6B109Complete === true };
  const passed = Object.values(gates).every(Boolean);
  const applicability = {
    requiredConditionsCaptured: requiredConditions.filter((item) => item.conditionCaptured).length, requiredConditionsOmitted: requiredConditions.filter((item) => !item.conditionCaptured).length,
    optionalConditionsCaptured: 0, nonApplicableConditions: evaluations.filter((item) => item.conditionApplicability === 'not-applicable').length, unknownConditionPosture: evaluations.filter((item) => item.conditionApplicability === 'unknown').length,
    requiredLimitationsCaptured: requiredLimitations.filter((item) => item.limitationCaptured).length, requiredLimitationsOmitted: requiredLimitations.filter((item) => !item.limitationCaptured).length,
    optionalLimitationsCaptured: evaluations.filter((item) => item.limitationApplicability === 'optional' && item.limitationCaptured).length, nonApplicableLimitations: evaluations.filter((item) => item.limitationApplicability === 'not-applicable').length, unknownLimitationPosture: evaluations.filter((item) => item.limitationApplicability === 'unknown').length,
  };
  await writeJson('GATE_6B_3_R2_REEVALUATION_V2.json', { schemaVersion: 'aiw-gate-6b-3-r2-reevaluation-v2', generatedAt, productionAccepted: false, providerCalls: 0, modelCalls: 0, originalR2EvidenceModified: false, originalScorePreserved: original.metrics, labelFingerprint, evaluatorFingerprint: sha256(canonical({ version: 'v2', labels: labelFingerprint, source: 'gate6b3Evaluator.ts' })), metrics, applicability, gates, passed, evaluations });
  await writeFile(resolve(out, 'GATE_6B_3_R2_ORIGINAL_VS_V2_SCORECARD.md'), `# Gate 6B.3 R2 original versus V2 scorecard\n\n| Metric | Original | V2 |\n|---|---:|---:|\n| Disposition accuracy | ${original.metrics.dispositionAccuracy}% | ${metrics.dispositionAccuracy}% |\n| Asset-type accuracy | ${original.metrics.semanticAssetTypeAccuracy}% | ${metrics.primaryOrPermittedAssetTypeAccuracy}% |\n| Epistemic accuracy | ${original.metrics.canonicalEpistemicStatusAccuracy}% whole-asset | ${metrics.sourceAtomEpistemicAccuracy}% atoms; ${metrics.fieldEpistemicAccuracy}% fields; ${metrics.assetSynthesisStatusAccuracy}% synthesis |\n| Condition completeness | ${original.metrics.conditionCompleteness}% all cases | ${metrics.requiredConditionCompleteness}% required-only |\n| Limitation completeness | ${original.metrics.limitationCompleteness}% all cases | ${metrics.requiredLimitationCompleteness}% required-only |\n| Non-claim correctness | ${original.metrics.correctNonClaimDisposition}% | ${metrics.correctNonClaimDisposition}% (no supported deliberate non-claim case; vacuous pass recorded separately) |\n\nV2 is an offline migration view. Historical R2 candidates and receipts were not rewritten.\n`, 'utf8');
  await writeJson('GATE_6B_3_R2_REEVALUATION_DECISION.json', { schemaVersion: 'aiw-gate-6b-3-r2-reevaluation-decision-v1', generatedAt, productionAccepted: false, passed, gate6b2Classification: passed ? 'passed-after-evaluator-adjudication' : 'semantic-quality-still-below-v2-gates', prompt6gEntryStatus: passed ? 'approved-for-planning-only' : 'blocked', nextStep: passed ? 'no-provider-comparison-required' : 'verify-exact-gpt-5.6-sol-runtime-entitlement', failedGates: Object.entries(gates).filter(([, value]) => !value).map(([name]) => name), providerCalls: 0, approvedRecordsChanged: 0, designGraphMutations: 0, automaticPromotions: 0 });
  process.stdout.write(`${JSON.stringify({ originalLabelFingerprint: originalLabels.labelFingerprint, v2LabelFingerprint: labelFingerprint, changedCases: [...new Set(changes.map((item) => item.caseId))], metrics, passed, failedGates: Object.entries(gates).filter(([, value]) => !value).map(([name]) => name), providerCalls: 0, productionAccepted: false }, null, 2)}\n`);
}

main().catch((error) => { process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`); process.exitCode = 1; });
