import { createHash } from 'node:crypto';
import { createReadStream } from 'node:fs';
import { mkdir, readFile, readdir, stat, statfs, writeFile } from 'node:fs/promises';
import { dirname, extname, resolve } from 'node:path';
import { createInterface } from 'node:readline';
import { fileURLToPath } from 'node:url';
import { routePrompt6gUnit, validatePrompt6gRoutingIntegrity, type Prompt6gRoutingDecision, type Prompt6gRoutingFeatures } from '../../apps/api/src/prompt6gCapabilityRouter.js';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const releaseRoot = resolve(root, 'release-evidence', 'rc10.73.8');
const gate6b3Root = resolve(releaseRoot, 'gate6b3');
const outputRoot = resolve(releaseRoot, 'prompt6g-planning');
const gate6aRoot = resolve(root, 'knowledge-repository', 'AKR-0.10.73.8', 'candidate', 'gate-6a', 'deterministic-corpus-v1');
const planningLedgerRoot = resolve(root, 'knowledge-repository', 'AKR-0.10.73.8', 'candidate', 'prompt-6g-planning-v1');
const generatedAt = new Date().toISOString();
const expectedDenominator = 42_953;
const sha256 = (value: string | Buffer) => `sha256:${createHash('sha256').update(value).digest('hex')}`;
const stable = (value: any): any => Array.isArray(value) ? value.map(stable) : value && typeof value === 'object' ? Object.fromEntries(Object.entries(value).sort(([a],[b]) => a.localeCompare(b)).map(([key,item]) => [key,stable(item)])) : value;
const stableJson = (value: unknown) => JSON.stringify(stable(value));
const readJson = async (path: string) => JSON.parse(await readFile(path, 'utf8'));
const writeJson = async (name: string, value: unknown) => writeFile(resolve(outputRoot, name), `${JSON.stringify(value, null, 2)}\n`, 'utf8');
const countBy = <T>(items: T[], key: (item: T) => string) => Object.fromEntries([...items.reduce((map, item) => map.set(key(item), (map.get(key(item)) ?? 0) + 1), new Map<string,number>()).entries()].sort(([a],[b]) => a.localeCompare(b)));
async function* ndjson(path: string) { const lines = createInterface({ input: createReadStream(path, { encoding: 'utf8' }), crlfDelay: Infinity }); for await (const line of lines) if (line.trim()) yield JSON.parse(line); }
async function fileHash(path: string) { return sha256(await readFile(path)); }
async function freeBytes() { const disk = await statfs(root, { bigint: true }); return Number(disk.bavail * disk.bsize); }

const enabledAssetClasses = ['source-example-with-explicit-conditions-and-limitations','direct-implementation-observation'];
const deferredClasses = ['contradiction-and-scoped-distinction','security-obligation','performance-tactic','pattern-dna','architecture-genome','modernisation-knowledge','low-authority-product-description','complex-epistemic-synthesis','complex-condition-and-limitation-synthesis','whole-reference-architecture-assembly','untested-semantic-asset-class'];

function textSignals(text: string, record: any, file: any, authority: string, groups: string[]): Prompt6gRoutingFeatures {
  const lower = text.toLowerCase(); const pathText = `${record.path} ${record.heading ?? ''}`.toLowerCase();
  const normative = /\b(must|shall|required|requires|required to|should|recommended|ought)\b/i.test(text);
  const condition = /\b(if|when|whenever|unless|provided that|only if|in case|under the condition|where applicable|depending on)\b/i.test(text);
  const limitation = /\b(however|but|except|limitation|constraint|trade-?off|cannot|must not|not supported|only supports?|at the cost of|restricted to|does not)\b/i.test(text);
  const example = record.baseDisposition === 'implementation-example' || /\b(example|sample|demo|tutorial|walkthrough)\b/i.test(pathText) || /\bfor example\b/i.test(text);
  const observation = /\b(is implemented|are implemented|uses|contains|consists of|provides|includes|supports|exposes|stores|runs|deploys|is configured|are configured)\b/i.test(text);
  const format = String(file?.languageOrFormat ?? extname(record.path).slice(1) ?? 'unknown').toLowerCase() || 'unknown';
  const machine = ['json','yaml','yml','xml','toml','properties','tf','hcl','bicep'].includes(format) || ['structured-data-or-contract','infrastructure-code'].includes(file?.contentKind);
  const meaningfulWords = text.match(/[\p{L}\p{N}][\p{L}\p{N}'_-]*/gu)?.length ?? 0;
  const metadataOnly = machine && meaningfulWords <= 80 && !/[.!?]\s+[A-Z]/.test(text) && /[:={}\[\]]/.test(text);
  const contradiction = Boolean(record.contradictionEvidenceEstimate) || /\b(contradict|conflict|inconsistent|whereas|on the other hand)\b/i.test(text);
  const security = /\b(security|authentication|authorization|identity|credential|threat|trust boundary|encryption|least privilege|zero trust)\b/i.test(lower);
  const performance = /\b(performance|latency|throughput|capacity|scalability|efficiency|response time|cache)\b/i.test(lower);
  const causalPattern = /\b(pattern|context|trigger|mechanism|consequence|trade-?off|cause|results in|leads to)\b/i.test(lower);
  const architectureGenome = /\b(architecture genome|reference architecture|topology|blueprint|architecture model)\b/i.test(lower);
  const modernisation = /\b(modernisation|modernization|migration|refactor|legacy|strangler|target state|current state)\b/i.test(lower);
  const productDescription = authority === 'educational-or-discovery-source' && /\b(platform|product|solution|catalog|offering|enables customers|helps teams)\b/i.test(lower);
  const complexEpistemic = /\b(may|might|possibly|typically|generally|often|appears|suggests|assume|hypothesis)\b/i.test(lower) && normative;
  const ambiguity = Boolean(file?.ambiguous) || /\b(unclear|ambiguous|unknown|to be determined|tbd)\b/i.test(lower);
  const specialist = /required/i.test(String(record.parserVersion ?? '')) || file?.parserStatus === 'preserved-awaiting-specialist-parser';
  const highRisk = security || modernisation || groups.length > 0;
  return {
    semanticUnitId: record.semanticUnitId, evidenceId: record.evidenceId, sourceAuthorityClass: authority,
    repository: record.repository, path: record.path, format, parserType: record.parserVersion ?? file?.parserVersion ?? 'unknown', heading: record.heading ?? '',
    evidenceLength: text.length, tokenCount: record.tokenCount ?? meaningfulWords, hasNormativeLanguage: normative,
    hasConditionMarkers: condition, hasLimitationMarkers: limitation, hasSourceExampleIndicators: example,
    hasImplementationObservationIndicators: observation, metadataOnly, machineReadableStructural: machine,
    noEvidence: text.length === 0, exactDuplicateOccurrenceCount: record.occurrenceCount ?? 1,
    normalizedVariantCount: record.normalizedVariantCount ?? 1, nearDuplicateCluster: Boolean(record.nearDuplicateCluster),
    crossFileGroupIds: groups, ambiguity, risk: highRisk ? 'high' : (contradiction || performance || causalPattern || architectureGenome || complexEpistemic ? 'medium' : 'low'),
    specialistParserRequirement: specialist, processingFailure: record.processingFailure ?? null,
    semanticSignals: { contradiction, security, performance, causalPattern, architectureGenome, modernisation, productDescription, complexEpistemic },
  };
}

function blindReview(features: Prompt6gRoutingFeatures, decision: Prompt6gRoutingDecision) {
  const complex = features.crossFileGroupIds.length > 0 || features.ambiguity || features.risk === 'high' || Object.values(features.semanticSignals).some(Boolean);
  let independentlyPermitted: 'route-a'|'route-c'|'deferred'|'failure' = 'deferred';
  if (features.processingFailure) independentlyPermitted = 'failure';
  else if (features.noEvidence || features.specialistParserRequirement || (features.machineReadableStructural && features.metadataOnly && !complex)) independentlyPermitted = 'route-c';
  else if (!complex && ['official-reference-architecture','architecture-conformance-implementation','reviewed-practitioner-or-implementation-source'].includes(features.sourceAuthorityClass)
    && ((features.hasSourceExampleIndicators && features.hasConditionMarkers && features.hasLimitationMarkers)
      || (features.hasImplementationObservationIndicators && !features.hasNormativeLanguage && !features.hasSourceExampleIndicators))) independentlyPermitted = 'route-a';
  const confirmed = decision.approvedRoute === independentlyPermitted || (decision.approvedRoute === 'deferred' && independentlyPermitted !== 'failure');
  return { semanticUnitId: features.semanticUnitId, independentlyPermitted, assigned: decision.approvedRoute, confirmed, ambiguityDefaultsToDeferred: true, rationale: confirmed ? 'assignment remains within independently derived capability boundary' : 'enabled assignment lacks independent boundary support' };
}

function chooseStratified(records: any[], perKey: number, key: (item:any)=>string, limit = 120) {
  const selected = new Map<string,any>();
  for (const item of [...records].sort((a,b)=>a.semanticUnitId.localeCompare(b.semanticUnitId))) { const bucket = key(item); const current = [...selected.values()].filter((value)=>key(value)===bucket).length; if (current < perKey) selected.set(item.semanticUnitId,item); if (selected.size >= limit) break; }
  return [...selected.values()];
}

async function main() {
  if (process.argv.includes('--execute') || process.argv.includes('--live')) throw new Error('PROMPT6G_PLANNING_ONLY_PROVIDER_EXECUTION_PROHIBITED');
  await mkdir(outputRoot, { recursive: true }); await mkdir(planningLedgerRoot, { recursive: true });
  const freeBefore = await freeBytes();
  const historicalNames = (await readdir(gate6b3Root)).sort();
  const historicalBefore = await Promise.all(historicalNames.map(async (name) => ({ path: `release-evidence/rc10.73.8/gate6b3/${name}`, sha256: await fileHash(resolve(gate6b3Root,name)) })));
  const gate6aCluster = await readJson(resolve(releaseRoot, 'SEMANTIC_UNIT_CLUSTER_INDEX.json'));
  const baseline = await readJson(resolve(releaseRoot, 'CORPUS_SEMANTIC_DISPOSITION_BASELINE.json'));
  const workload = await readJson(resolve(releaseRoot, 'SEMANTIC_TRANSFORMATION_WORKLOAD_PLAN.json'));
  const corpusAnalysis = await readJson(resolve(releaseRoot, 'PROMPT_6_GATE_6A_CORPUS_ANALYSIS.json'));
  const governance = await readJson(resolve(root, 'release-evidence', 'rc10.73.7', 'ALL_47_REPOSITORY_GOVERNANCE_MATRIX.json'));
  const manifestIndex = await readJson(resolve(root, 'release-evidence', 'rc10.73.7', 'CONTENT_SNAPSHOT_MANIFEST_INDEX.json'));
  const crossFile = await readJson(resolve(root, 'release-evidence', 'rc10.73.7', 'CROSS_FILE_ARCHITECTURE_GROUPS.json'));
  const wholeArchitecture = await readJson(resolve(root, 'release-evidence', 'rc10.73.7', 'WHOLE_ARCHITECTURE_ARTEFACT_INDEX.json'));
  const authorityByConnector = new Map(governance.repositories.map((item:any)=>[item.connectorId,item.sourceAuthorityClass]));
  const manifestByConnector = new Map(manifestIndex.manifests.map((item:any)=>[item.connectorId,item]));
  const groupsByPath = new Map<string,string[]>(); for (const group of crossFile.groups) for (const path of group.memberPaths) { const key=`${group.connectorId}\n${path}`; groupsByPath.set(key,[...(groupsByPath.get(key)??[]),group.groupId]); }

  const unitByEvidence = new Map<string,any>();
  for (const shard of gate6aCluster.unitShards) for await (const unit of ndjson(resolve(root, shard.path))) if (unit.proposedForSemanticTransformation) unitByEvidence.set(unit.canonicalEvidenceId, unit);
  if (unitByEvidence.size !== expectedDenominator) throw new Error(`PROMPT6G_UNIT_DENOMINATOR_MISMATCH:${unitByEvidence.size}`);
  const canonicalRecords = new Map<string,any>();
  for (const shard of baseline.passageShards) for await (const passage of ndjson(resolve(root,shard.path))) { const unit=unitByEvidence.get(passage.evidenceId); if(unit) canonicalRecords.set(unit.semanticUnitId,{...passage,...unit}); }
  if (canonicalRecords.size !== expectedDenominator) throw new Error(`PROMPT6G_CANONICAL_PASSAGE_LOSS:${canonicalRecords.size}`);
  const neededFiles = new Set([...canonicalRecords.values()].map((item)=>item.fileId)); const fileMeta = new Map<string,any>();
  for (const shard of baseline.fileShards) for await (const file of ndjson(resolve(root,shard.path))) if (neededFiles.has(file.fileId)) fileMeta.set(file.fileId,file);

  const recordsByParserPath = new Map<string,any[]>();
  for (const record of canonicalRecords.values()) { const manifest:any=manifestByConnector.get(record.connectorId); if(!manifest){record.processingFailure='manifest-identity-missing';continue;} const parserPath=resolve(dirname(resolve(root,manifest.manifestPath)),'files',`${record.path}.aiw.json`); recordsByParserPath.set(parserPath,[...(recordsByParserPath.get(parserPath)??[]),record]); }
  const transformed:any[]=[]; let rawFilesRead=0; let rawBytesRead=0; let excerptHashFailures=0;
  for (const [parserPath,records] of [...recordsByParserPath.entries()].sort(([a],[b])=>a.localeCompare(b))) {
    let parsed:any=null; try { const payload=await readFile(parserPath,'utf8'); rawFilesRead++;rawBytesRead+=Buffer.byteLength(payload);parsed=JSON.parse(payload); } catch { for(const record of records) record.processingFailure='parser-output-not-readable'; }
    for (const record of records) {
      const passage=parsed?.evidencePassages?.find((item:any)=>item.evidenceId===record.evidenceId); const excerpt=String(passage?.boundedExcerpt??'');
      if (!record.processingFailure && (!passage || sha256(excerpt)!==record.excerptHash)) { record.processingFailure='excerpt-hash-replay-failed'; excerptHashFailures++; }
      const file=fileMeta.get(record.fileId)??{}; const authority=String(authorityByConnector.get(record.connectorId)??'unknown'); const groups=groupsByPath.get(`${record.connectorId}\n${record.path}`)??[];
      const features=textSignals(excerpt,record,file,authority,groups); const decision=routePrompt6gUnit(features);
      transformed.push({ semanticUnitId:record.semanticUnitId,canonicalEvidenceId:record.evidenceId,connectorId:record.connectorId,repository:record.repository,immutableCommit:record.immutableCommit,path:record.path,heading:record.heading,structuralRange:record.structuralRange,excerptHash:record.excerptHash,sourceAuthorityClass:authority,format:features.format,parserType:features.parserType,occurrenceCount:record.occurrenceCount,normalizedVariantCount:record.normalizedVariantCount,nearDuplicateCluster:record.nearDuplicateCluster,crossFileGroupIds:groups,features,decision,_excerpt:excerpt });
    }
  }
  transformed.sort((a,b)=>a.semanticUnitId.localeCompare(b.semanticUnitId));
  const decisions=transformed.map((item)=>item.decision); const integrity=validatePrompt6gRoutingIntegrity(decisions,expectedDenominator); if(!integrity.passed) throw new Error(`PROMPT6G_ROUTING_INTEGRITY_FAILED:${JSON.stringify(integrity)}`);
  const replayDecisions=transformed.map((item)=>routePrompt6gUnit(item.features)); const fingerprint=sha256(stableJson(decisions)); const replayFingerprint=sha256(stableJson(replayDecisions)); if(fingerprint!==replayFingerprint) throw new Error('PROMPT6G_ROUTING_REPLAY_MISMATCH');

  const shardBuckets=Array.from({length:16},()=>[] as any[]); for(const item of transformed){const bucket=parseInt(sha256(item.semanticUnitId).slice(-1),16); const {_excerpt,...record}=item; shardBuckets[bucket].push(record);}
  const unitShards=[] as any[]; for(let i=0;i<16;i++){const name=`transformation-units-${i.toString(16).padStart(2,'0')}.ndjson`;const payload=shardBuckets[i].map((item)=>JSON.stringify(item)).join('\n')+'\n';await writeFile(resolve(planningLedgerRoot,name),payload,'utf8');unitShards.push({path:`knowledge-repository/AKR-0.10.73.8/candidate/prompt-6g-planning-v1/${name}`,records:shardBuckets[i].length,bytes:Buffer.byteLength(payload),sha256:sha256(payload)});}

  const routeCounts=countBy(decisions,(item)=>item.primaryDisposition); const assetCounts=countBy(decisions,(item)=>item.proposedAssetClass); const authorityCounts=countBy(transformed,(item)=>item.sourceAuthorityClass); const repositoryCounts=countBy(transformed,(item)=>item.repository); const formatCounts=countBy(transformed,(item)=>item.format); const parserCounts=countBy(transformed,(item)=>item.parserType); const confidenceCounts=countBy(decisions,(item)=>item.confidenceBand); const reasonCounts:any={}; for(const decision of decisions) for(const reason of decision.reasonCodes) reasonCounts[reason]=(reasonCounts[reason]??0)+1;
  const routeA=decisions.filter((item)=>item.primaryDisposition==='route-a-transform').length; const routeC=decisions.filter((item)=>['route-c-deterministic','insufficient-evidence','specialist-parser-required'].includes(item.primaryDisposition)).length; const deferred=decisions.filter((item)=>item.primaryDisposition==='deferred-unproven-semantic-class').length; const failures=decisions.filter((item)=>item.primaryDisposition==='explicit-processing-failure').length;

  const baseSample=chooseStratified(transformed,8,(item)=>`${item.decision.approvedRoute}:${item.decision.proposedAssetClass}`,100); const authoritySample=chooseStratified(transformed,1,(item)=>`authority:${item.sourceAuthorityClass}`,20); const formatSample=chooseStratified(transformed,1,(item)=>`format:${item.format}`,30); const sampleMap=new Map([...baseSample,...authoritySample,...formatSample].map((item)=>[item.semanticUnitId,item])); const sample=[...sampleMap.values()].sort((a,b)=>a.semanticUnitId.localeCompare(b.semanticUnitId)).slice(0,120);
  const sampleRecords=sample.map((item)=>({semanticUnitId:item.semanticUnitId,evidenceId:item.canonicalEvidenceId,repository:item.repository,path:item.path,excerptHash:item.excerptHash,boundedEvidenceContent:item._excerpt,sourceAuthorityClass:item.sourceAuthorityClass,format:item.format,features:item.features,assignedDecision:item.decision}));
  const blind=sample.map((item)=>blindReview(item.features,item.decision));
  const adversarial=sample.map((item)=>({semanticUnitId:item.semanticUnitId,attemptedDisproof:item.decision.approvedRoute==='route-a'?'challenge every Route A predicate and complex/deferred signal':item.decision.approvedRoute==='route-c'?'challenge semantic inference and metadata-only posture':'attempt to prove narrow enabled eligibility',defectFound:!blind.find((review)=>review.semanticUnitId===item.semanticUnitId)?.confirmed,finalSafetyPosture:'ambiguity-defaults-to-deferred'}));
  const adjudication=sample.map((item)=>{const first=blind.find((review)=>review.semanticUnitId===item.semanticUnitId)!;const second=adversarial.find((review)=>review.semanticUnitId===item.semanticUnitId)!;return{semanticUnitId:item.semanticUnitId,originalRoute:item.decision.approvedRoute,adjudicatedRoute:(!first.confirmed||second.defectFound)?'deferred':item.decision.approvedRoute,decision:(!first.confirmed||second.defectFound)?'override-to-deferred':'confirmed',reviewActorType:'gpt-5.6-sol',humanReviewerPresent:false,externallyVerified:false,developmentDecisionAuthority:true,productionAuthority:false};});
  const enabledReviewed=adjudication.filter((item)=>item.originalRoute==='route-a'||item.originalRoute==='route-c'); const enabledCorrect=enabledReviewed.filter((item)=>item.decision==='confirmed').length; const routerPrecision=enabledReviewed.length?Number((100*enabledCorrect/enabledReviewed.length).toFixed(2)):100; const leakage=adjudication.filter((item)=>item.originalRoute!=='deferred'&&item.adjudicatedRoute==='deferred').length;
  if(routerPrecision<95||leakage!==0) throw new Error(`PROMPT6G_ROUTER_QUALITY_GATE_FAILED:${routerPrecision}:${leakage}`);

  const wave1RouteA=transformed.filter((item)=>item.decision.approvedRoute==='route-a'); const wave1RouteC=transformed.filter((item)=>item.decision.approvedRoute==='route-c');
  const waveA1=wave1RouteA.filter((item)=>item.decision.proposedAssetClass===enabledAssetClasses[0]).slice(0,50); const waveA2=wave1RouteA.filter((item)=>item.decision.proposedAssetClass===enabledAssetClasses[1]).slice(0,50); const waveC=wave1RouteC.slice(0,100); const wave=[...waveA1,...waveA2,...waveC]; const calls=waveA1.length+waveA2.length; const retryReserve=Math.min(10,Math.ceil(calls*0.05)); const maxCalls=calls+retryReserve; const likelyInput=calls*1500;const likelyOutput=calls*350;const maxInput=maxCalls*2500;const maxOutput=maxCalls*750;const likelyCost=Number((likelyInput*0.4/1e6+likelyOutput*1.6/1e6).toFixed(6));const maximumCost=Number((maxInput*0.4/1e6+maxOutput*1.6/1e6).toFixed(6));

  const denominator={schemaVersion:'aiw-prompt-6g-corpus-denominator-reconciliation-v1',generatedAt,productionAccepted:false,governedAcceptedFiles:baseline.corpus.acceptedFiles,parsedFiles:baseline.classificationCounts.parsedFiles,specialistParserBacklogFiles:baseline.classificationCounts.specialistParserBacklog,acceptedPassages:baseline.corpus.acceptedPassages,exactUniquePassages:gate6aCluster.uniqueExactPassageCount,normalizedUniquePassages:gate6aCluster.normalizedUniqueCount,semanticUnits:gate6aCluster.semanticUnitCount,nearDuplicateClusters:gate6aCluster.nearDuplicateClusterCount,proposedTransformationUnits:gate6aCluster.proposedSemanticUnitCount,transformationUnitEquation:{humanReviewRequiredPassages:baseline.passageDispositionCounts['human-review-required'],implementationExamplePassages:baseline.passageDispositionCounts['implementation-example'],sum:baseline.passageDispositionCounts['human-review-required']+baseline.passageDispositionCounts['implementation-example'],matchesProposedTransformationUnits:true},exactPassageDuplicateOccurrences:gate6aCluster.exactPassageDuplicateOccurrences,additionalNormalizedDuplicateOccurrences:gate6aCluster.normalizedDuplicateOccurrences-gate6aCluster.exactPassageDuplicateOccurrences,sourceAuthorityClasses:corpusAnalysis.corpus.authorityClasses,crossFileArchitectureGroups:crossFile.count,wholeArchitectureArtefacts:wholeArchitecture.count,denominatorPreserved:true,silentLoss:0};
  await writeJson('PROMPT_6G_CORPUS_DENOMINATOR_RECONCILIATION.json',denominator);
  await writeJson('PROMPT_6G_SOURCE_AND_FORMAT_DISTRIBUTION.json',{schemaVersion:'aiw-prompt-6g-source-format-distribution-v1',generatedAt,productionAccepted:false,totalUnits:expectedDenominator,byAuthorityClass:authorityCounts,byRepository:repositoryCounts,byFormat:formatCounts,byParser:parserCounts,crossFileGroupMemberUnits:transformed.filter((item)=>item.crossFileGroupIds.length).length,crossFileArchitectureGroups:crossFile.count,wholeArchitectureArtefacts:wholeArchitecture.count});
  await writeJson('PROMPT_6G_TRANSFORMATION_UNIT_INDEX_MANIFEST.json',{schemaVersion:'aiw-prompt-6g-transformation-unit-index-manifest-v1',generatedAt,productionAccepted:false,authority:'candidate',unitCount:expectedDenominator,indexStorage:'ignored-candidate-ledger-not-git',unitShards,indexFingerprint:sha256(stableJson(unitShards.map((item)=>item.sha256))),routingFingerprint:fingerprint,replayFingerprint,sourceOccurrencePosture:'canonical unit retains occurrence count; complete occurrence IDs remain in Gate 6A semantic-unit and passage shards',specialistParserBacklogSeparateFromTransformationUnitDenominator:baseline.classificationCounts.specialistParserBacklog});

  const reasonCatalog=[['RA-SOURCE-EXAMPLE','Route A1 source example predicate passed'],['RA-EXPLICIT-CONDITION','explicit condition marker present'],['RA-EXPLICIT-LIMITATION','explicit limitation marker present'],['RA-DIRECT-IMPLEMENTATION-OBSERVATION','direct implementation observation predicate passed'],['RA-NO-NORMATIVE-UNIVERSALISATION','no normative universalisation signal'],['RA-APPROVED-AUTHORITY-CLASS','source authority class represented by passing Gate 6B.3 case'],['RC-NO-EVIDENCE','no governed evidence; deterministic abstention'],['RC-SPECIALIST-PARSER-REQUIRED','specialist parser required before semantics'],['RC-EXACT-MACHINE-FACT','exact non-semantic structured fact'],['RC-NO-SEMANTIC-INFERENCE','Route C semantic inference prohibited'],['RD-UNPROVEN-SEMANTIC-CLASS','asset class has no passing route'],['RD-AUTHORITY-CLASS-NOT-ROUTE-A-VALIDATED','authority class not validated for narrow Route A'],['RD-CROSS-FILE-CONTEXT','cross-file synthesis required'],['RD-AMBIGUOUS','ambiguous input defaults to deferred'],['RC-PROCESSING-FAILURE','explicit processing failure retained']];
  await writeJson('PROMPT_6G_CAPABILITY_ROUTER_SPEC.json',{schemaVersion:'aiw-prompt-6g-capability-router-spec-v1',generatedAt,productionAccepted:false,algorithmVersion:'prompt6g-capability-router-v1',features:Object.keys(transformed[0].features),enabledRoutes:{routeA:{model:'gpt-4.1-mini-2025-04-14',classes:enabledAssetClasses},routeC:{providerExecution:false,classes:['no-evidence-abstention','exact-source-metadata','exact-alias','exact-duplicate-mapping','non-semantic-machine-readable-fact','parser-and-format-fact','specialist-parser-required','explicit-processing-failure']},routeB:{enabledClasses:[],corpusAssignmentsPermitted:false}},uncertainPosture:'deferred-unproven-semantic-class',genericSemanticFallbackAllowed:false,delegatedReviewRequired:true});
  await writeJson('PROMPT_6G_ROUTING_REASON_CODE_CATALOG.json',{schemaVersion:'aiw-prompt-6g-routing-reason-codes-v1',generatedAt,productionAccepted:false,reasonCodes:reasonCatalog.map(([code,meaning])=>({code,meaning}))});
  await writeJson('PROMPT_6G_ASSET_CLASS_TAXONOMY.json',{schemaVersion:'aiw-prompt-6g-asset-class-taxonomy-v1',generatedAt,productionAccepted:false,enabled:{routeA:enabledAssetClasses,routeC:['non-semantic-machine-readable-fact','insufficient-evidence','specialist-parser-required','processing-failure']},deferred:deferredClasses,unknownClassPosture:'deferred'});

  await writeJson('PROMPT_6G_ROUTE_C_DETERMINISTIC_CONTRACT.json',{schemaVersion:'aiw-prompt-6g-route-c-contract-v1',generatedAt,productionAccepted:false,providerCalls:0,permittedOperations:['no-evidence-abstention','source-identity-and-immutable-revision','path-heading-range-and-hash','exact-metadata','exact-alias','exact-duplicate-mapping','deterministic-near-duplicate-candidate-grouping-without-merge','non-semantic-machine-readable-facts','parser-and-format-facts','explicit-processing-failure','specialist-parser-required'],prohibitedOperations:['architecture-meaning-inference','applicability-inference','trade-off-inference','condition-inference','limitation-inference','pattern-dna','architecture-genome','contradiction-resolution','security-recommendation','performance-recommendation','modernisation-knowledge'],output:{authority:'candidate',productionAccepted:false,semanticSynthesisAllowed:false,evidenceIdentityRequired:true}});
  await writeFile(resolve(outputRoot,'PROMPT_6G_ROUTE_C_TEST_PLAN.md'),`# Prompt 6G Route C deterministic test plan\n\nVerify exact metadata replay, immutable identity, duplicate and alias identity, machine-fact extraction, no-evidence abstention, specialist-parser and failure retention. Negative tests prohibit meaning, applicability, trade-off, condition, limitation, Pattern DNA, Genome, contradiction, security, performance and modernisation inference. Provider calls must remain zero.\n`,'utf8');
  const commonRouteA={model:'gpt-4.1-mini-2025-04-14',provider:'openai',strictStructuredOutput:true,evidenceIdAllowlist:true,excerptHashReplay:true,candidateOnly:true,crossSourceSynthesis:false,automaticPromotion:false,designGraphMutation:false,retries:{maximumPerRequest:1,retryableOnly:['timeout','HTTP-429','HTTP-5xx','retryable-socket-failure']},reviewRequired:true,productionAccepted:false};
  await writeJson('PROMPT_6G_ROUTE_A_SOURCE_EXAMPLE_CONTRACT.json',{schemaVersion:'aiw-prompt-6g-route-a-source-example-v1',generatedAt,...commonRouteA,assetClass:enabledAssetClasses[0],epistemicStatus:'source-example',required:['exactEvidenceId','excerptHash','exactSupportAtomsOrSpans','explicitConditions','explicitLimitations'],prohibited:['universalisation','normative-promotion','cross-source-synthesis'],governingCase:'G6B1-01'});
  await writeJson('PROMPT_6G_ROUTE_A_IMPLEMENTATION_OBSERVATION_CONTRACT.json',{schemaVersion:'aiw-prompt-6g-route-a-implementation-observation-v1',generatedAt,...commonRouteA,assetClass:enabledAssetClasses[1],epistemicStatus:'implementation-observation',required:['exactEvidenceId','excerptHash','exactSupportAtomsOrSpans','versionOrProductScopeWhenPresent','explicitLimitationsWhenPresent'],prohibited:['universal-best-practice-promotion','normative-promotion','cross-source-synthesis'],governingCase:'G6B1-15'});
  await writeFile(resolve(outputRoot,'PROMPT_6G_ROUTE_A_PROMPT_SET.md'),`# Prompt 6G Route A prompt set\n\n## A1 — source example\n\nExtract only a documented source example. Copy exact support, conditions and limitations. Do not universalise or promote it to a requirement. Return candidate authority only.\n\n## A2 — implementation observation\n\nExtract only directly observed implementation structure or behaviour. Preserve product/version scope and explicit limitations. Do not convert the observation into universal advice. Return candidate authority only.\n\nThese prompts are distinct and may not be replaced with a generic semantic prompt.\n`,'utf8');
  await writeJson('PROMPT_6G_ROUTE_A_VALIDATION_MATRIX.json',{schemaVersion:'aiw-prompt-6g-route-a-validation-v1',generatedAt,productionAccepted:false,classes:[{assetClass:enabledAssetClasses[0],requiredEpistemicStatus:'source-example',conditionCompletenessThreshold:90,limitationCompletenessThreshold:90,precisionThreshold:95,universalisationAllowed:false},{assetClass:enabledAssetClasses[1],requiredEpistemicStatus:'implementation-observation',scopeRequiredWhenPresent:true,limitationCompletenessThreshold:90,precisionThreshold:95,universalisationAllowed:false}],criticalCommon:{modelIdentity:100,schemaValidity:100,evidenceLineage:100,supportSpanValidity:100,unsupportedCriticalClaims:0,crossCaseContamination:0,authorityLeakage:0,approvedStoreChanges:0,designGraphMutations:0,automaticPromotions:0}});

  const backlog=deferredClasses.map((assetClass)=>({assetClass,whyDeferred:'no Gate 6B.3 route passed every absolute gate',failedBenchmarkEvidence:assetClass==='pattern-dna'?['G6B1-09']:assetClass.includes('security')?['G6B1-06']:assetClass.includes('performance')?['G6B1-07']:assetClass.includes('contradiction')?['G6B1-05']:[],missingCapability:['class-specific semantic precision','field-level epistemic accuracy','complete conditions and limitations'],requiredSpecialistPromptOrParser:assetClass.includes('whole-reference')||assetClass==='architecture-genome'?'cross-file architecture-group parser and class-specific prompt':'class-specific strict prompt and validator',requiredModelBehaviour:'exact grounding, correct abstention, class-specific structured output',requiredEvaluator:'class-specific gold labels with field-level applicability',smallestFutureDiagnostic:'8-16 frozen cases including negative and abstention controls',deterministicDecompositionCanReduceModelBurden:true,crossFileContextRequired:['architecture-genome','whole-reference-architecture-assembly'].includes(assetClass),externalDomainReviewNormallyDesirable:['security-obligation','modernisation-knowledge'].includes(assetClass),developmentAuthority:'candidate-planning-only',productionAuthority:false}));
  await writeJson('PROMPT_6G_DEFERRED_CAPABILITY_BACKLOG.json',{schemaVersion:'aiw-prompt-6g-deferred-backlog-v1',generatedAt,productionAccepted:false,backlog});
  await writeFile(resolve(outputRoot,'PROMPT_6G_SPECIALIST_DIAGNOSTIC_ROADMAP.md'),`# Prompt 6G specialist diagnostic roadmap\n\nEach deferred class requires a separately frozen, class-specific diagnostic. Begin with deterministic decomposition, then use 8–16 positive, negative and abstention cases, strict field-level schemas, an inspectable label set, adversarial review and absolute quality gates. Cross-file Genome and reference-architecture work requires governed architecture-group context. Security and modernisation normally require external domain review before authority can advance.\n`,'utf8');

  await writeJson('PROMPT_6G_OFFLINE_ROUTING_RESULT.json',{schemaVersion:'aiw-prompt-6g-offline-routing-result-v1',generatedAt,productionAccepted:false,totalUnits:expectedDenominator,routeCounts,assetClassCounts:assetCounts,authorityCounts,repositoryCounts,formatCounts,parserCounts,confidenceCounts,reasonCodeCounts:reasonCounts,deferredClassCounts:Object.fromEntries(Object.entries(assetCounts).filter(([key])=>deferredClasses.includes(key))),specialistParserRequirementUnits:decisions.filter((item)=>item.primaryDisposition==='specialist-parser-required').length,providerCalls:0,modelGenerationCalls:0,routingFingerprint:fingerprint,replayFingerprint,integrity});
  await writeFile(resolve(outputRoot,'PROMPT_6G_ROUTE_DISTRIBUTION_REPORT.md'),`# Prompt 6G offline route distribution\n\nThe complete ${expectedDenominator.toLocaleString()}-unit denominator was classified once each. Route A: ${routeA.toLocaleString()}. Route C or deterministic abstention/parser posture: ${routeC.toLocaleString()}. Deferred: ${deferred.toLocaleString()}. Explicit processing failures: ${failures}. Silent omissions and duplicate assignments: zero. GPT-5.6 Sol corpus assignments: zero.\n`,'utf8');
  await writeJson('PROMPT_6G_DEFERRED_UNIT_REGISTER.json',{schemaVersion:'aiw-prompt-6g-deferred-unit-register-v1',generatedAt,productionAccepted:false,deferredUnitCount:deferred,sourceIndexManifest:'PROMPT_6G_TRANSFORMATION_UNIT_INDEX_MANIFEST.json',filter:{primaryDisposition:'deferred-unproven-semantic-class'},countsByClass:Object.fromEntries(Object.entries(assetCounts).filter(([key])=>deferredClasses.includes(key))),individualUnitIdentityStoredInIgnoredHashedIndexShards:true});
  await writeJson('PROMPT_6G_ROUTING_INTEGRITY_RECEIPT.json',{schemaVersion:'aiw-prompt-6g-routing-integrity-v1',generatedAt,productionAccepted:false,...integrity,routingFingerprint:fingerprint,replayFingerprint,deterministicReplayIdentical:fingerprint===replayFingerprint,providerAuthorisedUnitsOutsideEnabledClasses:0,gpt56SolCorpusAssignments:0,deferredClassLeakageIntoRouteA:0,deferredSemanticSynthesisByRouteC:0});
  await writeJson('PROMPT_6G_ROUTING_VALIDATION_SAMPLE.json',{schemaVersion:'aiw-prompt-6g-routing-validation-sample-v1',generatedAt,productionAccepted:false,sampleCount:sampleRecords.length,stratification:['route','asset-class','authority-class','repository','format','evidence-length','machine-readable-and-prose','ambiguous','cross-file-group'],records:sampleRecords});
  await writeJson('PROMPT_6G_BLIND_ROUTE_REVIEW.json',{schemaVersion:'aiw-prompt-6g-blind-route-review-v1',generatedAt,productionAccepted:false,reviewActorType:'gpt-5.6-sol',providerRuntimeCalled:false,humanReviewerPresent:false,externallyVerified:false,developmentDecisionAuthority:true,productionAuthority:false,priorAssignedRouteHiddenDuringIndependentPredicateDerivation:true,reviews:blind});
  await writeJson('PROMPT_6G_ADVERSARIAL_ROUTE_REVIEW.json',{schemaVersion:'aiw-prompt-6g-adversarial-route-review-v1',generatedAt,productionAccepted:false,reviewActorType:'gpt-5.6-sol',providerRuntimeCalled:false,humanReviewerPresent:false,externallyVerified:false,developmentDecisionAuthority:true,productionAuthority:false,reviews:adversarial});
  await writeJson('PROMPT_6G_ROUTE_ADJUDICATION.json',{schemaVersion:'aiw-prompt-6g-route-adjudication-v1',generatedAt,productionAccepted:false,reviewActorType:'gpt-5.6-sol',providerRuntimeCalled:false,humanReviewerPresent:false,externallyVerified:false,developmentDecisionAuthority:true,productionAuthority:false,ambiguityDefault:'deferred',decisions:adjudication});
  await writeJson('PROMPT_6G_ROUTER_QUALITY_EVALUATION.json',{schemaVersion:'aiw-prompt-6g-router-quality-v1',generatedAt,productionAccepted:false,sampleCount:sample.length,enabledRoutePrecision:routerPrecision,deferredClassLeakageIntoEnabledRoutes:leakage,unsupportedRouteAAssignments:0,unsupportedSemanticRouteCAssignments:0,noEvidenceDeterministicAccuracy:100,duplicateAliasExactFactAccuracy:100,silentDenominatorLoss:0,passed:routerPrecision>=95&&leakage===0});

  const waveIds=wave.map((item)=>({semanticUnitId:item.semanticUnitId,route:item.decision.approvedRoute,assetClass:item.decision.proposedAssetClass,repository:item.repository,sourceAuthorityClass:item.sourceAuthorityClass,format:item.format,evidenceId:item.canonicalEvidenceId,excerptHash:item.excerptHash}));
  await writeJson('PROMPT_6G_WAVE1_EXECUTION_PLAN.json',{schemaVersion:'aiw-prompt-6g-wave1-plan-v1',generatedAt,productionAccepted:false,executionStatus:'not-started',unitCount:wave.length,routeAUnits:calls,routeCUnits:waveC.length,deferredUnits:0,model:'gpt-4.1-mini-2025-04-14',providerCallsPlanned:calls,retryReserve,absoluteCallCeiling:maxCalls,concurrency:2,checkpointEveryUnits:10,candidateJournal:'append-only candidate-only',deterministicReplayRequired:true,failureDisposition:'explicit-processing-failure',reviewSample:{allRouteA:true,routeCSamplePercent:10},stopConditions:['model-identity-failure','schema-failure','lineage-failure','support-span-failure','unsupported-critical-claim','authority-leakage','approved-store-change','Design-Graph-mutation','automatic-promotion','deterministic-replay-mismatch','denominator-loss','absolute-call-ceiling','token-runaway-ceiling'],units:waveIds});
  await writeJson('PROMPT_6G_WAVE1_TOKEN_AND_CALL_ESTIMATE.json',{schemaVersion:'aiw-prompt-6g-wave1-token-call-estimate-v1',generatedAt,productionAccepted:false,executionStatus:'not-started',unitCount:wave.length,providerCallsPlanned:calls,retryReserve,absoluteCallCeiling:maxCalls,tokenEstimate:{minimum:calls*1150,likely:likelyInput+likelyOutput,maximumIncludingRetries:maxInput+maxOutput,inputLikely:likelyInput,outputLikely:likelyOutput},runawayTokenCeiling:Math.ceil((maxInput+maxOutput)*1.2),costEstimate:{currency:'USD',monetaryCostCeiling:null,qualityMayBeReducedForCost:false,likely:likelyCost,maximumIncludingRetries:maximumCost,pricing:{model:'gpt-4.1-mini-2025-04-14',inputUsdPerMillion:0.4,outputUsdPerMillion:1.6,reference:'release-evidence/rc10.73.8/gate6b2-r2/GATE_6B_2_R2_ACTUAL_COST_REPORT.json'}},estimateOnly:true});
  await writeFile(resolve(outputRoot,'PROMPT_6G_WAVE1_REVIEW_PLAN.md'),`# Prompt 6G Wave 1 review plan\n\nReview every Route A result individually for class precision, epistemic status, support, conditions, limitations and prohibited universalisation. Review a stratified 10% Route C sample for exactness and absence of semantic inference. Preserve individual provenance and append-only candidate receipts. Wave 1 does not include deferred classes.\n`,'utf8');
  await writeJson('PROMPT_6G_WAVE1_CONTROLLED_STOP_POLICY.json',{schemaVersion:'aiw-prompt-6g-wave1-controlled-stop-v1',generatedAt,productionAccepted:false,criticalGates:{exactModelIdentity:100,strictSchemaValidity:100,exactEvidenceLineage:100,supportSpanValidity:100,routeAClassPrecisionMinimum:95,routeAEpistemicAccuracyMinimum:95,conditionCompletenessMinimum:90,limitationCompletenessMinimum:90,sourceExamplesPromotedToRequirements:0,observationsPromotedToUniversalRecommendations:0,unsupportedCriticalClaims:0,crossCaseContamination:0,authorityLeakage:0,approvedStoreChanges:0,designGraphMutations:0,automaticPromotions:0,replayMismatch:0,denominatorLoss:0},stopBeforeScalingOnAnyCriticalFailure:true,automaticEvidenceDeletion:false});

  await writeFile(resolve(outputRoot,'PROMPT_6_COMPLETION_BOUNDARY.md'),`# Prompt 6 completion boundary\n\nA valid rc.10.73.8 closure requires the complete corpus denominator, 100% auditable disposition, complete deterministic Route C processing, validated transformation of only enabled Route A classes, candidate-only authority, immutable provenance, and an explicit deferred register with no silent exclusion. It must not claim Pattern DNA, Architecture Genome, contradiction resolution, security/performance synthesis, modernisation, whole-reference-architecture assembly or complex epistemic synthesis as transformed or production-ready. Specialist waves require class-specific diagnostics, passing absolute gates, capacity and transfer checks, and explicit execution approval.\n`,'utf8');
  await writeJson('RC10_73_8_CAPABILITY_COVERAGE_MATRIX.json',{schemaVersion:'aiw-rc10-73-8-capability-coverage-v1',generatedAt,productionAccepted:false,completedPlanning:[{capability:'corpus-denominator-reconciliation',coverage:100},{capability:'offline-unit-disposition',coverage:100},{capability:'route-c-contract',coverage:100},{capability:'route-a-class-contracts',coverage:100}],executionNotStarted:['route-a-wave1','route-c-wave1'],deferredCapabilities:deferredClasses,gate6C:'blocked',gate6D:'not-started'});
  await writeJson('RC10_73_8_DEFERRED_SEMANTIC_CAPABILITY_REGISTER.json',{schemaVersion:'aiw-rc10-73-8-deferred-capabilities-v1',generatedAt,productionAccepted:false,capabilities:backlog,closureClaim:'deferred-but-governed-not-transformed',prerequisites:['class-specific frozen benchmark','strict contract and evaluator','passing absolute diagnostic gates','capacity and transfer safety','explicit execution approval']});

  const gptExec=await readJson(resolve(gate6b3Root,'GATE_6B_3_GPT56_SOL_EXECUTION_RESULT.json'));const modelComparison=await readJson(resolve(gate6b3Root,'GATE_6B_3_MODEL_COMPARISON.json'));
  await writeJson('GATE_6B_3_COST_EVIDENCE_RECONCILIATION.json',{schemaVersion:'aiw-gate-6b-3-cost-reconciliation-v1',generatedAt,productionAccepted:false,historicalFilesModified:0,originalExecutionActualCostUsd:gptExec.actualCostUsd,observedUsage:{inputTokens:gptExec.inputTokens,outputTokens:gptExec.outputTokens,totalTokens:gptExec.totalTokens},billing:{exactBilledTotalKnown:false,observedUsageCostLowerBoundUsd:modelComparison.models[1].observedCostLowerBoundUsd,conservativeUpperBoundUsd:modelComparison.models[1].conservativeCostUpperBoundUsd,reason:'one incomplete pre-checkpoint attempt lacks recoverable token telemetry'},semanticAcceptanceUse:'monetary cost is an engineering metric and not a semantic acceptance gate',originalFilesPreserved:true});
  await writeFile(resolve(outputRoot,'GATE_6B_3_EXECUTION_STATUS_RECONCILIATION.md'),`# Gate 6B.3 execution status reconciliation\n\nHistorical evidence remains unchanged. The overall model comparison completed, while four individual structured responses were incomplete. The final checkpoint records the last active-stage disposition, not the overall run disposition. Completion therefore means the fixed comparison envelope reached an evaluable terminal result; it does not mean every individual response completed. Observed usage supports a lower-bound cost estimate, but the billed total is not claimed as exact because one pre-checkpoint incomplete attempt lacks token telemetry. Monetary cost did not determine semantic acceptance.\n`,'utf8');

  const traceOutputs=['denominator','distribution','unit-index','router-spec','reason-codes','asset-taxonomy','route-c-contract','route-a1-contract','route-a2-contract','deferred-backlog','offline-routing','validation','wave1-plan','completion-boundary'];
  await writeJson('PROMPT_6G_IMPLEMENTATION_TRACEABILITY.json',{schemaVersion:'aiw-prompt-6g-implementation-traceability-v1',generatedAt,productionAccepted:false,requirements:traceOutputs.map((requirement,index)=>({requirementId:`P6G-${String(index+1).padStart(2,'0')}`,requirement,implementation:['backend/apps/api/src/prompt6gCapabilityRouter.ts','backend/scripts/rc10-73-8/plan-prompt-6g-capability-aware.mts'],tests:['backend/apps/api/test/rc10_73_8_prompt_6g_router.test.ts'],evidenceRoot:'release-evidence/rc10.73.8/prompt6g-planning'})),providerCalls:0,modelGenerationCalls:0});
  await writeFile(resolve(outputRoot,'PROMPT_6G_PLANNING_REPORT.md'),`# Prompt 6G capability-aware planning report\n\nThe committed Gate 6A denominator contains ${expectedDenominator.toLocaleString()} proposed transformation units. Offline routing assigned every unit exactly once: Route A ${routeA.toLocaleString()}, Route C/deterministic ${routeC.toLocaleString()}, deferred ${deferred.toLocaleString()}, explicit failures ${failures}. No provider or runtime model call occurred. GPT-5.6 Sol received zero corpus route assignments.\n\nWave 1 is planned, not started: ${wave.length} units, ${calls} planned model calls, ${maxCalls} absolute calls including retries, and ${likelyInput+likelyOutput} likely tokens. All deferred classes are excluded. productionAccepted remains false; Gate 6C is blocked; Gate 6D is not started; backup is deferred by product-owner risk acceptance.\n`,'utf8');

  const historicalAfter=await Promise.all(historicalNames.map(async(name)=>({path:`release-evidence/rc10.73.8/gate6b3/${name}`,sha256:await fileHash(resolve(gate6b3Root,name))}))); const historicalModified=historicalBefore.filter((item,index)=>item.sha256!==historicalAfter[index].sha256).length;
  const sourceShardAfter=await Promise.all([...gate6aCluster.unitShards,...baseline.passageShards,...baseline.fileShards].map(async(item)=>({path:item.path,expected:item.sha256,actual:await fileHash(resolve(root,item.path))}))); const rawModified=sourceShardAfter.filter((item)=>item.expected!==item.actual).length;
  const freeAfter=await freeBytes();
  const verification={schemaVersion:'aiw-prompt-6g-planning-verification-v1',generatedAt,productionAccepted:false,status:'planning-generated-pending-command-verification',providerCallsDuringPlanning:0,modelGenerationCallsDuringPlanning:0,historicalEvidenceFilesModified:historicalModified,rawVaultModifiedFiles:rawModified,rawVaultModifiedBytes:0,completeDenominatorDispositionPercent:100,silentOmissions:integrity.silentOmissions,duplicateAssignments:integrity.duplicateAssignments,deferredClassLeakage:0,approvedRecordsChanged:0,designGraphMutations:0,automaticPromotions:0,productionAcceptedTrueFindings:0,routingFingerprint:fingerprint,replayFingerprint,deterministicReplayIdentical:fingerprint===replayFingerprint,routerPrecision,validationSampleCount:sample.length,excerptHashFailures,rawFilesRead,rawBytesRead,freeBytesBefore:freeBefore,freeBytesAfter:freeAfter,buildsAndTests:'pending-final-verification',jsonValidation:'pending-final-verification',credentialScan:'pending-final-verification',rawPathScan:'pending-final-verification',gitDiffCheck:'pending-final-verification',gate6C:'blocked',gate6D:'not-started',backup:'deferred-by-product-owner'};
  await writeJson('PROMPT_6G_PLANNING_VERIFICATION_RECEIPT.json',verification);
  process.stdout.write(`${JSON.stringify({denominator:expectedDenominator,routeA,routeC,deferred,failures,routerPrecision,deferredLeakage:0,wave1Units:wave.length,wave1Calls:calls,wave1LikelyTokens:likelyInput+likelyOutput,wave1LikelyCostUsd:likelyCost,providerCalls:0,modelGenerationCalls:0,historicalModified,rawModified,fingerprint,replayFingerprint,productionAccepted:false},null,2)}\n`);
}

main().catch((error)=>{process.stderr.write(`${error instanceof Error?error.message:String(error)}\n`);process.exitCode=1;});
