const path = require('node:path');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const { chromium } = require(process.env.AIW_PLAYWRIGHT_MODULE || path.resolve(__dirname, '../../../v5/node_modules/@playwright/test'));
(async () => {
  const browser = await chromium.launch({headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[], checks=[];
  page.on('pageerror',e=>errors.push(e.message));
  const base=process.env.AIW_COLLECTION_URL || 'http://127.0.0.1:8766';
  const settled=()=>page.waitForFunction(()=>document.querySelector('#results').getAttribute('aria-busy')!=='true');
  try {
    await page.goto(base);
    await page.locator('#results .card').first().waitFor();
    const catalog=await (await page.request.get(base+'/catalog.json')).json();
    assert.equal(catalog.mode,'collection');assert.equal(catalog.stats.repositories,47);
    assert.equal(catalog.stats.fileEntries,186219);assert.equal(catalog.collectionReceipt.candidateShards,16);
    assert.equal(await page.locator('#source-count').innerText(),'47');
    checks.push('All 47 selected snapshots and 16 candidate shards represented');
    const first=await page.locator('#results .card').evaluateAll(cards=>cards.map(c=>c.dataset.id));
    assert.equal(first.length,40);
    await page.locator('#more').click();await settled();
    const second=await page.locator('#results .card').evaluateAll(cards=>cards.map(c=>c.dataset.id));
    assert.equal(second.length,40);assert.ok(second.every(id=>!first.includes(id)));
    await page.locator('#previous').click();await settled();
    assert.deepEqual(await page.locator('#results .card').evaluateAll(cards=>cards.map(c=>c.dataset.id)),first);
    checks.push('Bounded pagination with no duplicate or skipped first-page records');
    await page.locator('#repo').selectOption('arc42/arc42-template');await settled();
    await page.locator('#search').fill('introduction');await settled();
    assert.ok(await page.locator('#results .card').count()>0);
    await page.locator('#results .card').first().click();
    await page.locator('#read-source').click();
    await page.locator('.source-text').waitFor();
    assert.ok((await page.locator('.source-text').innerText()).length>100);
    assert.match(await page.locator('#detail').innerText(),/Content SHA-256 verified on this read/);
    checks.push('Repository and full-text search with hash-verified downloaded source preview');
    await page.screenshot({path:path.resolve(__dirname,'../test-results/collection-desktop.png'),fullPage:true});
    await page.locator('#search').fill('');await settled();
    await page.locator('#availability').selectOption('');await settled();
    await page.locator('#kind').selectOption('candidate-semantic-unit');await settled();
    await page.locator('#results .card').first().click();
    await page.locator('#linked-source').click();
    await page.locator('#read-source').waitFor();
    assert.match(await page.locator('#detail').innerText(),/acquired-file/);
    checks.push('Candidate-to-source navigation pins repository, revision and file path');
    await page.locator('#repo').selectOption('');await settled();
    await page.locator('#kind').selectOption('acquired-file');await settled();
    await page.locator('#availability').selectOption('quarantined');await settled();
    await page.locator('#results .card').first().click();
    assert.equal(await page.locator('#read-source').count(),0);
    assert.match(await page.locator('#detail').innerText(),/preview unavailable: quarantined/);
    const blockedId=await page.locator('#results .card').first().getAttribute('data-id');
    assert.equal((await page.request.get(base+'/api/records/'+blockedId+'/content')).status(),403);
    checks.push('Quarantined entries visible for coverage but unavailable to source reader');
    await page.locator('#search').fill('zzzzz_no_possible_record_8291741');await settled();
    assert.equal(await page.locator('#results .card').count(),0);
    assert.equal(await page.locator('#result-count').innerText(),'0 results');
    checks.push('Empty query results are honest and have no stale cards');
    await page.locator('#collection-coverage summary').click();
    assert.match(await page.locator('#coverage-details').innerText(),/Historical snapshots not double-counted: 1/);
    checks.push('Historical duplicate and file-disposition coverage disclosed');
    await page.locator('[data-view="guide"]').click();
    await page.waitForFunction(()=>document.querySelector('#list-title').textContent.includes('guide'));
    assert.equal(await page.locator('#results .card').count(),10);
    await page.locator('#results .card').first().click();
    await page.locator('#detail button').filter({hasText:'the two layers'}).click();
    assert.equal(await page.locator('#detail h2').innerText(),'Keep evidence and understanding distinct');
    await page.locator('[data-view="sources"]').click();
    await page.waitForFunction(()=>document.querySelector('#list-title').textContent==='Selected source files');
    await page.locator('#results .card').first().click();
    assert.match(await page.locator('#detail').innerText(),/39338 of 39338/);
    checks.push('Guide links and complete selected-manifest receipts preserved');
    await page.setViewportSize({width:390,height:844});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
    await page.screenshot({path:path.resolve(__dirname,'../test-results/collection-mobile.png'),fullPage:true});
    checks.push('Mobile layout has no horizontal overflow');
    await page.locator('[data-view="library"]').click();
    await page.waitForFunction(()=>document.querySelector('#list-title').textContent==='Knowledge collection');
    await page.locator('#repo').selectOption('arc42/arc42-template');await settled();
    await page.locator('#availability').selectOption('verified-text');await settled();
    await page.locator('#results .card').first().click();
    await page.route('**/api/records/*/content',async route=>{
      const response=await route.fetch();const data=await response.json();data.text='<img src=x onerror="window.pwned=true"><script>window.pwned=true</script>';
      await route.fulfill({response,json:data});
    });
    await page.locator('#read-source').click();await page.locator('.source-text').waitFor();
    assert.equal(await page.locator('#detail img,#detail script').count(),0);
    assert.equal(await page.evaluate(()=>window.pwned),undefined);
    assert.ok((await page.locator('.source-text').innerText()).includes('<script>'));
    checks.push('Untrusted downloaded markup is rendered only as inert text');
    assert.equal((await page.request.get(base+'/collection.sqlite')).status(),404);
    assert.equal((await page.request.get(base+'/api/search',{headers:{Origin:'https://attacker.example'}})).status(),403);
    checks.push('Database downloads and cross-origin API requests are blocked');
    assert.deepEqual(errors,[]);
    const evidence={passed:true,checks,pageErrors:errors,coverage:catalog.stats,productionAccepted:false};
    fs.writeFileSync(path.resolve(__dirname,'../evidence/full-collection-browser.json'),JSON.stringify(evidence,null,2)+'\n');
    console.log(JSON.stringify({passed:true,checks}));
  } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
